
_sprA05_04:
		.BYTE	$04
		.BYTE	$01,$A4,$02,$F8
		.BYTE	$01,$A4,$42,$00
		.BYTE	$F1,$94,$02,$F8
		.BYTE	$F1,$94,$42,$00
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$00
_sprA05_05:
		.BYTE	$04
		.BYTE	$01,$A2,$42,$00
		.BYTE	$01,$B2,$42,$F8
		.BYTE	$F1,$92,$42,$00
		.BYTE	$F1,$B0,$42,$F8
		.BYTE	$02
		.BYTE	$06,$3E,$02,$00
		.BYTE	$06,$3E,$42,$F8
		.BYTE	$00
_sprA05_06:
		.BYTE	$04
		.BYTE	$01,$82,$02,$F8
		.BYTE	$01,$82,$42,$00
		.BYTE	$F1,$90,$02,$F8
		.BYTE	$F1,$90,$42,$00
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$00
_sprA05_07:
		.BYTE	$04
		.BYTE	$01,$A2,$02,$F8
		.BYTE	$01,$B2,$02,$00
		.BYTE	$F1,$92,$02,$F8
		.BYTE	$F1,$B0,$02,$00
		.BYTE	$02
		.BYTE	$06,$3E,$02,$00
		.BYTE	$06,$3E,$42,$F8
		.BYTE	$00
_sprA05_08:
		.BYTE	$04
		.BYTE	$00,$A4,$02,$F8
		.BYTE	$00,$A4,$42,$00
		.BYTE	$F0,$84,$02,$F8
		.BYTE	$F0,$84,$42,$00
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$00
_sprA05_09:
		.BYTE	$04
		.BYTE	$00,$A2,$42,$00
		.BYTE	$00,$B2,$42,$F8
		.BYTE	$F0,$A0,$42,$00
		.BYTE	$F0,$B0,$42,$F8
		.BYTE	$02
		.BYTE	$06,$3E,$02,$00
		.BYTE	$06,$3E,$42,$F8
		.BYTE	$00
_sprA05_0A:
		.BYTE	$04
		.BYTE	$00,$82,$02,$F8
		.BYTE	$00,$82,$42,$00
		.BYTE	$F0,$80,$02,$F8
		.BYTE	$F0,$80,$42,$00
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$00
_sprA05_0B:
		.BYTE	$04
		.BYTE	$00,$A2,$02,$F8
		.BYTE	$00,$B2,$02,$00
		.BYTE	$F0,$A0,$02,$F8
		.BYTE	$F0,$B0,$02,$00
		.BYTE	$02
		.BYTE	$06,$3E,$02,$00
		.BYTE	$06,$3E,$42,$F8
		.BYTE	$00
_sprA05_0C:
		.BYTE	$04
		.BYTE	$00,$A4,$02,$FA
		.BYTE	$00,$A4,$42,$02
		.BYTE	$F0,$84,$02,$FA
		.BYTE	$F0,$84,$42,$02
		.BYTE	$02
		.BYTE	$08,$3E,$02,$02
		.BYTE	$08,$3E,$42,$FA
		.BYTE	$00
_sprA05_0D:
		.BYTE	$06
		.BYTE	$00,$A2,$42,$02
		.BYTE	$00,$B2,$42,$FA
		.BYTE	$06,$3E,$02,$02
		.BYTE	$06,$3E,$42,$FA
		.BYTE	$F0,$A0,$42,$02
		.BYTE	$F0,$B0,$42,$FA
		.BYTE	$00
_sprA05_0E:
		.BYTE	$04
		.BYTE	$00,$82,$02,$FA
		.BYTE	$00,$82,$42,$02
		.BYTE	$F0,$80,$02,$FA
		.BYTE	$F0,$80,$42,$02
		.BYTE	$02
		.BYTE	$08,$3E,$02,$02
		.BYTE	$08,$3E,$42,$FA
		.BYTE	$00
_sprA05_0F:
		.BYTE	$06
		.BYTE	$00,$A2,$02,$FA
		.BYTE	$00,$B2,$02,$02
		.BYTE	$06,$3E,$02,$02
		.BYTE	$06,$3E,$42,$FA
		.BYTE	$F0,$A0,$02,$FA
		.BYTE	$F0,$B0,$02,$02
		.BYTE	$00
_sprA05_10:
		.BYTE	$03
		.BYTE	$00,$B4,$02,$F8
		.BYTE	$F0,$96,$02,$F8
		.BYTE	$F0,$86,$02,$F0
		.BYTE	$00
_sprA05_11:
		.BYTE	$02
		.BYTE	$F8,$B6,$02,$F8
		.BYTE	$F8,$A6,$02,$F0
		.BYTE	$00
_sprA05_12:
		.BYTE	$03
		.BYTE	$00,$B4,$42,$00
		.BYTE	$F0,$96,$42,$00
		.BYTE	$F0,$86,$42,$08
		.BYTE	$00
_sprA05_13:
		.BYTE	$02
		.BYTE	$F8,$A6,$42,$08
		.BYTE	$F8,$B6,$42,$00
		.BYTE	$00
_sprA05_14:
		.BYTE	$04
		.BYTE	$00,$F9,$00,$02
		.BYTE	$00,$F9,$00,$F7
		.BYTE	$F0,$E9,$03,$F8
		.BYTE	$F0,$E9,$43,$00
		.BYTE	$00
_sprA05_15:
		.BYTE	$02
		.BYTE	$F8,$CF,$03,$F8
		.BYTE	$F8,$DF,$03,$00
		.BYTE	$00
_sprA05_16:
		.BYTE	$02
		.BYTE	$F8,$DF,$43,$F8
		.BYTE	$F8,$CF,$43,$00
		.BYTE	$00
_sprA05_17:
		.BYTE	$02
		.BYTE	$F8,$CF,$C3,$00
		.BYTE	$F8,$DF,$C3,$F8
		.BYTE	$00
_sprA05_18:
		.BYTE	$02
		.BYTE	$F8,$DF,$83,$00
		.BYTE	$F8,$CF,$83,$F8
		.BYTE	$00
_sprA05_19:
		.BYTE	$02
		.BYTE	$F8,$E1,$00,$F8
		.BYTE	$F8,$F1,$00,$00
		.BYTE	$00
_sprA05_1A:
		.BYTE	$02
		.BYTE	$F8,$F1,$40,$F8
		.BYTE	$F8,$E1,$40,$00
		.BYTE	$00
_sprA05_1B:
		.BYTE	$02
		.BYTE	$F8,$E1,$C0,$00
		.BYTE	$F8,$F1,$C0,$F8
		.BYTE	$00
_sprA05_1C:
		.BYTE	$02
		.BYTE	$F8,$F1,$80,$00
		.BYTE	$F8,$E1,$80,$F8
		.BYTE	$00
_sprA05_1D:
		.BYTE	$02
		.BYTE	$F8,$E7,$03,$F8
		.BYTE	$F8,$F7,$03,$00
		.BYTE	$00
_sprA05_1E:
		.BYTE	$02
		.BYTE	$F8,$F7,$43,$F8
		.BYTE	$F8,$E7,$43,$00
		.BYTE	$00
_sprA05_1F:
		.BYTE	$02
		.BYTE	$F8,$E7,$C3,$00
		.BYTE	$F8,$F7,$C3,$F8
		.BYTE	$00
_sprA05_20:
		.BYTE	$02
		.BYTE	$F8,$F7,$83,$00
		.BYTE	$F8,$E7,$83,$F8
		.BYTE	$00
_sprA05_21:
		.BYTE	$02
		.BYTE	$F8,$CB,$03,$F8
		.BYTE	$F8,$DB,$03,$00
		.BYTE	$00
_sprA05_22:
		.BYTE	$02
		.BYTE	$F8,$DB,$43,$F8
		.BYTE	$F8,$CB,$43,$00
		.BYTE	$00
_sprA05_23:
		.BYTE	$02
		.BYTE	$F8,$CB,$C3,$00
		.BYTE	$F8,$DB,$C3,$F8
		.BYTE	$00
_sprA05_24:
		.BYTE	$02
		.BYTE	$F8,$DB,$83,$00
		.BYTE	$F8,$CB,$83,$F8
		.BYTE	$00
_sprA05_25:
		.BYTE	$02
		.BYTE	$F8,$5B,$03,$F8
		.BYTE	$F8,$5B,$43,$00
		.BYTE	$02
		.BYTE	$F9,$4B,$00,$F9
		.BYTE	$F9,$4B,$40,$01
		.BYTE	$00
_sprA05_26:
		.BYTE	$02
		.BYTE	$F8,$5B,$03,$F8
		.BYTE	$F8,$5B,$43,$00
		.BYTE	$02
		.BYTE	$FA,$4B,$00,$F9
		.BYTE	$FA,$4B,$40,$01
		.BYTE	$00
_sprA05_27:
		.BYTE	$02
		.BYTE	$F8,$5B,$03,$F8
		.BYTE	$F8,$5B,$43,$00
		.BYTE	$02
		.BYTE	$FC,$4B,$00,$F9
		.BYTE	$FC,$4B,$40,$01
		.BYTE	$00
_sprA05_28:
		.BYTE	$02
		.BYTE	$F8,$5B,$03,$F8
		.BYTE	$F8,$5B,$43,$00
		.BYTE	$02
		.BYTE	$FE,$4B,$00,$F9
		.BYTE	$FE,$4B,$40,$01
		.BYTE	$00
_sprA05_29:
		.BYTE	$02
		.BYTE	$F8,$5B,$03,$F8
		.BYTE	$F8,$5B,$43,$00
		.BYTE	$02
		.BYTE	$01,$4B,$00,$F9
		.BYTE	$01,$4B,$40,$01
		.BYTE	$00
_sprA05_2A:
		.BYTE	$02
		.BYTE	$F8,$5B,$03,$F8
		.BYTE	$F8,$5B,$43,$00
		.BYTE	$02
		.BYTE	$05,$4B,$00,$F9
		.BYTE	$05,$4B,$40,$01
		.BYTE	$00
_sprA05_2B:
		.BYTE	$02
		.BYTE	$F8,$5B,$03,$F8
		.BYTE	$F8,$5B,$43,$00
		.BYTE	$02
		.BYTE	$0B,$4B,$00,$F9
		.BYTE	$0B,$4B,$40,$01
		.BYTE	$00
_sprA05_2C:
		.BYTE	$02
		.BYTE	$F8,$5B,$03,$F8
		.BYTE	$F8,$5B,$43,$00
		.BYTE	$02
		.BYTE	$11,$4B,$00,$F9
		.BYTE	$11,$4B,$40,$01
		.BYTE	$00
_sprA05_2D:
		.BYTE	$08
		.BYTE	$EA,$BA,$03,$F8
		.BYTE	$EA,$BA,$43,$00
		.BYTE	$F6,$BC,$00,$F8
		.BYTE	$F6,$BC,$40,$00
		.BYTE	$FA,$A4,$03,$F8
		.BYTE	$FA,$A4,$43,$00
		.BYTE	$02,$3E,$03,$00
		.BYTE	$02,$3E,$43,$F8
		.BYTE	$00
_sprA05_2E:
		.BYTE	$08
		.BYTE	$EB,$BA,$03,$F8
		.BYTE	$EB,$BA,$43,$00
		.BYTE	$F9,$BC,$00,$F8
		.BYTE	$F9,$BC,$40,$00
		.BYTE	$FB,$A4,$03,$F8
		.BYTE	$FB,$A4,$43,$00
		.BYTE	$03,$3E,$03,$00
		.BYTE	$03,$3E,$43,$F8
		.BYTE	$00
_sprA05_2F:
		.BYTE	$08
		.BYTE	$EA,$BA,$03,$FA
		.BYTE	$EA,$BA,$43,$02
		.BYTE	$F6,$BC,$00,$FA
		.BYTE	$F6,$BC,$40,$02
		.BYTE	$FA,$A4,$03,$FA
		.BYTE	$FA,$A4,$43,$02
		.BYTE	$02,$3E,$03,$02
		.BYTE	$02,$3E,$43,$FA
		.BYTE	$00
_sprA05_30:
		.BYTE	$03
		.BYTE	$00,$C6,$03,$F8
		.BYTE	$F0,$88,$03,$F3
		.BYTE	$F0,$98,$03,$FB
		.BYTE	$00
_sprA05_31:
		.BYTE	$02
		.BYTE	$F8,$AE,$03,$F0
		.BYTE	$F8,$BE,$03,$F8
		.BYTE	$00
_sprA05_32:
		.BYTE	$03
		.BYTE	$00,$C6,$43,$00
		.BYTE	$F0,$88,$43,$05
		.BYTE	$F0,$98,$43,$FD
		.BYTE	$00
_sprA05_33:
		.BYTE	$02
		.BYTE	$F8,$AE,$43,$08
		.BYTE	$F8,$BE,$43,$00
		.BYTE	$00
_sprA05_34:
		.BYTE	$04
		.BYTE	$02,$AA,$03,$F8
		.BYTE	$02,$AA,$43,$00
		.BYTE	$F2,$A8,$03,$F8
		.BYTE	$F2,$B8,$03,$00
		.BYTE	$01
		.BYTE	$F0,$E1,$42,$F0
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_35:
		.BYTE	$04
		.BYTE	$02,$86,$43,$00
		.BYTE	$02,$96,$43,$F8
		.BYTE	$F2,$84,$43,$00
		.BYTE	$F2,$94,$43,$F8
		.BYTE	$01
		.BYTE	$F1,$E1,$42,$F0
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_36:
		.BYTE	$04
		.BYTE	$02,$A4,$03,$F8
		.BYTE	$02,$A4,$43,$00
		.BYTE	$F2,$A0,$03,$F8
		.BYTE	$F2,$B0,$03,$00
		.BYTE	$01
		.BYTE	$F1,$E1,$02,$08
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_37:
		.BYTE	$04
		.BYTE	$02,$86,$03,$F8
		.BYTE	$02,$96,$03,$00
		.BYTE	$F2,$84,$03,$F8
		.BYTE	$F2,$94,$03,$00
		.BYTE	$01
		.BYTE	$F1,$E1,$02,$08
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_38:
		.BYTE	$04
		.BYTE	$02,$AA,$03,$F8
		.BYTE	$02,$AA,$43,$00
		.BYTE	$F2,$A6,$03,$F8
		.BYTE	$F2,$B6,$03,$00
		.BYTE	$01
		.BYTE	$EC,$E1,$42,$F1
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_39:
		.BYTE	$04
		.BYTE	$02,$86,$43,$00
		.BYTE	$02,$96,$43,$F8
		.BYTE	$F2,$88,$43,$00
		.BYTE	$F2,$98,$43,$F8
		.BYTE	$01
		.BYTE	$EA,$E1,$42,$F1
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_3A:
		.BYTE	$04
		.BYTE	$02,$A4,$03,$F8
		.BYTE	$02,$A4,$43,$00
		.BYTE	$F2,$A2,$03,$F8
		.BYTE	$F2,$B2,$03,$00
		.BYTE	$01
		.BYTE	$E9,$E1,$02,$03
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_3B:
		.BYTE	$04
		.BYTE	$02,$86,$03,$F8
		.BYTE	$02,$96,$03,$00
		.BYTE	$F2,$88,$03,$F8
		.BYTE	$F2,$98,$03,$00
		.BYTE	$01
		.BYTE	$EA,$E1,$02,$07
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_3C:
		.BYTE	$04
		.BYTE	$02,$A4,$03,$F8
		.BYTE	$02,$A4,$43,$00
		.BYTE	$F2,$A6,$03,$F8
		.BYTE	$F2,$B6,$03,$00
		.BYTE	$01
		.BYTE	$EC,$E1,$42,$F1
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_3D:
		.BYTE	$04
		.BYTE	$02,$8A,$43,$00
		.BYTE	$02,$9A,$43,$F8
		.BYTE	$F2,$88,$43,$00
		.BYTE	$F2,$98,$43,$F8
		.BYTE	$01
		.BYTE	$EA,$E1,$42,$F1
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_3E:
		.BYTE	$04
		.BYTE	$02,$B4,$03,$F8
		.BYTE	$02,$B4,$43,$00
		.BYTE	$F2,$A2,$03,$F8
		.BYTE	$F2,$B2,$03,$00
		.BYTE	$01
		.BYTE	$E9,$E1,$02,$03
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_3F:
		.BYTE	$04
		.BYTE	$02,$8A,$03,$F8
		.BYTE	$02,$9A,$03,$00
		.BYTE	$F2,$88,$03,$F8
		.BYTE	$F2,$98,$03,$00
		.BYTE	$01
		.BYTE	$EA,$E1,$02,$07
		.BYTE	$02
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
		.BYTE	$00
_sprA05_40:
		.BYTE	$06
		.BYTE	$02,$A4,$03,$FA
		.BYTE	$02,$A4,$43,$02
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$A6,$03,$FA
		.BYTE	$F2,$B6,$03,$02
		.BYTE	$01
		.BYTE	$EC,$E1,$42,$F3
		.BYTE	$00
_sprA05_41:
		.BYTE	$06
		.BYTE	$02,$8A,$43,$02
		.BYTE	$02,$9A,$43,$FA
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$88,$43,$02
		.BYTE	$F2,$98,$43,$FA
		.BYTE	$01
		.BYTE	$EA,$E1,$42,$F3
		.BYTE	$00
_sprA05_42:
		.BYTE	$06
		.BYTE	$02,$B4,$03,$FA
		.BYTE	$02,$B4,$43,$02
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$A2,$03,$FA
		.BYTE	$F2,$B2,$03,$02
		.BYTE	$01
		.BYTE	$E9,$E1,$02,$05
		.BYTE	$00
_sprA05_43:
		.BYTE	$06
		.BYTE	$02,$8A,$03,$FA
		.BYTE	$02,$9A,$03,$02
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$88,$03,$FA
		.BYTE	$F2,$98,$03,$02
		.BYTE	$01
		.BYTE	$EA,$E1,$02,$09
		.BYTE	$00
_sprA05_44:
		.BYTE	$04
		.BYTE	$02,$AA,$03,$F8
		.BYTE	$02,$AA,$43,$00
		.BYTE	$F2,$A8,$03,$F8
		.BYTE	$F2,$B8,$03,$00
		.BYTE	$02
		.BYTE	$F0,$C3,$42,$F0
		.BYTE	$F0,$D3,$42,$E8
		.BYTE	$00
_sprA05_45:
		.BYTE	$04
		.BYTE	$02,$86,$43,$00
		.BYTE	$02,$96,$43,$F8
		.BYTE	$F2,$84,$43,$00
		.BYTE	$F2,$94,$43,$F8
		.BYTE	$02
		.BYTE	$F1,$C3,$42,$F0
		.BYTE	$F1,$D3,$42,$E8
		.BYTE	$00
_sprA05_46:
		.BYTE	$04
		.BYTE	$02,$A4,$03,$F8
		.BYTE	$02,$A4,$43,$00
		.BYTE	$F2,$A0,$03,$F8
		.BYTE	$F2,$B0,$03,$00
		.BYTE	$02
		.BYTE	$F1,$C3,$02,$08
		.BYTE	$F1,$D3,$02,$10
		.BYTE	$00
_sprA05_47:
		.BYTE	$04
		.BYTE	$02,$86,$03,$F8
		.BYTE	$02,$96,$03,$00
		.BYTE	$F2,$84,$03,$F8
		.BYTE	$F2,$94,$03,$00
		.BYTE	$02
		.BYTE	$F1,$C3,$02,$08
		.BYTE	$F1,$D3,$02,$10
		.BYTE	$00
_sprA05_48:
		.BYTE	$04
		.BYTE	$02,$AA,$03,$F8
		.BYTE	$02,$AA,$43,$00
		.BYTE	$F2,$A6,$03,$F8
		.BYTE	$F2,$B6,$03,$00
		.BYTE	$02
		.BYTE	$EC,$C3,$42,$F1
		.BYTE	$EC,$D3,$42,$E9
		.BYTE	$00
_sprA05_49:
		.BYTE	$04
		.BYTE	$02,$86,$43,$00
		.BYTE	$02,$96,$43,$F8
		.BYTE	$F2,$88,$43,$00
		.BYTE	$F2,$98,$43,$F8
		.BYTE	$02
		.BYTE	$EA,$C3,$42,$F1
		.BYTE	$EA,$D3,$42,$E9
		.BYTE	$00
_sprA05_4A:
		.BYTE	$04
		.BYTE	$02,$A4,$03,$F8
		.BYTE	$02,$A4,$43,$00
		.BYTE	$F2,$A2,$03,$F8
		.BYTE	$F2,$B2,$03,$00
		.BYTE	$02
		.BYTE	$E9,$C3,$02,$03
		.BYTE	$E9,$D3,$02,$0B
		.BYTE	$00
_sprA05_4B:
		.BYTE	$04
		.BYTE	$02,$86,$03,$F8
		.BYTE	$02,$96,$03,$00
		.BYTE	$F2,$88,$03,$F8
		.BYTE	$F2,$98,$03,$00
		.BYTE	$02
		.BYTE	$EA,$C3,$02,$07
		.BYTE	$EA,$D3,$02,$0F
		.BYTE	$00
_sprA05_4C:
		.BYTE	$04
		.BYTE	$02,$A4,$03,$F8
		.BYTE	$02,$A4,$43,$00
		.BYTE	$F2,$A6,$03,$F8
		.BYTE	$F2,$B6,$03,$00
		.BYTE	$02
		.BYTE	$EC,$C3,$42,$F1
		.BYTE	$EC,$D3,$42,$E9
		.BYTE	$00
_sprA05_4D:
		.BYTE	$04
		.BYTE	$02,$8A,$43,$00
		.BYTE	$02,$9A,$43,$F8
		.BYTE	$F2,$88,$43,$00
		.BYTE	$F2,$98,$43,$F8
		.BYTE	$02
		.BYTE	$EA,$C3,$42,$F1
		.BYTE	$EA,$D3,$42,$E9
		.BYTE	$00
_sprA05_4E:
		.BYTE	$04
		.BYTE	$02,$B4,$03,$F8
		.BYTE	$02,$B4,$43,$00
		.BYTE	$F2,$A2,$03,$F8
		.BYTE	$F2,$B2,$03,$00
		.BYTE	$02
		.BYTE	$E9,$C3,$02,$03
		.BYTE	$E9,$D3,$02,$0B
		.BYTE	$00
_sprA05_4F:
		.BYTE	$04
		.BYTE	$02,$8A,$03,$F8
		.BYTE	$02,$9A,$03,$00
		.BYTE	$F2,$88,$03,$F8
		.BYTE	$F2,$98,$03,$00
		.BYTE	$02
		.BYTE	$EA,$C3,$02,$07
		.BYTE	$EA,$D3,$02,$0F
		.BYTE	$00
_sprA05_50:
		.BYTE	$06
		.BYTE	$02,$A4,$03,$FA
		.BYTE	$02,$A4,$43,$02
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$A6,$03,$FA
		.BYTE	$F2,$B6,$03,$02
		.BYTE	$02
		.BYTE	$EC,$C3,$42,$F3
		.BYTE	$EC,$D3,$42,$EB
		.BYTE	$00
_sprA05_51:
		.BYTE	$06
		.BYTE	$02,$8A,$43,$02
		.BYTE	$02,$9A,$43,$FA
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$88,$43,$02
		.BYTE	$F2,$98,$43,$FA
		.BYTE	$02
		.BYTE	$EA,$C3,$42,$F3
		.BYTE	$EA,$D3,$42,$EB
		.BYTE	$00
_sprA05_52:
		.BYTE	$06
		.BYTE	$02,$B4,$03,$FA
		.BYTE	$02,$B4,$43,$02
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$A2,$03,$FA
		.BYTE	$F2,$B2,$03,$02
		.BYTE	$02
		.BYTE	$E9,$C3,$02,$05
		.BYTE	$E9,$D3,$02,$0D
		.BYTE	$00
_sprA05_53:
		.BYTE	$06
		.BYTE	$02,$8A,$03,$FA
		.BYTE	$02,$9A,$03,$02
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$88,$03,$FA
		.BYTE	$F2,$98,$03,$02
		.BYTE	$02
		.BYTE	$EA,$C3,$02,$09
		.BYTE	$EA,$D3,$02,$11
		.BYTE	$00
_sprA05_56:
		.BYTE	$04
		.BYTE	$00,$82,$02,$F8
		.BYTE	$00,$82,$42,$00
		.BYTE	$F0,$80,$02,$F8
		.BYTE	$F0,$80,$42,$00
		.BYTE	$00
_sprA05_57:
		.BYTE	$04
		.BYTE	$F8,$90,$02,$F0
		.BYTE	$F8,$90,$42,$08
		.BYTE	$F8,$92,$02,$F8
		.BYTE	$F8,$92,$42,$00
		.BYTE	$00
_sprA05_58:
		.BYTE	$02
		.BYTE	$F1,$9C,$03,$F8
		.BYTE	$F1,$9C,$43,$00
		.BYTE	$04
		.BYTE	$00,$82,$02,$F8
		.BYTE	$00,$82,$42,$00
		.BYTE	$F0,$80,$02,$F8
		.BYTE	$F0,$80,$42,$00
		.BYTE	$00
_sprA05_59:
		.BYTE	$02
		.BYTE	$F2,$8E,$43,$01
		.BYTE	$F2,$9E,$43,$F9
		.BYTE	$04
		.BYTE	$F8,$90,$02,$F0
		.BYTE	$F8,$90,$42,$08
		.BYTE	$F8,$92,$02,$F8
		.BYTE	$F8,$92,$42,$00
		.BYTE	$00
_sprA05_5A:
		.BYTE	$02
		.BYTE	$F3,$8C,$03,$F8
		.BYTE	$F3,$8C,$43,$00
		.BYTE	$04
		.BYTE	$00,$82,$02,$F8
		.BYTE	$00,$82,$42,$00
		.BYTE	$F0,$80,$02,$F8
		.BYTE	$F0,$80,$42,$00
		.BYTE	$00
_sprA05_5B:
		.BYTE	$02
		.BYTE	$F2,$8E,$03,$F7
		.BYTE	$F2,$9E,$03,$FF
		.BYTE	$04
		.BYTE	$F8,$90,$02,$F0
		.BYTE	$F8,$90,$42,$08
		.BYTE	$F8,$92,$02,$F8
		.BYTE	$F8,$92,$42,$00
		.BYTE	$00
_sprA05_5C:
		.BYTE	$02
		.BYTE	$08,$3E,$03,$00
		.BYTE	$08,$3E,$43,$F8
		.BYTE	$04
		.BYTE	$00,$A4,$03,$F8
		.BYTE	$00,$A4,$43,$00
		.BYTE	$F0,$A6,$03,$F8
		.BYTE	$F0,$B6,$03,$00
		.BYTE	$00
_sprA05_5D:
		.BYTE	$02
		.BYTE	$08,$3E,$03,$00
		.BYTE	$08,$3E,$43,$F8
		.BYTE	$04
		.BYTE	$00,$8A,$43,$00
		.BYTE	$00,$9A,$43,$F8
		.BYTE	$F0,$88,$43,$00
		.BYTE	$F0,$98,$43,$F8
		.BYTE	$00
_sprA05_5E:
		.BYTE	$02
		.BYTE	$08,$3E,$03,$00
		.BYTE	$08,$3E,$43,$F8
		.BYTE	$04
		.BYTE	$00,$B4,$03,$F8
		.BYTE	$00,$B4,$43,$00
		.BYTE	$F0,$A2,$03,$F8
		.BYTE	$F0,$B2,$03,$00
		.BYTE	$00
_sprA05_5F:
		.BYTE	$02
		.BYTE	$08,$3E,$03,$00
		.BYTE	$08,$3E,$43,$F8
		.BYTE	$04
		.BYTE	$00,$8A,$03,$F8
		.BYTE	$00,$9A,$03,$00
		.BYTE	$F0,$88,$03,$F8
		.BYTE	$F0,$98,$03,$00
		.BYTE	$00
_sprA05_60:
		.BYTE	$02
		.BYTE	$08,$3E,$03,$02
		.BYTE	$08,$3E,$43,$FA
		.BYTE	$04
		.BYTE	$00,$A4,$03,$FA
		.BYTE	$00,$A4,$43,$02
		.BYTE	$F0,$A6,$03,$FA
		.BYTE	$F0,$B6,$03,$02
		.BYTE	$00
_sprA05_61:
		.BYTE	$02
		.BYTE	$08,$3E,$03,$02
		.BYTE	$08,$3E,$43,$FA
		.BYTE	$04
		.BYTE	$00,$8A,$43,$02
		.BYTE	$00,$9A,$43,$FA
		.BYTE	$F0,$88,$43,$02
		.BYTE	$F0,$98,$43,$FA
		.BYTE	$00
_sprA05_62:
		.BYTE	$02
		.BYTE	$08,$3E,$03,$02
		.BYTE	$08,$3E,$43,$FA
		.BYTE	$04
		.BYTE	$00,$B4,$03,$FA
		.BYTE	$00,$B4,$43,$02
		.BYTE	$F0,$A2,$03,$FA
		.BYTE	$F0,$B2,$03,$02
		.BYTE	$00
_sprA05_63:
		.BYTE	$02
		.BYTE	$08,$3E,$03,$02
		.BYTE	$08,$3E,$43,$FA
		.BYTE	$04
		.BYTE	$00,$8A,$03,$FA
		.BYTE	$00,$9A,$03,$02
		.BYTE	$F0,$88,$03,$FA
		.BYTE	$F0,$98,$03,$02
		.BYTE	$00
_sprA05_64:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$E8,$03,$F8
		.BYTE	$F6,$E8,$43,$00
		.BYTE	$00
_sprA05_65:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$F8,$03,$FA
		.BYTE	$F6,$F8,$43,$02
		.BYTE	$00
_sprA05_66:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$F8,$03,$F8
		.BYTE	$F6,$F8,$43,$00
		.BYTE	$00
_sprA05_67:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$EA,$03,$F8
		.BYTE	$F6,$EA,$43,$00
		.BYTE	$00
_sprA05_68:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$FA,$03,$FA
		.BYTE	$F6,$FA,$43,$02
		.BYTE	$00
_sprA05_69:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$FA,$03,$F8
		.BYTE	$F6,$FA,$43,$00
		.BYTE	$00
_sprA05_6A:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$EC,$03,$F8
		.BYTE	$F6,$EC,$43,$00
		.BYTE	$00
_sprA05_6B:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$FC,$03,$FA
		.BYTE	$F6,$FC,$43,$02
		.BYTE	$00
_sprA05_6C:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$FC,$03,$F8
		.BYTE	$F6,$FC,$43,$00
		.BYTE	$00
_sprA05_6D:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$CA,$03,$F8
		.BYTE	$F6,$CA,$43,$00
		.BYTE	$00
_sprA05_6E:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$DA,$03,$FA
		.BYTE	$F6,$DA,$43,$02
		.BYTE	$00
_sprA05_6F:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$DA,$03,$F8
		.BYTE	$F6,$DA,$43,$00
		.BYTE	$00
_sprA05_70:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$CC,$03,$F8
		.BYTE	$F6,$CC,$43,$00
		.BYTE	$00
_sprA05_71:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$DC,$03,$FA
		.BYTE	$F6,$DC,$43,$02
		.BYTE	$00
_sprA05_72:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$DC,$03,$F8
		.BYTE	$F6,$DC,$43,$00
		.BYTE	$00
_sprA05_73:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$CE,$03,$F8
		.BYTE	$F6,$CE,$43,$00
		.BYTE	$00
_sprA05_74:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$DE,$03,$FA
		.BYTE	$F6,$DE,$43,$02
		.BYTE	$00
_sprA05_75:
		.BYTE	$03
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$DE,$03,$F8
		.BYTE	$F6,$DE,$43,$00
		.BYTE	$00
_sprA05_77:
		.BYTE	$02
		.BYTE	$F4,$DA,$03,$F0
		.BYTE	$F4,$FE,$03,$F8
		.BYTE	$00
_sprA05_79:
		.BYTE	$02
		.BYTE	$F4,$FE,$43,$00
		.BYTE	$F4,$DA,$43,$08
		.BYTE	$00
_sprA05_7A:
		.BYTE	$01
		.BYTE	$F8,$D8,$03,$FC
		.BYTE	$00
_sprA05_7B:
		.BYTE	$01
		.BYTE	$F8,$D8,$C3,$FC
		.BYTE	$00
_sprA05_7C:
		.BYTE	$02
		.BYTE	$F8,$98,$00,$00
		.BYTE	$F8,$88,$00,$F8
		.BYTE	$00
_sprA05_7D:
		.BYTE	$02
		.BYTE	$F8,$88,$80,$F8
		.BYTE	$F8,$98,$80,$00
		.BYTE	$00
_sprA05_7E:
		.BYTE	$02
		.BYTE	$F8,$98,$C0,$F8
		.BYTE	$F8,$88,$C0,$00
		.BYTE	$00
_sprA05_7F:
		.BYTE	$02
		.BYTE	$F8,$88,$40,$00
		.BYTE	$F8,$98,$40,$F8
		.BYTE	$00
_sprA05_80:
		.BYTE	$02
		.BYTE	$F8,$B8,$00,$00
		.BYTE	$F8,$A8,$00,$F8
		.BYTE	$00
_sprA05_81:
		.BYTE	$02
		.BYTE	$F8,$A8,$80,$F8
		.BYTE	$F8,$B8,$80,$00
		.BYTE	$00
_sprA05_82:
		.BYTE	$02
		.BYTE	$F8,$B8,$C0,$F8
		.BYTE	$F8,$A8,$C0,$00
		.BYTE	$00
_sprA05_83:
		.BYTE	$02
		.BYTE	$F8,$A8,$40,$00
		.BYTE	$F8,$B8,$40,$F8
		.BYTE	$00
_sprA05_84:
		.BYTE	$02
		.BYTE	$F8,$9E,$00,$00
		.BYTE	$F8,$8E,$00,$F8
		.BYTE	$00
_sprA05_85:
		.BYTE	$02
		.BYTE	$F8,$8E,$40,$00
		.BYTE	$F8,$9E,$40,$F8
		.BYTE	$00
_sprA05_86:
		.BYTE	$02
		.BYTE	$F8,$9E,$C0,$F8
		.BYTE	$F8,$8E,$C0,$00
		.BYTE	$00
_sprA05_87:
		.BYTE	$02
		.BYTE	$F8,$9E,$80,$00
		.BYTE	$F8,$8E,$80,$F8
		.BYTE	$00
_sprA05_88:
		.BYTE	$02
		.BYTE	$F8,$9A,$00,$00
		.BYTE	$F8,$8A,$00,$F8
		.BYTE	$00
_sprA05_89:
		.BYTE	$02
		.BYTE	$F8,$8A,$40,$00
		.BYTE	$F8,$9A,$40,$F8
		.BYTE	$00
_sprA05_8A:
		.BYTE	$02
		.BYTE	$F8,$9A,$C0,$F8
		.BYTE	$F8,$8A,$C0,$00
		.BYTE	$00
_sprA05_8B:
		.BYTE	$02
		.BYTE	$F8,$8A,$80,$F8
		.BYTE	$F8,$9A,$80,$00
		.BYTE	$00
_sprA05_8F:
		.BYTE	$02
		.BYTE	$F8,$BA,$00,$00
		.BYTE	$F8,$AA,$00,$F8
		.BYTE	$00
_sprA05_93:
		.BYTE	$02
		.BYTE	$F8,$9C,$00,$00
		.BYTE	$F8,$8C,$00,$F8
		.BYTE	$00
_sprA05_97:
		.BYTE	$02
		.BYTE	$F8,$BC,$00,$00
		.BYTE	$F8,$AC,$00,$F8
		.BYTE	$00
_sprA06_04:
		.BYTE	$04
		.BYTE	$EE,$84,$03,$F0
		.BYTE	$EE,$94,$03,$F8
		.BYTE	$FE,$8C,$03,$F0
		.BYTE	$FE,$8E,$03,$F8
		.BYTE	$00
_sprA06_05:
		.BYTE	$04
		.BYTE	$F6,$84,$03,$F0
		.BYTE	$F6,$94,$03,$F8
		.BYTE	$FE,$6E,$03,$F0
		.BYTE	$FE,$7E,$03,$F8
		.BYTE	$00
_sprA06_06:
		.BYTE	$04
		.BYTE	$EE,$84,$43,$08
		.BYTE	$EE,$94,$43,$00
		.BYTE	$FE,$8C,$43,$08
		.BYTE	$FE,$8E,$43,$00
		.BYTE	$00
_sprA06_07:
		.BYTE	$04
		.BYTE	$F6,$84,$43,$08
		.BYTE	$F6,$94,$43,$00
		.BYTE	$FE,$6E,$43,$08
		.BYTE	$FE,$7E,$43,$00
		.BYTE	$00
_sprA06_08:
		.BYTE	$04
		.BYTE	$EE,$8C,$03,$F3
		.BYTE	$EE,$8C,$43,$FB
		.BYTE	$FE,$A0,$03,$F3
		.BYTE	$FE,$B0,$03,$FB
		.BYTE	$00
_sprA06_09:
		.BYTE	$02
		.BYTE	$FD,$80,$03,$F2
		.BYTE	$FD,$90,$03,$FA
		.BYTE	$00
_sprA06_0A:
		.BYTE	$04
		.BYTE	$EE,$8C,$03,$FE
		.BYTE	$EE,$8C,$43,$06
		.BYTE	$FE,$A0,$43,$06
		.BYTE	$FE,$B0,$43,$FE
		.BYTE	$00
_sprA06_0B:
		.BYTE	$02
		.BYTE	$FD,$80,$43,$07
		.BYTE	$FD,$90,$43,$FF
		.BYTE	$00
_sprA06_0C:
		.BYTE	$01
		.BYTE	$F8,$B8,$83,$FC
		.BYTE	$00
_sprA06_0D:
		.BYTE	$02
		.BYTE	$00,$8E,$83,$FC
		.BYTE	$F8,$B8,$83,$FC
		.BYTE	$00
_sprA06_0E:
		.BYTE	$02
		.BYTE	$08,$8E,$83,$FC
		.BYTE	$F8,$B8,$83,$FC
		.BYTE	$00
_sprA06_0F:
		.BYTE	$03
		.BYTE	$08,$8E,$83,$FC
		.BYTE	$10,$8E,$03,$FC
		.BYTE	$F8,$B8,$83,$FC
		.BYTE	$00
_sprA06_10:
		.BYTE	$03
		.BYTE	$08,$8E,$83,$FC
		.BYTE	$18,$8E,$03,$FC
		.BYTE	$F8,$B8,$83,$FC
		.BYTE	$00
_sprA06_11:
		.BYTE	$02
		.BYTE	$F5,$84,$43,$00
		.BYTE	$F5,$94,$43,$F8
		.BYTE	$00
_sprA06_12:
		.BYTE	$03
		.BYTE	$F5,$84,$43,$00
		.BYTE	$F5,$94,$43,$F8
		.BYTE	$F5,$A4,$43,$F0
		.BYTE	$00
_sprA06_13:
		.BYTE	$04
		.BYTE	$F5,$84,$43,$00
		.BYTE	$F5,$94,$43,$F8
		.BYTE	$F5,$A4,$43,$E8
		.BYTE	$F5,$A4,$43,$F0
		.BYTE	$00
_sprA06_14:
		.BYTE	$05
		.BYTE	$F5,$84,$43,$00
		.BYTE	$F5,$94,$43,$F8
		.BYTE	$F5,$A4,$43,$E0
		.BYTE	$F5,$A4,$43,$E8
		.BYTE	$F5,$A4,$43,$F0
		.BYTE	$00
_sprA06_15:
		.BYTE	$01
		.BYTE	$F8,$B8,$03,$FC
		.BYTE	$00
_sprA06_16:
		.BYTE	$02
		.BYTE	$F0,$8E,$03,$FC
		.BYTE	$F8,$B8,$03,$FC
		.BYTE	$00
_sprA06_17:
		.BYTE	$02
		.BYTE	$E8,$8E,$03,$FC
		.BYTE	$F8,$B8,$03,$FC
		.BYTE	$00
_sprA06_18:
		.BYTE	$03
		.BYTE	$E1,$8E,$03,$FC
		.BYTE	$E8,$8E,$03,$FC
		.BYTE	$F8,$B8,$03,$FC
		.BYTE	$00
_sprA06_19:
		.BYTE	$03
		.BYTE	$D8,$8E,$03,$FC
		.BYTE	$E8,$8E,$03,$FC
		.BYTE	$F8,$B8,$03,$FC
		.BYTE	$00
_sprA06_1A:
		.BYTE	$02
		.BYTE	$F5,$84,$03,$F8
		.BYTE	$F5,$94,$03,$00
		.BYTE	$00
_sprA06_1B:
		.BYTE	$03
		.BYTE	$F5,$84,$03,$F8
		.BYTE	$F5,$94,$03,$00
		.BYTE	$F5,$A4,$03,$08
		.BYTE	$00
_sprA06_1C:
		.BYTE	$04
		.BYTE	$F5,$84,$03,$F8
		.BYTE	$F5,$94,$03,$00
		.BYTE	$F5,$A4,$03,$08
		.BYTE	$F5,$A4,$03,$10
		.BYTE	$00
_sprA06_1D:
		.BYTE	$05
		.BYTE	$F5,$84,$03,$F8
		.BYTE	$F5,$94,$03,$00
		.BYTE	$F5,$A4,$03,$08
		.BYTE	$F5,$A4,$03,$10
		.BYTE	$F5,$A4,$03,$18
		.BYTE	$00
_sprA06_1E:
		.BYTE	$04
		.BYTE	$00,$C2,$40,$00
		.BYTE	$00,$D2,$40,$F8
		.BYTE	$F1,$E8,$00,$F8
		.BYTE	$F1,$F8,$00,$00
		.BYTE	$00
_sprA06_1F:
		.BYTE	$06
		.BYTE	$00,$C6,$40,$00
		.BYTE	$00,$D6,$40,$F8
		.BYTE	$F1,$E4,$40,$00
		.BYTE	$F1,$F4,$40,$F8
		.BYTE	$F2,$C8,$40,$09
		.BYTE	$F2,$D8,$40,$01
		.BYTE	$00
_sprA06_20:
		.BYTE	$05
		.BYTE	$00,$C2,$40,$00
		.BYTE	$00,$D2,$40,$F8
		.BYTE	$E8,$FA,$80,$FC
		.BYTE	$F1,$C4,$00,$F8
		.BYTE	$F1,$D4,$00,$00
		.BYTE	$00
_sprA06_21:
		.BYTE	$06
		.BYTE	$00,$C6,$00,$F8
		.BYTE	$00,$D6,$00,$00
		.BYTE	$F1,$E4,$00,$F8
		.BYTE	$F1,$F4,$00,$00
		.BYTE	$F2,$C8,$00,$EF
		.BYTE	$F2,$D8,$00,$F7
		.BYTE	$00
_sprA06_22:
		.BYTE	$05
		.BYTE	$00,$E2,$00,$F8
		.BYTE	$00,$F2,$00,$00
		.BYTE	$E8,$FA,$80,$FE
		.BYTE	$F0,$E8,$00,$F8
		.BYTE	$F0,$F8,$00,$00
		.BYTE	$00
_sprA06_23:
		.BYTE	$05
		.BYTE	$00,$E6,$40,$00
		.BYTE	$00,$F6,$40,$F8
		.BYTE	$EC,$FA,$C0,$01
		.BYTE	$F0,$E4,$40,$00
		.BYTE	$F0,$F4,$40,$F8
		.BYTE	$00
_sprA06_24:
		.BYTE	$05
		.BYTE	$00,$FA,$00,$FC
		.BYTE	$00,$E2,$00,$F8
		.BYTE	$00,$F2,$00,$00
		.BYTE	$F0,$C4,$00,$F8
		.BYTE	$F0,$D4,$00,$00
		.BYTE	$00
_sprA06_25:
		.BYTE	$05
		.BYTE	$00,$E6,$00,$F8
		.BYTE	$00,$F6,$00,$00
		.BYTE	$EC,$FA,$80,$F7
		.BYTE	$F0,$E4,$00,$F8
		.BYTE	$F0,$F4,$00,$00
		.BYTE	$00
_sprA06_26:
		.BYTE	$04
		.BYTE	$00,$C2,$00,$F8
		.BYTE	$00,$D2,$00,$00
		.BYTE	$F1,$E8,$00,$F8
		.BYTE	$F1,$F8,$00,$00
		.BYTE	$00
_sprA06_27:
		.BYTE	$06
		.BYTE	$00,$C2,$00,$F8
		.BYTE	$00,$D2,$00,$00
		.BYTE	$F1,$E4,$40,$00
		.BYTE	$F1,$F4,$40,$F8
		.BYTE	$F2,$C8,$40,$09
		.BYTE	$F2,$D8,$40,$01
		.BYTE	$00
_sprA06_28:
		.BYTE	$05
		.BYTE	$00,$C2,$00,$F8
		.BYTE	$00,$D2,$00,$00
		.BYTE	$E8,$FA,$80,$FC
		.BYTE	$F1,$C4,$00,$F8
		.BYTE	$F1,$D4,$00,$00
		.BYTE	$00
_sprA06_29:
		.BYTE	$06
		.BYTE	$00,$C2,$40,$00
		.BYTE	$00,$D2,$40,$F8
		.BYTE	$F1,$E4,$00,$F8
		.BYTE	$F1,$F4,$00,$00
		.BYTE	$F2,$C8,$00,$EF
		.BYTE	$F2,$D8,$00,$F7
		.BYTE	$00
_sprA06_2A:
		.BYTE	$04
		.BYTE	$00,$E2,$00,$F8
		.BYTE	$00,$F2,$00,$00
		.BYTE	$F0,$C0,$00,$F8
		.BYTE	$F0,$D0,$00,$00
		.BYTE	$00
_sprA06_2B:
		.BYTE	$04
		.BYTE	$00,$E2,$40,$00
		.BYTE	$00,$F2,$40,$F8
		.BYTE	$F0,$E4,$40,$00
		.BYTE	$F0,$F4,$40,$F8
		.BYTE	$00
_sprA06_2C:
		.BYTE	$04
		.BYTE	$00,$E2,$00,$F8
		.BYTE	$00,$F2,$00,$00
		.BYTE	$F0,$E0,$00,$F8
		.BYTE	$F0,$F0,$00,$00
		.BYTE	$00
_sprA06_2D:
		.BYTE	$04
		.BYTE	$00,$E2,$00,$F8
		.BYTE	$00,$F2,$00,$00
		.BYTE	$F0,$E4,$00,$F8
		.BYTE	$F0,$F4,$00,$00
		.BYTE	$00
_sprA06_2E:
		.BYTE	$04
		.BYTE	$00,$E2,$00,$FA
		.BYTE	$00,$F2,$00,$02
		.BYTE	$F0,$C0,$00,$FA
		.BYTE	$F0,$D0,$00,$02
		.BYTE	$00
_sprA06_2F:
		.BYTE	$04
		.BYTE	$00,$E2,$40,$02
		.BYTE	$00,$F2,$40,$FA
		.BYTE	$F0,$E4,$40,$02
		.BYTE	$F0,$F4,$40,$FA
		.BYTE	$00
_sprA06_30:
		.BYTE	$04
		.BYTE	$00,$E2,$00,$FA
		.BYTE	$00,$F2,$00,$02
		.BYTE	$F0,$E0,$00,$FA
		.BYTE	$F0,$F0,$00,$02
		.BYTE	$00
_sprA06_31:
		.BYTE	$04
		.BYTE	$00,$E2,$00,$FA
		.BYTE	$00,$F2,$00,$02
		.BYTE	$F0,$E4,$00,$FA
		.BYTE	$F0,$F4,$00,$02
		.BYTE	$00
_sprA06_32:
		.BYTE	$04
		.BYTE	$07,$EC,$00,$F2
		.BYTE	$07,$FC,$00,$FA
		.BYTE	$F7,$E4,$00,$F2
		.BYTE	$F7,$F4,$00,$FA
		.BYTE	$00
_sprA06_33:
		.BYTE	$02
		.BYTE	$FF,$CC,$00,$F2
		.BYTE	$FF,$DC,$00,$FA
		.BYTE	$00
_sprA06_34:
		.BYTE	$04
		.BYTE	$08,$EC,$40,$07
		.BYTE	$08,$FC,$40,$FF
		.BYTE	$F8,$E4,$40,$07
		.BYTE	$F8,$F4,$40,$FF
		.BYTE	$00
_sprA06_35:
		.BYTE	$02
		.BYTE	$FF,$CC,$40,$07
		.BYTE	$FF,$DC,$40,$FF
		.BYTE	$00
_sprA06_36:
		.BYTE	$05
		.BYTE	$00,$C2,$00,$F8
		.BYTE	$00,$D2,$00,$00
		.BYTE	$EE,$EA,$00,$FC
		.BYTE	$F1,$C0,$00,$F8
		.BYTE	$F1,$F8,$00,$00
		.BYTE	$00
_sprA06_37:
		.BYTE	$05
		.BYTE	$00,$C6,$40,$00
		.BYTE	$00,$D6,$40,$F8
		.BYTE	$F1,$E4,$40,$00
		.BYTE	$F1,$F4,$40,$F8
		.BYTE	$F7,$EA,$00,$FD
		.BYTE	$00
_sprA06_38:
		.BYTE	$05
		.BYTE	$00,$C2,$00,$F8
		.BYTE	$00,$D2,$00,$00
		.BYTE	$F1,$D4,$00,$00
		.BYTE	$F1,$E0,$00,$F8
		.BYTE	$F4,$DA,$80,$FC
		.BYTE	$00
_sprA06_39:
		.BYTE	$05
		.BYTE	$00,$C6,$00,$F8
		.BYTE	$00,$D6,$00,$00
		.BYTE	$F1,$E4,$00,$F8
		.BYTE	$F1,$F4,$00,$00
		.BYTE	$F7,$EA,$40,$FB
		.BYTE	$00
_sprA06_3A:
		.BYTE	$05
		.BYTE	$00,$E2,$00,$F8
		.BYTE	$00,$F2,$00,$00
		.BYTE	$E9,$EA,$40,$FF
		.BYTE	$F0,$C0,$00,$F8
		.BYTE	$F0,$F8,$00,$00
		.BYTE	$00
_sprA06_3B:
		.BYTE	$05
		.BYTE	$00,$E6,$40,$00
		.BYTE	$00,$F6,$40,$F8
		.BYTE	$F0,$E4,$40,$00
		.BYTE	$F0,$F4,$40,$F8
		.BYTE	$F5,$DA,$40,$02
		.BYTE	$00
_sprA06_3C:
		.BYTE	$05
		.BYTE	$00,$E2,$00,$F8
		.BYTE	$00,$F2,$00,$00
		.BYTE	$F0,$D4,$00,$00
		.BYTE	$F0,$E0,$00,$F8
		.BYTE	$F5,$EA,$80,$01
		.BYTE	$00
_sprA06_3D:
		.BYTE	$05
		.BYTE	$00,$E6,$00,$F8
		.BYTE	$00,$F6,$00,$00
		.BYTE	$F0,$E4,$00,$F8
		.BYTE	$F0,$F4,$00,$00
		.BYTE	$F5,$DA,$00,$F6
		.BYTE	$00
_sprA06_3E:
		.BYTE	$05
		.BYTE	$00,$C2,$40,$00
		.BYTE	$00,$D2,$40,$F8
		.BYTE	$EE,$EA,$00,$FC
		.BYTE	$F1,$C0,$00,$F8
		.BYTE	$F1,$F8,$00,$00
		.BYTE	$00
_sprA06_3F:
		.BYTE	$05
		.BYTE	$00,$C2,$00,$F8
		.BYTE	$00,$D2,$00,$00
		.BYTE	$F1,$E4,$40,$00
		.BYTE	$F1,$F4,$40,$F8
		.BYTE	$F7,$EA,$40,$FD
		.BYTE	$00
_sprA06_40:
		.BYTE	$05
		.BYTE	$00,$C2,$40,$00
		.BYTE	$00,$D2,$40,$F8
		.BYTE	$F1,$D4,$00,$00
		.BYTE	$F1,$E0,$00,$F8
		.BYTE	$F4,$DA,$80,$FC
		.BYTE	$00
_sprA06_41:
		.BYTE	$05
		.BYTE	$00,$C2,$40,$00
		.BYTE	$00,$D2,$40,$F8
		.BYTE	$F1,$E4,$00,$F8
		.BYTE	$F1,$F4,$00,$00
		.BYTE	$F7,$EA,$00,$FB
		.BYTE	$00
_sprA06_42:
		.BYTE	$01
		.BYTE	$FD,$CA,$00,$FD
		.BYTE	$00
_sprA06_43:
		.BYTE	$01
		.BYTE	$FD,$CA,$40,$FD
		.BYTE	$00
_sprA06_44:
		.BYTE	$01
		.BYTE	$F5,$CA,$C0,$FD
		.BYTE	$00
_sprA06_45:
		.BYTE	$01
		.BYTE	$F5,$CA,$80,$FD
		.BYTE	$00
_sprA06_46:
		.BYTE	$02
		.BYTE	$F8,$CE,$03,$02
		.BYTE	$F8,$BE,$03,$FA
		.BYTE	$00
_sprA06_47:
		.BYTE	$02
		.BYTE	$FF,$BE,$03,$F1
		.BYTE	$FF,$6E,$03,$F9
		.BYTE	$00
_sprA06_48:
		.BYTE	$01
		.BYTE	$FF,$FE,$03,$F9
		.BYTE	$00
_sprA06_49:
		.BYTE	$02
		.BYTE	$FF,$BE,$43,$08
		.BYTE	$FF,$6E,$43,$00
		.BYTE	$00
_sprA06_4A:
		.BYTE	$01
		.BYTE	$FF,$FE,$43,$00
		.BYTE	$00
_sprA06_4B:
		.BYTE	$02
		.BYTE	$F4,$E0,$03,$F8
		.BYTE	$F4,$E0,$43,$00
		.BYTE	$00
_sprA06_4C:
		.BYTE	$02
		.BYTE	$F4,$E2,$03,$F8
		.BYTE	$F4,$E2,$43,$00
		.BYTE	$00
_sprA06_4D:
		.BYTE	$02
		.BYTE	$F4,$E4,$03,$F8
		.BYTE	$F4,$E4,$43,$00
		.BYTE	$00
_sprA06_4E:
		.BYTE	$02
		.BYTE	$F4,$E0,$03,$FA
		.BYTE	$F4,$E0,$43,$02
		.BYTE	$00
_sprA06_50:
		.BYTE	$01
		.BYTE	$05,$CE,$03,$FA
		.BYTE	$00
_sprA06_51:
		.BYTE	$02
		.BYTE	$02,$E4,$83,$F8
		.BYTE	$02,$E4,$C3,$00
		.BYTE	$00
_sprA06_52:
		.BYTE	$01
		.BYTE	$05,$CE,$43,$FF
		.BYTE	$00
_sprA06_53:
		.BYTE	$02
		.BYTE	$F4,$F0,$03,$F8
		.BYTE	$F4,$F0,$43,$00
		.BYTE	$00
_sprA06_54:
		.BYTE	$04
		.BYTE	$04,$F4,$03,$F8
		.BYTE	$04,$F4,$43,$00
		.BYTE	$F4,$F2,$03,$F8
		.BYTE	$F4,$F2,$43,$00
		.BYTE	$00
_sprA06_55:
		.BYTE	$04
		.BYTE	$04,$E8,$03,$F8
		.BYTE	$04,$E8,$43,$00
		.BYTE	$F4,$E6,$03,$F8
		.BYTE	$F4,$E6,$43,$00
		.BYTE	$00
_sprA06_56:
		.BYTE	$04
		.BYTE	$04,$F8,$03,$F8
		.BYTE	$04,$F8,$43,$00
		.BYTE	$F4,$F6,$03,$F8
		.BYTE	$F4,$F6,$43,$00
		.BYTE	$00
_sprA06_57:
		.BYTE	$04
		.BYTE	$04,$F4,$03,$FA
		.BYTE	$04,$F4,$43,$02
		.BYTE	$F4,$F2,$03,$FA
		.BYTE	$F4,$F2,$43,$02
		.BYTE	$00
_sprA06_58:
		.BYTE	$04
		.BYTE	$05,$EA,$03,$F3
		.BYTE	$05,$FA,$03,$FB
		.BYTE	$F5,$F2,$03,$F3
		.BYTE	$F5,$F2,$43,$FB
		.BYTE	$00
_sprA06_59:
		.BYTE	$02
		.BYTE	$FE,$EC,$03,$F1
		.BYTE	$FE,$FC,$03,$F9
		.BYTE	$00
_sprA06_5A:
		.BYTE	$04
		.BYTE	$06,$EA,$43,$07
		.BYTE	$06,$FA,$43,$FF
		.BYTE	$F6,$F2,$03,$FF
		.BYTE	$F6,$F2,$43,$07
		.BYTE	$00
_sprA06_5B:
		.BYTE	$02
		.BYTE	$FD,$EC,$43,$09
		.BYTE	$FD,$FC,$43,$01
		.BYTE	$00
_sprA06_5C:
		.BYTE	$01
		.BYTE	$FC,$FE,$01,$FD
		.BYTE	$00
_sprA06_5D:
		.BYTE	$01
		.BYTE	$FC,$EE,$01,$FC
		.BYTE	$00
_sprA06_5E:
		.BYTE	$06
		.BYTE	$04,$C2,$03,$FC
		.BYTE	$04,$D2,$03,$04
		.BYTE	$04,$D2,$43,$F4
		.BYTE	$F4,$D0,$03,$04
		.BYTE	$F4,$D0,$43,$F4
		.BYTE	$F4,$DE,$03,$FC
		.BYTE	$00
_sprA06_5F:
		.BYTE	$06
		.BYTE	$04,$CA,$03,$FC
		.BYTE	$04,$D2,$43,$F4
		.BYTE	$04,$DA,$03,$04
		.BYTE	$F4,$CC,$03,$F4
		.BYTE	$F4,$D8,$03,$04
		.BYTE	$F4,$DC,$03,$FC
		.BYTE	$00
_sprA06_60:
		.BYTE	$06
		.BYTE	$04,$D2,$03,$04
		.BYTE	$04,$D2,$43,$F4
		.BYTE	$04,$D6,$03,$FC
		.BYTE	$F4,$C4,$43,$04
		.BYTE	$F4,$C6,$43,$F4
		.BYTE	$F4,$D4,$43,$FC
		.BYTE	$00
_sprA06_61:
		.BYTE	$06
		.BYTE	$04,$CA,$43,$FC
		.BYTE	$04,$D2,$43,$00
		.BYTE	$04,$DA,$43,$F4
		.BYTE	$F4,$C8,$43,$FC
		.BYTE	$F4,$CC,$43,$04
		.BYTE	$F4,$D8,$43,$F4
		.BYTE	$00
_sprA06_62:
		.BYTE	$06
		.BYTE	$04,$C2,$03,$FC
		.BYTE	$04,$D2,$03,$04
		.BYTE	$04,$D2,$43,$F4
		.BYTE	$F4,$C0,$03,$FC
		.BYTE	$F4,$D0,$03,$04
		.BYTE	$F4,$D0,$43,$F4
		.BYTE	$00
_sprA06_63:
		.BYTE	$06
		.BYTE	$04,$CA,$03,$FC
		.BYTE	$04,$D2,$03,$FB
		.BYTE	$04,$DA,$03,$04
		.BYTE	$F4,$C8,$03,$FC
		.BYTE	$F4,$CC,$03,$F4
		.BYTE	$F4,$D8,$03,$04
		.BYTE	$00
_sprA06_64:
		.BYTE	$06
		.BYTE	$04,$D2,$03,$04
		.BYTE	$04,$D2,$43,$F4
		.BYTE	$04,$D6,$03,$FC
		.BYTE	$F4,$C4,$03,$F4
		.BYTE	$F4,$C6,$03,$04
		.BYTE	$F4,$D4,$03,$FC
		.BYTE	$00
_sprA06_65:
		.BYTE	$06
		.BYTE	$04,$CA,$43,$FC
		.BYTE	$04,$D2,$03,$04
		.BYTE	$04,$DA,$43,$F4
		.BYTE	$F4,$CC,$43,$04
		.BYTE	$F4,$D8,$43,$F4
		.BYTE	$F4,$DC,$43,$FC
		.BYTE	$00
_sprA06_66:
		.BYTE	$06
		.BYTE	$04,$C2,$03,$FE
		.BYTE	$04,$D2,$03,$06
		.BYTE	$04,$D2,$43,$F6
		.BYTE	$F4,$C0,$03,$FE
		.BYTE	$F4,$D0,$03,$06
		.BYTE	$F4,$D0,$43,$F6
		.BYTE	$00
_sprA06_67:
		.BYTE	$04
		.BYTE	$07,$CE,$03,$FA
		.BYTE	$F7,$C0,$03,$FA
		.BYTE	$F7,$C6,$03,$02
		.BYTE	$F7,$C6,$43,$F2
		.BYTE	$00
_sprA06_68:
		.BYTE	$01
		.BYTE	$FE,$BE,$03,$FA
		.BYTE	$00
_sprA06_69:
		.BYTE	$04
		.BYTE	$07,$CE,$43,$00
		.BYTE	$F7,$C0,$43,$00
		.BYTE	$F7,$C6,$03,$08
		.BYTE	$F7,$C6,$43,$F8
		.BYTE	$00
_sprA06_6A:
		.BYTE	$01
		.BYTE	$FE,$BE,$43,$FF
		.BYTE	$00
_sprA06_6B:
		.BYTE	$02
		.BYTE	$F8,$C9,$01,$D8
		.BYTE	$F8,$C9,$01,$20
		.BYTE	$00
_sprA06_6C:
		.BYTE	$02
		.BYTE	$F8,$C7,$01,$D8
		.BYTE	$F8,$C7,$01,$20
		.BYTE	$00
_sprA06_6D:
		.BYTE	$02
		.BYTE	$00,$05,$00,$FC
		.BYTE	$F0,$03,$00,$FC
		.BYTE	$00
_sprB06_C0:
		.BYTE	$07
		.BYTE	$0A,$3E,$00,$00
		.BYTE	$0A,$3E,$40,$F8
		.BYTE	$EC,$88,$03,$F8
		.BYTE	$EC,$98,$03,$00
		.BYTE	$EC,$B8,$03,$08
		.BYTE	$FC,$8A,$03,$F8
		.BYTE	$FC,$9A,$03,$00
		.BYTE	$00
_sprB06_C1:
		.BYTE	$08
		.BYTE	$0A,$3E,$00,$00
		.BYTE	$0A,$3E,$40,$F8
		.BYTE	$EC,$84,$43,$00
		.BYTE	$EC,$94,$43,$F8
		.BYTE	$EC,$BC,$43,$08
		.BYTE	$FC,$86,$43,$00
		.BYTE	$FC,$96,$43,$F8
		.BYTE	$FC,$AC,$43,$08
		.BYTE	$00
_sprB06_C2:
		.BYTE	$08
		.BYTE	$0A,$3E,$00,$00
		.BYTE	$0A,$3E,$40,$F8
		.BYTE	$EC,$80,$03,$F8
		.BYTE	$EC,$90,$03,$00
		.BYTE	$EC,$9C,$03,$F0
		.BYTE	$FC,$82,$03,$F8
		.BYTE	$FC,$92,$03,$00
		.BYTE	$FC,$9E,$03,$F0
		.BYTE	$00
_sprB06_C3:
		.BYTE	$08
		.BYTE	$0A,$3E,$00,$00
		.BYTE	$0A,$3E,$40,$F8
		.BYTE	$EC,$84,$03,$F8
		.BYTE	$EC,$94,$03,$00
		.BYTE	$EC,$BC,$03,$F0
		.BYTE	$FC,$86,$03,$F8
		.BYTE	$FC,$96,$03,$00
		.BYTE	$FC,$AC,$03,$F0
		.BYTE	$00
_sprB06_C4:
		.BYTE	$06
		.BYTE	$0A,$3E,$00,$00
		.BYTE	$0A,$3E,$40,$F8
		.BYTE	$EC,$88,$43,$00
		.BYTE	$EC,$A8,$03,$F8
		.BYTE	$FC,$8A,$43,$00
		.BYTE	$FC,$AA,$03,$F8
		.BYTE	$00
_sprB06_C5:
		.BYTE	$07
		.BYTE	$0A,$3E,$00,$00
		.BYTE	$0A,$3E,$40,$F8
		.BYTE	$EC,$A4,$43,$00
		.BYTE	$EC,$B4,$43,$F8
		.BYTE	$FC,$A6,$43,$00
		.BYTE	$FC,$B6,$43,$F8
		.BYTE	$FC,$BA,$43,$08
		.BYTE	$00
_sprB06_C6:
		.BYTE	$06
		.BYTE	$0A,$3E,$00,$00
		.BYTE	$0A,$3E,$40,$F8
		.BYTE	$EC,$A0,$03,$F8
		.BYTE	$EC,$B0,$03,$00
		.BYTE	$FC,$A2,$03,$F8
		.BYTE	$FC,$B2,$03,$00
		.BYTE	$00
_sprB06_C7:
		.BYTE	$07
		.BYTE	$0A,$3E,$00,$00
		.BYTE	$0A,$3E,$40,$F8
		.BYTE	$EC,$A4,$03,$F8
		.BYTE	$EC,$B4,$03,$00
		.BYTE	$FC,$A6,$03,$F8
		.BYTE	$FC,$B6,$03,$00
		.BYTE	$FC,$BA,$03,$F0
		.BYTE	$00
_sprB06_C8:
		.BYTE	$07
		.BYTE	$0A,$3E,$00,$02
		.BYTE	$0A,$3E,$40,$FA
		.BYTE	$EC,$88,$03,$FA
		.BYTE	$EC,$98,$03,$02
		.BYTE	$EC,$B8,$03,$0A
		.BYTE	$FC,$8A,$03,$FA
		.BYTE	$FC,$9A,$03,$02
		.BYTE	$00
_sprB06_C9:
		.BYTE	$08
		.BYTE	$0A,$3E,$00,$02
		.BYTE	$0A,$3E,$40,$FA
		.BYTE	$EC,$84,$43,$02
		.BYTE	$EC,$94,$43,$FA
		.BYTE	$EC,$BC,$43,$0A
		.BYTE	$FC,$86,$43,$02
		.BYTE	$FC,$96,$43,$FA
		.BYTE	$FC,$AC,$43,$0A
		.BYTE	$00
_sprB06_CA:
		.BYTE	$08
		.BYTE	$0A,$3E,$00,$02
		.BYTE	$0A,$3E,$40,$FA
		.BYTE	$EC,$80,$03,$FA
		.BYTE	$EC,$90,$03,$02
		.BYTE	$EC,$9C,$03,$F2
		.BYTE	$FC,$82,$03,$FA
		.BYTE	$FC,$92,$03,$02
		.BYTE	$FC,$9E,$03,$F2
		.BYTE	$00
_sprB06_CB:
		.BYTE	$08
		.BYTE	$0A,$3E,$00,$02
		.BYTE	$0A,$3E,$40,$FA
		.BYTE	$EC,$84,$03,$FA
		.BYTE	$EC,$94,$03,$02
		.BYTE	$EC,$BC,$03,$F2
		.BYTE	$FC,$86,$03,$FA
		.BYTE	$FC,$96,$03,$02
		.BYTE	$FC,$AC,$03,$F2
		.BYTE	$00
_sprB06_CC:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$E4,$8C,$03,$F8
		.BYTE	$E4,$8C,$43,$00
		.BYTE	$F4,$AC,$03,$F8
		.BYTE	$F4,$AC,$43,$00
		.BYTE	$00
_sprB06_CD:
		.BYTE	$07
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$E4,$B4,$43,$F8
		.BYTE	$F4,$A2,$43,$10
		.BYTE	$F4,$A6,$43,$00
		.BYTE	$F4,$B2,$43,$08
		.BYTE	$F4,$B6,$43,$F8
		.BYTE	$00
_sprB06_CE:
		.BYTE	$07
		.BYTE	$04,$BC,$03,$F8
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$E4,$8C,$03,$F8
		.BYTE	$E4,$8C,$43,$00
		.BYTE	$F4,$9C,$03,$F8
		.BYTE	$F4,$9C,$43,$00
		.BYTE	$00
_sprB06_CF:
		.BYTE	$07
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$E4,$B4,$03,$00
		.BYTE	$F4,$A2,$03,$E8
		.BYTE	$F4,$A6,$03,$F8
		.BYTE	$F4,$B2,$03,$F0
		.BYTE	$F4,$B6,$03,$00
		.BYTE	$00
_sprB06_D0:
		.BYTE	$07
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$EB,$BA,$C3,$00
		.BYTE	$F3,$8A,$03,$F0
		.BYTE	$F3,$8A,$43,$08
		.BYTE	$F3,$AA,$03,$F8
		.BYTE	$F3,$AA,$43,$00
		.BYTE	$00
_sprB06_D1:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F3,$82,$43,$10
		.BYTE	$F3,$92,$43,$08
		.BYTE	$F3,$96,$43,$F8
		.BYTE	$F3,$A6,$43,$00
		.BYTE	$00
_sprB06_D2:
		.BYTE	$07
		.BYTE	$03,$BA,$43,$F8
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F3,$8A,$03,$F0
		.BYTE	$F3,$8A,$43,$08
		.BYTE	$F3,$9A,$03,$F8
		.BYTE	$F3,$9A,$43,$00
		.BYTE	$00
_sprB06_D3:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F3,$82,$03,$E8
		.BYTE	$F3,$92,$03,$F0
		.BYTE	$F3,$96,$03,$00
		.BYTE	$F3,$A6,$03,$F8
		.BYTE	$00
_sprB06_D4:
		.BYTE	$07
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$EA,$B8,$C3,$00
		.BYTE	$F2,$88,$03,$F0
		.BYTE	$F2,$88,$43,$08
		.BYTE	$F2,$A8,$03,$F8
		.BYTE	$F2,$A8,$43,$00
		.BYTE	$00
_sprB06_D5:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F2,$84,$43,$10
		.BYTE	$F2,$86,$43,$F8
		.BYTE	$F2,$94,$43,$08
		.BYTE	$F2,$A6,$43,$00
		.BYTE	$00
_sprB06_D6:
		.BYTE	$07
		.BYTE	$02,$B8,$43,$F8
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F2,$88,$03,$F0
		.BYTE	$F2,$88,$43,$08
		.BYTE	$F2,$98,$03,$F8
		.BYTE	$F2,$98,$43,$00
		.BYTE	$00
_sprB06_D7:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F2,$84,$03,$E8
		.BYTE	$F2,$86,$03,$00
		.BYTE	$F2,$94,$03,$F0
		.BYTE	$F2,$A6,$03,$F8
		.BYTE	$00
_sprB06_D8:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$E4,$8C,$03,$F8
		.BYTE	$E4,$8C,$43,$00
		.BYTE	$F4,$AC,$03,$F8
		.BYTE	$F4,$AC,$43,$00
		.BYTE	$00
_sprB06_D9:
		.BYTE	$05
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$E4,$B4,$43,$F8
		.BYTE	$F4,$A6,$43,$00
		.BYTE	$F4,$B6,$43,$F8
		.BYTE	$00
_sprB06_DA:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$E4,$8C,$03,$F8
		.BYTE	$E4,$8C,$43,$00
		.BYTE	$F4,$9C,$03,$F8
		.BYTE	$F4,$9C,$43,$00
		.BYTE	$00
_sprB06_DB:
		.BYTE	$05
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$E4,$B4,$03,$00
		.BYTE	$F4,$A6,$03,$F8
		.BYTE	$F4,$B6,$03,$00
		.BYTE	$00
_sprB06_DC:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F3,$8A,$03,$F0
		.BYTE	$F3,$8A,$43,$08
		.BYTE	$F3,$AA,$03,$F8
		.BYTE	$F3,$AA,$43,$00
		.BYTE	$00
_sprB06_DD:
		.BYTE	$04
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F3,$96,$43,$F8
		.BYTE	$F3,$A6,$43,$00
		.BYTE	$00
_sprB06_DE:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F3,$8A,$03,$F0
		.BYTE	$F3,$8A,$43,$08
		.BYTE	$F3,$9A,$03,$F8
		.BYTE	$F3,$9A,$43,$00
		.BYTE	$00
_sprB06_DF:
		.BYTE	$04
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F3,$96,$03,$00
		.BYTE	$F3,$A6,$03,$F8
		.BYTE	$00
_sprB06_E0:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F2,$88,$03,$F0
		.BYTE	$F2,$88,$43,$08
		.BYTE	$F2,$A8,$03,$F8
		.BYTE	$F2,$A8,$43,$00
		.BYTE	$00
_sprB06_E1:
		.BYTE	$04
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F2,$86,$43,$F8
		.BYTE	$F2,$A6,$43,$00
		.BYTE	$00
_sprB06_E2:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F2,$88,$03,$F0
		.BYTE	$F2,$88,$43,$08
		.BYTE	$F2,$98,$03,$F8
		.BYTE	$F2,$98,$43,$00
		.BYTE	$00
_sprB06_E3:
		.BYTE	$04
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$F2,$86,$03,$00
		.BYTE	$F2,$A6,$03,$F8
		.BYTE	$00
_sprB06_E4:
		.BYTE	$06
		.BYTE	$06,$3E,$00,$02
		.BYTE	$06,$3E,$40,$FA
		.BYTE	$E4,$8C,$03,$FA
		.BYTE	$E4,$8C,$43,$02
		.BYTE	$F4,$AC,$03,$FA
		.BYTE	$F4,$AC,$43,$02
		.BYTE	$00
_sprB06_E5:
		.BYTE	$07
		.BYTE	$06,$3E,$00,$02
		.BYTE	$06,$3E,$40,$FA
		.BYTE	$E4,$B4,$43,$FA
		.BYTE	$F4,$A2,$43,$12
		.BYTE	$F4,$A6,$43,$02
		.BYTE	$F4,$B2,$43,$0A
		.BYTE	$F4,$B6,$43,$FA
		.BYTE	$00
_sprB06_E6:
		.BYTE	$07
		.BYTE	$04,$BC,$03,$FA
		.BYTE	$06,$3E,$00,$02
		.BYTE	$06,$3E,$40,$FA
		.BYTE	$E4,$8C,$03,$FA
		.BYTE	$E4,$8C,$43,$02
		.BYTE	$F4,$9C,$03,$FA
		.BYTE	$F4,$9C,$43,$02
		.BYTE	$00
_sprB06_E7:
		.BYTE	$07
		.BYTE	$06,$3E,$00,$02
		.BYTE	$06,$3E,$40,$FA
		.BYTE	$E4,$B4,$03,$02
		.BYTE	$F4,$A2,$03,$EA
		.BYTE	$F4,$A6,$03,$FA
		.BYTE	$F4,$B2,$03,$F2
		.BYTE	$F4,$B6,$03,$02
		.BYTE	$00
_sprB06_E8:
		.BYTE	$02
		.BYTE	$F8,$CE,$03,$00
		.BYTE	$F8,$BE,$03,$F8
		.BYTE	$00
_sprB06_E9:
		.BYTE	$02
		.BYTE	$F8,$EE,$03,$00
		.BYTE	$F8,$DE,$03,$F8
		.BYTE	$00
_sprB06_EA:
		.BYTE	$02
		.BYTE	$F8,$EE,$43,$F8
		.BYTE	$F8,$DE,$43,$00
		.BYTE	$00
_sprB06_EB:
		.BYTE	$02
		.BYTE	$F8,$9E,$03,$F8
		.BYTE	$F8,$AE,$03,$00
		.BYTE	$00
_sprA07_04:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$02,$8A,$02,$F8
		.BYTE	$02,$9A,$02,$00
		.BYTE	$F2,$8E,$02,$F8
		.BYTE	$F2,$9E,$02,$00
		.BYTE	$00
_sprA07_06:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$02,$8A,$42,$00
		.BYTE	$02,$9A,$42,$F8
		.BYTE	$F2,$8E,$42,$00
		.BYTE	$F2,$9E,$42,$F8
		.BYTE	$00
_sprA07_07:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$04,$9A,$02,$00
		.BYTE	$04,$9A,$42,$F8
		.BYTE	$F4,$9E,$02,$00
		.BYTE	$F4,$9E,$42,$F8
		.BYTE	$00
_sprA07_08:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$02,$8C,$42,$00
		.BYTE	$02,$9C,$42,$F8
		.BYTE	$F2,$A8,$42,$00
		.BYTE	$F2,$B8,$42,$F8
		.BYTE	$00
_sprA07_09:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$03,$AC,$02,$F8
		.BYTE	$03,$AC,$42,$00
		.BYTE	$F3,$AA,$42,$00
		.BYTE	$F3,$B8,$42,$F8
		.BYTE	$00
_sprA07_0A:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$02,$8C,$02,$F8
		.BYTE	$02,$9C,$02,$00
		.BYTE	$F2,$AA,$42,$00
		.BYTE	$F2,$BA,$42,$F8
		.BYTE	$00
_sprA07_0B:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$03,$AC,$02,$F8
		.BYTE	$03,$AC,$42,$00
		.BYTE	$F3,$AA,$42,$00
		.BYTE	$F3,$BA,$42,$F8
		.BYTE	$00
_sprA07_0C:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$02,$8A,$02,$F8
		.BYTE	$02,$9A,$02,$00
		.BYTE	$F2,$88,$02,$F8
		.BYTE	$F2,$98,$02,$00
		.BYTE	$00
_sprA07_0E:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$02,$8A,$42,$00
		.BYTE	$02,$9A,$42,$F8
		.BYTE	$F2,$88,$42,$00
		.BYTE	$F2,$98,$42,$F8
		.BYTE	$00
_sprA07_0F:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$03,$9A,$02,$00
		.BYTE	$03,$9A,$42,$F8
		.BYTE	$F3,$98,$02,$00
		.BYTE	$F3,$98,$42,$F8
		.BYTE	$00
_sprA07_10:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$02,$8C,$02,$F8
		.BYTE	$02,$9C,$02,$00
		.BYTE	$F2,$A8,$02,$F8
		.BYTE	$F2,$B8,$02,$00
		.BYTE	$00
_sprA07_11:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$03,$AC,$02,$F8
		.BYTE	$03,$AC,$42,$00
		.BYTE	$F3,$AA,$02,$F8
		.BYTE	$F3,$B8,$02,$00
		.BYTE	$00
_sprA07_12:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$02,$8C,$42,$00
		.BYTE	$02,$9C,$42,$F8
		.BYTE	$F2,$AA,$02,$F8
		.BYTE	$F2,$BA,$02,$00
		.BYTE	$00
_sprA07_13:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$04
		.BYTE	$03,$AC,$02,$F8
		.BYTE	$03,$AC,$42,$00
		.BYTE	$F3,$AA,$02,$F8
		.BYTE	$F3,$BA,$02,$00
		.BYTE	$00
_sprA07_14:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$02
		.BYTE	$08,$3E,$42,$FA
		.BYTE	$04
		.BYTE	$02,$8A,$02,$FA
		.BYTE	$02,$9A,$02,$02
		.BYTE	$F2,$8E,$02,$FA
		.BYTE	$F2,$9E,$02,$02
		.BYTE	$00
_sprA07_15:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$02
		.BYTE	$08,$3E,$42,$FA
		.BYTE	$04
		.BYTE	$02,$8C,$42,$02
		.BYTE	$02,$9C,$42,$FA
		.BYTE	$F2,$A8,$42,$02
		.BYTE	$F2,$B8,$42,$FA
		.BYTE	$00
_sprA07_16:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$02
		.BYTE	$08,$3E,$42,$FA
		.BYTE	$04
		.BYTE	$02,$8A,$02,$FA
		.BYTE	$02,$9A,$02,$02
		.BYTE	$F2,$88,$02,$FA
		.BYTE	$F2,$98,$02,$02
		.BYTE	$00
_sprA07_17:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$02
		.BYTE	$08,$3E,$42,$FA
		.BYTE	$04
		.BYTE	$02,$8C,$02,$FA
		.BYTE	$02,$9C,$02,$02
		.BYTE	$F2,$A8,$02,$FA
		.BYTE	$F2,$B8,$02,$02
		.BYTE	$00
_sprA07_18:
		.BYTE	$03
		.BYTE	$00,$B4,$02,$F6
		.BYTE	$F0,$A8,$02,$F0
		.BYTE	$F0,$B8,$02,$F8
		.BYTE	$00
_sprA07_19:
		.BYTE	$02
		.BYTE	$F8,$AE,$02,$F0
		.BYTE	$F8,$BE,$02,$F8
		.BYTE	$00
_sprA07_1A:
		.BYTE	$03
		.BYTE	$00,$B4,$42,$02
		.BYTE	$F0,$A8,$42,$08
		.BYTE	$F0,$B8,$42,$00
		.BYTE	$00
_sprA07_1B:
		.BYTE	$02
		.BYTE	$F8,$AE,$42,$08
		.BYTE	$F8,$BE,$42,$00
		.BYTE	$00
_sprA07_1C:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$05
		.BYTE	$00,$C8,$02,$F8
		.BYTE	$00,$C8,$42,$00
		.BYTE	$F0,$C6,$02,$F8
		.BYTE	$F0,$C6,$42,$00
		.BYTE	$F4,$E6,$40,$F4
		.BYTE	$00
_sprA07_1D:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$EC,$02,$F8
		.BYTE	$00,$FC,$02,$00
		.BYTE	$F0,$EA,$02,$F8
		.BYTE	$F0,$FA,$02,$00
		.BYTE	$F9,$D6,$00,$FD
		.BYTE	$F9,$E6,$00,$05
		.BYTE	$00
_sprA07_1E:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$E4,$02,$F8
		.BYTE	$00,$E4,$42,$00
		.BYTE	$F0,$C4,$02,$F8
		.BYTE	$F0,$C4,$42,$00
		.BYTE	$F9,$D6,$00,$FA
		.BYTE	$F9,$E6,$00,$02
		.BYTE	$00
_sprA07_1F:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$EC,$42,$00
		.BYTE	$00,$FC,$42,$F8
		.BYTE	$F0,$EA,$42,$00
		.BYTE	$F0,$FA,$42,$F8
		.BYTE	$F9,$D6,$40,$FB
		.BYTE	$F9,$E6,$40,$F3
		.BYTE	$00
_sprA07_20:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$05
		.BYTE	$00,$C8,$02,$F8
		.BYTE	$00,$C8,$42,$00
		.BYTE	$F0,$C6,$02,$F8
		.BYTE	$F0,$C6,$42,$00
		.BYTE	$F4,$E8,$40,$F4
		.BYTE	$00
_sprA07_21:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$EC,$02,$F8
		.BYTE	$00,$FC,$02,$00
		.BYTE	$F0,$EA,$02,$F8
		.BYTE	$F0,$FA,$02,$00
		.BYTE	$F9,$D8,$00,$FD
		.BYTE	$F9,$E8,$00,$05
		.BYTE	$00
_sprA07_22:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$E4,$02,$F8
		.BYTE	$00,$E4,$42,$00
		.BYTE	$F0,$C4,$02,$F8
		.BYTE	$F0,$C4,$42,$00
		.BYTE	$F9,$D8,$00,$FA
		.BYTE	$F9,$E8,$00,$02
		.BYTE	$00
_sprA07_23:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$EC,$42,$00
		.BYTE	$00,$FC,$42,$F8
		.BYTE	$F0,$EA,$42,$00
		.BYTE	$F0,$FA,$42,$F8
		.BYTE	$F9,$D8,$40,$FB
		.BYTE	$F9,$E8,$40,$F3
		.BYTE	$00
_sprA07_24:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$F6,$02,$F8
		.BYTE	$00,$F6,$42,$00
		.BYTE	$E9,$D6,$40,$00
		.BYTE	$E9,$E6,$40,$F8
		.BYTE	$F0,$F4,$02,$F8
		.BYTE	$F0,$F4,$42,$00
		.BYTE	$00
_sprA07_25:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$CC,$02,$F8
		.BYTE	$00,$DC,$02,$00
		.BYTE	$EE,$D6,$00,$FA
		.BYTE	$EE,$E6,$00,$02
		.BYTE	$F0,$CA,$02,$F8
		.BYTE	$F0,$DA,$02,$00
		.BYTE	$00
_sprA07_26:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$E4,$02,$F8
		.BYTE	$00,$E4,$42,$00
		.BYTE	$ED,$D6,$00,$F9
		.BYTE	$ED,$E6,$00,$01
		.BYTE	$F0,$D4,$02,$F8
		.BYTE	$F0,$D4,$42,$00
		.BYTE	$00
_sprA07_27:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$CC,$42,$00
		.BYTE	$00,$DC,$42,$F8
		.BYTE	$EE,$D6,$40,$FE
		.BYTE	$EE,$E6,$40,$F6
		.BYTE	$F0,$CA,$42,$00
		.BYTE	$F0,$DA,$42,$F8
		.BYTE	$00
_sprA07_28:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$F6,$02,$F8
		.BYTE	$00,$F6,$42,$00
		.BYTE	$E9,$D8,$40,$00
		.BYTE	$E9,$E8,$40,$F8
		.BYTE	$F0,$F4,$02,$F8
		.BYTE	$F0,$F4,$42,$00
		.BYTE	$00
_sprA07_29:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$CC,$02,$F8
		.BYTE	$00,$DC,$02,$00
		.BYTE	$EE,$D8,$00,$FA
		.BYTE	$EE,$E8,$00,$02
		.BYTE	$F0,$CA,$02,$F8
		.BYTE	$F0,$DA,$02,$00
		.BYTE	$00
_sprA07_2A:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$E4,$02,$F8
		.BYTE	$00,$E4,$42,$00
		.BYTE	$ED,$D8,$00,$F9
		.BYTE	$ED,$E8,$00,$01
		.BYTE	$F0,$D4,$02,$F8
		.BYTE	$F0,$D4,$42,$00
		.BYTE	$00
_sprA07_2B:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
		.BYTE	$06
		.BYTE	$00,$CC,$42,$00
		.BYTE	$00,$DC,$42,$F8
		.BYTE	$EE,$D8,$40,$FE
		.BYTE	$EE,$E8,$40,$F6
		.BYTE	$F0,$CA,$42,$00
		.BYTE	$F0,$DA,$42,$F8
		.BYTE	$00
_sprA07_2C:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$02
		.BYTE	$08,$3E,$42,$FA
		.BYTE	$06
		.BYTE	$00,$F6,$02,$FA
		.BYTE	$00,$F6,$42,$02
		.BYTE	$E9,$D6,$40,$02
		.BYTE	$E9,$E6,$40,$FA
		.BYTE	$F0,$F4,$02,$FA
		.BYTE	$F0,$F4,$42,$02
		.BYTE	$00
_sprA07_2D:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$02
		.BYTE	$08,$3E,$42,$FA
		.BYTE	$06
		.BYTE	$00,$CC,$02,$FA
		.BYTE	$00,$DC,$02,$02
		.BYTE	$EE,$D6,$00,$FC
		.BYTE	$EE,$E6,$00,$04
		.BYTE	$F0,$CA,$02,$FA
		.BYTE	$F0,$DA,$02,$02
		.BYTE	$00
_sprA07_2E:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$02
		.BYTE	$08,$3E,$42,$FA
		.BYTE	$06
		.BYTE	$00,$E4,$02,$FA
		.BYTE	$00,$E4,$42,$02
		.BYTE	$ED,$D6,$00,$FB
		.BYTE	$ED,$E6,$00,$03
		.BYTE	$F0,$D4,$02,$FA
		.BYTE	$F0,$D4,$42,$02
		.BYTE	$00
_sprA07_2F:
		.BYTE	$02
		.BYTE	$08,$3E,$02,$02
		.BYTE	$08,$3E,$42,$FA
		.BYTE	$06
		.BYTE	$00,$CC,$42,$02
		.BYTE	$00,$DC,$42,$FA
		.BYTE	$EE,$D6,$40,$00
		.BYTE	$EE,$E6,$40,$F8
		.BYTE	$F0,$CA,$42,$02
		.BYTE	$F0,$DA,$42,$FA
		.BYTE	$00
_sprA07_30:
		.BYTE	$03
		.BYTE	$00,$B4,$02,$F8
		.BYTE	$F0,$CA,$42,$F8
		.BYTE	$F0,$DA,$42,$F0
		.BYTE	$00
_sprA07_31:
		.BYTE	$02
		.BYTE	$F8,$CE,$42,$F8
		.BYTE	$F8,$DE,$42,$F0
		.BYTE	$00
_sprA07_32:
		.BYTE	$03
		.BYTE	$00,$B4,$42,$00
		.BYTE	$F0,$CA,$02,$00
		.BYTE	$F0,$DA,$02,$08
		.BYTE	$00
_sprA07_33:
		.BYTE	$02
		.BYTE	$F8,$CE,$02,$00
		.BYTE	$F8,$DE,$02,$08
		.BYTE	$00
_sprA07_34:
		.BYTE	$02
		.BYTE	$08,$3E,$40,$F8
		.BYTE	$08,$3E,$00,$00
		.BYTE	$00
_sprA07_35:
		.BYTE	$01
		.BYTE	$F8,$F8,$02,$FC
		.BYTE	$00
_sprA07_36:
		.BYTE	$03
		.BYTE	$F4,$F8,$02,$FC
		.BYTE	$FC,$E0,$02,$F8
		.BYTE	$FC,$E0,$42,$00
		.BYTE	$00
_sprA07_37:
		.BYTE	$0B
		.BYTE	$00,$E0,$02,$F8
		.BYTE	$00,$E0,$42,$00
		.BYTE	$F1,$F8,$02,$FC
		.BYTE	$F4,$E2,$82,$F8
		.BYTE	$F4,$E2,$C2,$00
		.BYTE	$F7,$E2,$82,$F8
		.BYTE	$F7,$E2,$C2,$00
		.BYTE	$FA,$E2,$82,$F8
		.BYTE	$FA,$E2,$C2,$00
		.BYTE	$FD,$E2,$82,$F8
		.BYTE	$FD,$E2,$C2,$00
		.BYTE	$00
_sprA07_38:
		.BYTE	$0B
		.BYTE	$02,$E0,$02,$F8
		.BYTE	$02,$E0,$42,$00
		.BYTE	$EE,$F8,$02,$FC
		.BYTE	$F2,$E2,$82,$F8
		.BYTE	$F2,$E2,$C2,$00
		.BYTE	$F6,$E2,$82,$F8
		.BYTE	$F6,$E2,$C2,$00
		.BYTE	$FA,$E2,$82,$F8
		.BYTE	$FA,$E2,$C2,$00
		.BYTE	$FE,$E2,$82,$F8
		.BYTE	$FE,$E2,$C2,$00
		.BYTE	$00
_sprA07_39:
		.BYTE	$0B
		.BYTE	$00,$E2,$82,$F8
		.BYTE	$00,$E2,$C2,$00
		.BYTE	$05,$E0,$02,$F8
		.BYTE	$05,$E0,$42,$00
		.BYTE	$EC,$F8,$02,$FC
		.BYTE	$F1,$E2,$82,$F8
		.BYTE	$F1,$E2,$C2,$00
		.BYTE	$F6,$E2,$82,$F8
		.BYTE	$F6,$E2,$C2,$00
		.BYTE	$FB,$E2,$82,$F8
		.BYTE	$FB,$E2,$C2,$00
		.BYTE	$00
_sprA07_3A:
		.BYTE	$0B
		.BYTE	$01,$E2,$82,$F8
		.BYTE	$01,$E2,$C2,$00
		.BYTE	$07,$E0,$02,$F8
		.BYTE	$07,$E0,$42,$00
		.BYTE	$E9,$F8,$02,$FC
		.BYTE	$EF,$E2,$82,$F8
		.BYTE	$EF,$E2,$C2,$00
		.BYTE	$F5,$E2,$82,$F8
		.BYTE	$F5,$E2,$C2,$00
		.BYTE	$FB,$E2,$82,$F8
		.BYTE	$FB,$E2,$C2,$00
		.BYTE	$00
_sprA07_3B:
		.BYTE	$0B
		.BYTE	$03,$E2,$82,$F8
		.BYTE	$03,$E2,$C2,$00
		.BYTE	$0A,$E0,$02,$F8
		.BYTE	$0A,$E0,$42,$00
		.BYTE	$E7,$F8,$02,$FC
		.BYTE	$EE,$E2,$82,$F8
		.BYTE	$EE,$E2,$C2,$00
		.BYTE	$F5,$E2,$82,$F8
		.BYTE	$F5,$E2,$C2,$00
		.BYTE	$FC,$E2,$82,$F8
		.BYTE	$FC,$E2,$C2,$00
		.BYTE	$00
_sprA07_3C:
		.BYTE	$0B
		.BYTE	$04,$E2,$82,$F8
		.BYTE	$04,$E2,$C2,$00
		.BYTE	$0C,$E0,$02,$F8
		.BYTE	$0C,$E0,$42,$00
		.BYTE	$E4,$F8,$02,$FC
		.BYTE	$EC,$E2,$82,$F8
		.BYTE	$EC,$E2,$C2,$00
		.BYTE	$F4,$E2,$82,$F8
		.BYTE	$F4,$E2,$C2,$00
		.BYTE	$FC,$E2,$82,$F8
		.BYTE	$FC,$E2,$C2,$00
		.BYTE	$00
_sprA07_3D:
		.BYTE	$0B
		.BYTE	$04,$E2,$82,$FA
		.BYTE	$04,$E2,$C2,$02
		.BYTE	$0C,$E0,$02,$FA
		.BYTE	$0C,$E0,$42,$02
		.BYTE	$E4,$F8,$02,$FE
		.BYTE	$EC,$E2,$82,$FA
		.BYTE	$EC,$E2,$C2,$02
		.BYTE	$F4,$E2,$82,$FA
		.BYTE	$F4,$E2,$C2,$02
		.BYTE	$FC,$E2,$82,$FA
		.BYTE	$FC,$E2,$C2,$02
		.BYTE	$00
_sprA07_3E:
		.BYTE	$04
		.BYTE	$F4,$C0,$02,$EC
		.BYTE	$F4,$D0,$02,$F4
		.BYTE	$F8,$F2,$C2,$F3
		.BYTE	$FD,$F2,$02,$F8
		.BYTE	$00
_sprA07_3F:
		.BYTE	$03
		.BYTE	$00,$B4,$02,$F8
		.BYTE	$F8,$C0,$02,$F0
		.BYTE	$F8,$D0,$02,$F8
		.BYTE	$00
_sprA07_40:
		.BYTE	$04
		.BYTE	$F4,$C0,$42,$0D
		.BYTE	$F4,$D0,$42,$05
		.BYTE	$F8,$F2,$82,$06
		.BYTE	$FD,$F2,$42,$01
		.BYTE	$00
_sprA07_41:
		.BYTE	$03
		.BYTE	$00,$B4,$42,$00
		.BYTE	$F8,$C0,$42,$08
		.BYTE	$F8,$D0,$42,$00
		.BYTE	$00
_sprA07_42:
		.BYTE	$08
		.BYTE	$EE,$D8,$03,$F2
		.BYTE	$EE,$E0,$03,$FA
		.BYTE	$EE,$F0,$03,$02
		.BYTE	$FC,$EC,$00,$EE
		.BYTE	$FC,$FC,$00,$F6
		.BYTE	$FE,$CE,$03,$F2
		.BYTE	$FE,$DE,$03,$FA
		.BYTE	$FE,$EE,$03,$02
		.BYTE	$00
_sprA07_43:
		.BYTE	$04
		.BYTE	$06,$AE,$03,$FA
		.BYTE	$06,$BE,$03,$02
		.BYTE	$F6,$E0,$03,$FA
		.BYTE	$F6,$F0,$03,$02
		.BYTE	$00
_sprA07_44:
		.BYTE	$04
		.BYTE	$DA,$C8,$00,$FC
		.BYTE	$EA,$C8,$00,$FC
		.BYTE	$F8,$EC,$00,$F8
		.BYTE	$F8,$FC,$00,$00
		.BYTE	$00
_sprA07_45:
		.BYTE	$05
		.BYTE	$CA,$C8,$00,$FC
		.BYTE	$DA,$C8,$00,$FC
		.BYTE	$EA,$C8,$00,$FC
		.BYTE	$F8,$EC,$00,$F8
		.BYTE	$F8,$FC,$00,$00
		.BYTE	$00
_sprA07_46:
		.BYTE	$06
		.BYTE	$BA,$C8,$00,$FC
		.BYTE	$CA,$C8,$00,$FC
		.BYTE	$DA,$C8,$00,$FC
		.BYTE	$EA,$C8,$00,$FC
		.BYTE	$F8,$EC,$00,$F8
		.BYTE	$F8,$FC,$00,$00
		.BYTE	$00
_sprA07_47:
		.BYTE	$07
		.BYTE	$AA,$C8,$00,$FC
		.BYTE	$BA,$C8,$00,$FC
		.BYTE	$CA,$C8,$00,$FC
		.BYTE	$DA,$C8,$00,$FC
		.BYTE	$EA,$C8,$00,$FC
		.BYTE	$F8,$EC,$00,$F8
		.BYTE	$F8,$FC,$00,$00
		.BYTE	$00
_sprA07_48:
		.BYTE	$08
		.BYTE	$9A,$C8,$00,$FC
		.BYTE	$AA,$C8,$00,$FC
		.BYTE	$BA,$C8,$00,$FC
		.BYTE	$CA,$C8,$00,$FC
		.BYTE	$DA,$C8,$00,$FC
		.BYTE	$EA,$C8,$00,$FC
		.BYTE	$F8,$EC,$00,$F8
		.BYTE	$F8,$FC,$00,$00
		.BYTE	$00
_sprA07_49:
		.BYTE	$09
		.BYTE	$8A,$C8,$00,$FC
		.BYTE	$9A,$C8,$00,$FC
		.BYTE	$AA,$C8,$00,$FC
		.BYTE	$BA,$C8,$00,$FC
		.BYTE	$CA,$C8,$00,$FC
		.BYTE	$DA,$C8,$00,$FC
		.BYTE	$EA,$C8,$00,$FC
		.BYTE	$F8,$EC,$00,$F8
		.BYTE	$F8,$FC,$00,$00
		.BYTE	$00
_sprA07_4A:
		.BYTE	$0A
		.BYTE	$7A,$C8,$00,$FC
		.BYTE	$8A,$C8,$00,$FC
		.BYTE	$9A,$C8,$00,$FC
		.BYTE	$AA,$C8,$00,$FC
		.BYTE	$BA,$C8,$00,$FC
		.BYTE	$CA,$C8,$00,$FC
		.BYTE	$DA,$C8,$00,$FC
		.BYTE	$EA,$C8,$00,$FC
		.BYTE	$F8,$EC,$00,$F8
		.BYTE	$F8,$FC,$00,$00
		.BYTE	$00
_sprA07_4B:
		.BYTE	$0B
		.BYTE	$6A,$C8,$00,$FC
		.BYTE	$7A,$C8,$00,$FC
		.BYTE	$8A,$C8,$00,$FC
		.BYTE	$9A,$C8,$00,$FC
		.BYTE	$AA,$C8,$00,$FC
		.BYTE	$BA,$C8,$00,$FC
		.BYTE	$CA,$C8,$00,$FC
		.BYTE	$DA,$C8,$00,$FC
		.BYTE	$EA,$C8,$00,$FC
		.BYTE	$F8,$EC,$00,$F8
		.BYTE	$F8,$FC,$00,$00
		.BYTE	$00
_sprA07_4C:
		.BYTE	$06
		.BYTE	$04,$96,$02,$F8
		.BYTE	$04,$96,$42,$00
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$94,$02,$F8
		.BYTE	$F4,$94,$42,$00
		.BYTE	$00
_sprA07_4D:
		.BYTE	$06
		.BYTE	$04,$8A,$42,$00
		.BYTE	$04,$9A,$42,$F8
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$88,$42,$00
		.BYTE	$F4,$98,$42,$F8
		.BYTE	$00
_sprA07_4E:
		.BYTE	$06
		.BYTE	$04,$92,$02,$F8
		.BYTE	$04,$92,$42,$00
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$90,$02,$F8
		.BYTE	$F4,$90,$42,$00
		.BYTE	$00
_sprA07_4F:
		.BYTE	$06
		.BYTE	$04,$8A,$02,$F8
		.BYTE	$04,$9A,$02,$00
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$88,$02,$F8
		.BYTE	$F4,$98,$02,$00
		.BYTE	$00
_sprA07_50:
		.BYTE	$06
		.BYTE	$04,$86,$02,$F8
		.BYTE	$04,$86,$42,$00
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$84,$02,$F8
		.BYTE	$F4,$84,$42,$00
		.BYTE	$00
_sprA07_51:
		.BYTE	$06
		.BYTE	$04,$8E,$42,$00
		.BYTE	$04,$9E,$42,$F8
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$8C,$42,$00
		.BYTE	$F4,$9C,$42,$F8
		.BYTE	$00
_sprA07_52:
		.BYTE	$06
		.BYTE	$04,$82,$02,$F8
		.BYTE	$04,$82,$42,$00
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$80,$02,$F8
		.BYTE	$F4,$80,$42,$00
		.BYTE	$00
_sprA07_53:
		.BYTE	$06
		.BYTE	$04,$8E,$02,$F8
		.BYTE	$04,$9E,$02,$00
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$8C,$02,$F8
		.BYTE	$F4,$9C,$02,$00
		.BYTE	$00
_sprA07_54:
		.BYTE	$06
		.BYTE	$04,$96,$02,$FA
		.BYTE	$04,$96,$42,$02
		.BYTE	$10,$E8,$00,$FA
		.BYTE	$10,$E8,$40,$02
		.BYTE	$F4,$94,$02,$FA
		.BYTE	$F4,$94,$42,$02
		.BYTE	$00
_sprA07_55:
		.BYTE	$06
		.BYTE	$04,$8A,$42,$02
		.BYTE	$04,$9A,$42,$FA
		.BYTE	$10,$E8,$00,$FA
		.BYTE	$10,$E8,$40,$02
		.BYTE	$F4,$88,$42,$02
		.BYTE	$F4,$98,$42,$FA
		.BYTE	$00
_sprA07_56:
		.BYTE	$06
		.BYTE	$04,$92,$02,$FA
		.BYTE	$04,$92,$42,$02
		.BYTE	$10,$E8,$00,$FA
		.BYTE	$10,$E8,$40,$02
		.BYTE	$F4,$90,$02,$FA
		.BYTE	$F4,$90,$42,$02
		.BYTE	$00
_sprA07_57:
		.BYTE	$06
		.BYTE	$04,$8A,$02,$FA
		.BYTE	$04,$9A,$02,$02
		.BYTE	$10,$E8,$00,$FA
		.BYTE	$10,$E8,$40,$02
		.BYTE	$F4,$88,$02,$FA
		.BYTE	$F4,$98,$02,$02
		.BYTE	$00
_sprA07_58:
		.BYTE	$04
		.BYTE	$ED,$C2,$02,$F3
		.BYTE	$ED,$D2,$02,$FB
		.BYTE	$FD,$C4,$02,$F3
		.BYTE	$FD,$D4,$02,$FB
		.BYTE	$00
_sprA07_59:
		.BYTE	$02
		.BYTE	$FC,$C6,$02,$F3
		.BYTE	$FC,$D6,$02,$FB
		.BYTE	$00
_sprA07_5A:
		.BYTE	$04
		.BYTE	$ED,$C2,$42,$06
		.BYTE	$ED,$D2,$42,$FE
		.BYTE	$FD,$C4,$42,$06
		.BYTE	$FD,$D4,$42,$FE
		.BYTE	$00
_sprA07_5B:
		.BYTE	$02
		.BYTE	$FC,$C6,$42,$06
		.BYTE	$FC,$D6,$42,$FE
		.BYTE	$00
_sprA07_5C:
		.BYTE	$06
		.BYTE	$04,$E2,$02,$F8
		.BYTE	$04,$F2,$02,$00
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$E0,$02,$F8
		.BYTE	$F4,$F0,$02,$00
		.BYTE	$00
_sprA07_5D:
		.BYTE	$06
		.BYTE	$04,$E2,$42,$00
		.BYTE	$04,$F2,$42,$F8
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$E0,$42,$00
		.BYTE	$F4,$F0,$42,$F8
		.BYTE	$00
_sprA07_5E:
		.BYTE	$06
		.BYTE	$04,$F2,$02,$00
		.BYTE	$04,$F2,$42,$F8
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$F0,$02,$00
		.BYTE	$F4,$F0,$42,$F8
		.BYTE	$00
_sprA07_5F:
		.BYTE	$06
		.BYTE	$04,$E6,$02,$F8
		.BYTE	$04,$F6,$02,$00
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$E4,$02,$F8
		.BYTE	$F4,$F4,$02,$00
		.BYTE	$00
_sprA07_60:
		.BYTE	$06
		.BYTE	$04,$E6,$42,$00
		.BYTE	$04,$F6,$42,$F8
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$E4,$42,$00
		.BYTE	$F4,$F4,$42,$F8
		.BYTE	$00
_sprA07_61:
		.BYTE	$06
		.BYTE	$04,$F6,$02,$00
		.BYTE	$04,$F6,$42,$F8
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
		.BYTE	$F4,$F4,$02,$00
		.BYTE	$F4,$F4,$42,$F8
		.BYTE	$00
_sprA07_62:
		.BYTE	$02
		.BYTE	$FA,$48,$00,$FA
		.BYTE	$FC,$48,$00,$FF
		.BYTE	$00
_sprA07_63:
		.BYTE	$03
		.BYTE	$F4,$58,$00,$FC
		.BYTE	$FA,$58,$00,$00
		.BYTE	$FA,$58,$00,$F8
		.BYTE	$00
_sprA07_64:
		.BYTE	$05
		.BYTE	$E7,$58,$00,$F6
		.BYTE	$E8,$58,$00,$02
		.BYTE	$F4,$58,$00,$F1
		.BYTE	$F7,$58,$00,$08
		.BYTE	$FD,$58,$00,$FC
		.BYTE	$00
_sprA07_65:
		.BYTE	$05
		.BYTE	$05,$48,$00,$FC
		.BYTE	$E4,$48,$00,$F4
		.BYTE	$E5,$48,$00,$06
		.BYTE	$F7,$48,$00,$EE
		.BYTE	$FC,$48,$00,$0F
		.BYTE	$00
_sprA07_66:
		.BYTE	$04
		.BYTE	$00,$AA,$00,$F8
		.BYTE	$00,$BA,$00,$00
		.BYTE	$F0,$A8,$00,$F8
		.BYTE	$F0,$B8,$00,$00
		.BYTE	$00
_sprA07_67:
		.BYTE	$04
		.BYTE	$00,$AA,$40,$01
		.BYTE	$00,$BA,$40,$F9
		.BYTE	$F0,$A8,$40,$01
		.BYTE	$F0,$B8,$40,$F9
		.BYTE	$00
_sprA07_68:
		.BYTE	$04
		.BYTE	$00,$AA,$00,$F8
		.BYTE	$00,$BA,$00,$00
		.BYTE	$F0,$C8,$40,$00
		.BYTE	$F0,$D8,$40,$F8
		.BYTE	$00
_sprA07_69:
		.BYTE	$04
		.BYTE	$00,$AA,$40,$01
		.BYTE	$00,$BA,$40,$F9
		.BYTE	$F0,$C8,$00,$F9
		.BYTE	$F0,$D8,$00,$01
		.BYTE	$00
_sprA07_6A:
		.BYTE	$04
		.BYTE	$00,$AE,$00,$F8
		.BYTE	$00,$AE,$40,$00
		.BYTE	$F0,$BC,$00,$00
		.BYTE	$F0,$BC,$40,$F8
		.BYTE	$00
_sprA07_6B:
		.BYTE	$04
		.BYTE	$00,$AE,$00,$F8
		.BYTE	$00,$AE,$40,$00
		.BYTE	$F0,$AC,$00,$F8
		.BYTE	$F0,$AC,$40,$00
		.BYTE	$00
_sprA07_6C:
		.BYTE	$01
		.BYTE	$FC,$A6,$02,$FC
		.BYTE	$00
_sprA07_6D:
		.BYTE	$01
		.BYTE	$FC,$A4,$42,$FC
		.BYTE	$00
_sprA07_6E:
		.BYTE	$01
		.BYTE	$FC,$A2,$42,$FC
		.BYTE	$00
_sprA07_6F:
		.BYTE	$01
		.BYTE	$FC,$A4,$02,$FC
		.BYTE	$00
_sprA07_70:
		.BYTE	$01
		.BYTE	$FC,$B6,$02,$FC
		.BYTE	$00
_sprA07_71:
		.BYTE	$01
		.BYTE	$FC,$B4,$42,$FC
		.BYTE	$00
_sprA07_72:
		.BYTE	$01
		.BYTE	$FC,$B2,$42,$FC
		.BYTE	$00
_sprA07_73:
		.BYTE	$01
		.BYTE	$FC,$B4,$02,$FC
		.BYTE	$00
_sprA07_74:
		.BYTE	$01
		.BYTE	$FC,$B6,$02,$FE
		.BYTE	$00
_sprA07_75:
		.BYTE	$01
		.BYTE	$FC,$B4,$42,$FE
		.BYTE	$00
_sprA07_76:
		.BYTE	$01
		.BYTE	$FC,$B2,$42,$FE
		.BYTE	$00
_sprA07_77:
		.BYTE	$01
		.BYTE	$FC,$B4,$02,$FE
		.BYTE	$00
_sprA07_78:
		.BYTE	$01
		.BYTE	$02,$B4,$02,$FB
		.BYTE	$00
_sprA07_79:
		.BYTE	$01
		.BYTE	$02,$A4,$02,$FA
		.BYTE	$00
_sprA07_7A:
		.BYTE	$01
		.BYTE	$02,$B4,$42,$FE
		.BYTE	$00
_sprA07_7B:
		.BYTE	$01
		.BYTE	$02,$A4,$42,$FE
		.BYTE	$00
_sprA07_7C:
		.BYTE	$04
		.BYTE	$08,$B4,$00,$00
		.BYTE	$08,$B4,$40,$F8
		.BYTE	$F8,$A2,$00,$00
		.BYTE	$F8,$A2,$40,$F8
		.BYTE	$00
_sprA07_7D:
		.BYTE	$04
		.BYTE	$08,$84,$40,$00
		.BYTE	$08,$94,$40,$F8
		.BYTE	$F9,$82,$40,$00
		.BYTE	$F9,$92,$40,$F8
		.BYTE	$00
_sprA07_7E:
		.BYTE	$04
		.BYTE	$08,$28,$40,$00
		.BYTE	$08,$38,$40,$F8
		.BYTE	$F8,$82,$40,$00
		.BYTE	$F8,$92,$40,$F8
		.BYTE	$00
_sprA07_7F:
		.BYTE	$04
		.BYTE	$08,$84,$00,$F8
		.BYTE	$08,$94,$00,$00
		.BYTE	$F9,$82,$40,$00
		.BYTE	$F9,$92,$40,$F8
		.BYTE	$00
_sprA07_80:
		.BYTE	$04
		.BYTE	$08,$B4,$00,$00
		.BYTE	$08,$B4,$40,$F8
		.BYTE	$F8,$B2,$00,$00
		.BYTE	$F8,$B2,$40,$F8
		.BYTE	$00
_sprA07_81:
		.BYTE	$04
		.BYTE	$08,$84,$40,$00
		.BYTE	$08,$94,$40,$F8
		.BYTE	$F9,$82,$00,$F8
		.BYTE	$F9,$92,$00,$00
		.BYTE	$00
_sprA07_82:
		.BYTE	$04
		.BYTE	$08,$28,$00,$F8
		.BYTE	$08,$38,$00,$00
		.BYTE	$F8,$82,$00,$F8
		.BYTE	$F8,$92,$00,$00
		.BYTE	$00
_sprA07_83:
		.BYTE	$04
		.BYTE	$08,$84,$00,$F8
		.BYTE	$08,$94,$00,$00
		.BYTE	$F9,$82,$00,$F8
		.BYTE	$F9,$92,$00,$00
		.BYTE	$00
_sprA07_84:
		.BYTE	$02
		.BYTE	$F8,$E0,$00,$F8
		.BYTE	$F8,$F0,$00,$00
		.BYTE	$00
_sprA07_85:
		.BYTE	$02
		.BYTE	$F8,$A0,$00,$F8
		.BYTE	$F8,$B0,$00,$00
		.BYTE	$00
_sprA07_86:
		.BYTE	$0C
		.BYTE	$00,$EA,$03,$00
		.BYTE	$00,$EA,$43,$F8
		.BYTE	$08,$DE,$03,$F8
		.BYTE	$08,$EE,$03,$00
		.BYTE	$E0,$E6,$03,$00
		.BYTE	$E0,$F6,$03,$F8
		.BYTE	$F0,$E8,$03,$00
		.BYTE	$F0,$E8,$43,$F8
		.BYTE	$F0,$F8,$03,$08
		.BYTE	$F0,$F8,$43,$F0
		.BYTE	$F8,$DC,$03,$F8
		.BYTE	$F8,$EC,$03,$00
		.BYTE	$00
_sprA07_87:
		.BYTE	$0B
		.BYTE	$08,$C4,$03,$F8
		.BYTE	$08,$D4,$03,$00
		.BYTE	$08,$E4,$03,$08
		.BYTE	$08,$F4,$03,$10
		.BYTE	$E8,$C0,$03,$F8
		.BYTE	$E8,$D0,$03,$00
		.BYTE	$F8,$C2,$03,$F8
		.BYTE	$F8,$D2,$03,$00
		.BYTE	$F8,$E2,$03,$08
		.BYTE	$F8,$F2,$03,$10
		.BYTE	$FA,$FC,$03,$01
		.BYTE	$00
_sprA07_88:
		.BYTE	$0D
		.BYTE	$06,$C6,$03,$FB
		.BYTE	$08,$C4,$03,$F8
		.BYTE	$08,$D4,$03,$00
		.BYTE	$08,$E4,$03,$08
		.BYTE	$08,$F4,$03,$10
		.BYTE	$0A,$DA,$03,$00
		.BYTE	$0B,$CA,$03,$F8
		.BYTE	$E8,$C0,$03,$F8
		.BYTE	$E8,$D0,$03,$00
		.BYTE	$F8,$C2,$03,$F8
		.BYTE	$F8,$D2,$03,$00
		.BYTE	$F8,$E2,$03,$08
		.BYTE	$F8,$F2,$03,$10
		.BYTE	$00
_sprA07_89:
		.BYTE	$0E
		.BYTE	$06,$C6,$03,$FB
		.BYTE	$08,$C4,$03,$F8
		.BYTE	$08,$D4,$03,$00
		.BYTE	$08,$E4,$03,$08
		.BYTE	$08,$F4,$03,$10
		.BYTE	$0E,$D8,$03,$01
		.BYTE	$15,$DA,$03,$01
		.BYTE	$16,$CA,$03,$F9
		.BYTE	$E8,$C0,$03,$F8
		.BYTE	$E8,$D0,$03,$00
		.BYTE	$F8,$C2,$03,$F8
		.BYTE	$F8,$D2,$03,$00
		.BYTE	$F8,$E2,$03,$08
		.BYTE	$F8,$F2,$03,$10
		.BYTE	$00
_sprA07_8A:
		.BYTE	$10
		.BYTE	$06,$C6,$03,$FB
		.BYTE	$06,$D6,$03,$03
		.BYTE	$08,$C4,$03,$F8
		.BYTE	$08,$D4,$03,$00
		.BYTE	$08,$E4,$03,$08
		.BYTE	$08,$F4,$03,$10
		.BYTE	$16,$C8,$03,$FB
		.BYTE	$16,$D8,$03,$03
		.BYTE	$24,$DA,$03,$03
		.BYTE	$26,$CA,$03,$FB
		.BYTE	$E8,$C0,$03,$F8
		.BYTE	$E8,$D0,$03,$00
		.BYTE	$F8,$C2,$03,$F8
		.BYTE	$F8,$D2,$03,$00
		.BYTE	$F8,$E2,$03,$08
		.BYTE	$F8,$F2,$03,$10
		.BYTE	$00
_sprA07_8B:
		.BYTE	$12
		.BYTE	$06,$C6,$03,$FB
		.BYTE	$06,$D6,$03,$03
		.BYTE	$08,$C4,$03,$F8
		.BYTE	$08,$D4,$03,$00
		.BYTE	$08,$E4,$03,$08
		.BYTE	$08,$F4,$03,$10
		.BYTE	$16,$C8,$03,$FB
		.BYTE	$16,$D8,$03,$03
		.BYTE	$24,$DA,$03,$03
		.BYTE	$26,$80,$00,$FD
		.BYTE	$26,$90,$00,$05
		.BYTE	$26,$CA,$03,$FB
		.BYTE	$E8,$C0,$03,$F8
		.BYTE	$E8,$D0,$03,$00
		.BYTE	$F8,$C2,$03,$F8
		.BYTE	$F8,$D2,$03,$00
		.BYTE	$F8,$E2,$03,$08
		.BYTE	$F8,$F2,$03,$10
		.BYTE	$00
_sprA07_8C:
		.BYTE	$10
		.BYTE	$06,$C6,$03,$FB
		.BYTE	$08,$C4,$03,$F8
		.BYTE	$08,$D4,$03,$00
		.BYTE	$08,$E4,$03,$08
		.BYTE	$08,$F4,$03,$10
		.BYTE	$0E,$D8,$03,$01
		.BYTE	$15,$DA,$03,$01
		.BYTE	$16,$80,$00,$FB
		.BYTE	$16,$90,$00,$03
		.BYTE	$16,$CA,$03,$F9
		.BYTE	$E8,$C0,$03,$F8
		.BYTE	$E8,$D0,$03,$00
		.BYTE	$F8,$C2,$03,$F8
		.BYTE	$F8,$D2,$03,$00
		.BYTE	$F8,$E2,$03,$08
		.BYTE	$F8,$F2,$03,$10
		.BYTE	$00
_sprA07_8D:
		.BYTE	$0F
		.BYTE	$06,$C6,$03,$FB
		.BYTE	$08,$C4,$03,$F8
		.BYTE	$08,$D4,$03,$00
		.BYTE	$08,$E4,$03,$08
		.BYTE	$08,$F4,$03,$10
		.BYTE	$0B,$80,$00,$F8
		.BYTE	$0B,$90,$00,$00
		.BYTE	$0B,$CA,$03,$F8
		.BYTE	$0B,$DA,$03,$FF
		.BYTE	$E8,$C0,$03,$F8
		.BYTE	$E8,$D0,$03,$00
		.BYTE	$F8,$C2,$03,$F8
		.BYTE	$F8,$D2,$03,$00
		.BYTE	$F8,$E2,$03,$08
		.BYTE	$F8,$F2,$03,$10
		.BYTE	$00
_sprB07_C0:
		.BYTE	$09
		.BYTE	$D6,$EC,$00,$F0
		.BYTE	$D6,$FC,$00,$F8
		.BYTE	$DE,$C8,$00,$F4
		.BYTE	$EA,$D4,$03,$F4
		.BYTE	$EA,$E4,$03,$FC
		.BYTE	$EA,$F4,$03,$04
		.BYTE	$FA,$C6,$03,$04
		.BYTE	$FA,$D6,$03,$F4
		.BYTE	$FA,$E6,$03,$FC
		.BYTE	$00
_sprB07_C1:
		.BYTE	$09
		.BYTE	$DA,$EC,$00,$FA
		.BYTE	$DA,$FC,$00,$02
		.BYTE	$DF,$CC,$00,$F7
		.BYTE	$EA,$D4,$03,$F4
		.BYTE	$EA,$E4,$03,$FC
		.BYTE	$EA,$F4,$03,$04
		.BYTE	$FA,$C6,$03,$04
		.BYTE	$FA,$D6,$03,$F4
		.BYTE	$FA,$E6,$03,$FC
		.BYTE	$00
_sprB07_C2:
		.BYTE	$0A
		.BYTE	$E8,$EC,$00,$07
		.BYTE	$E8,$FC,$00,$0F
		.BYTE	$EA,$D0,$03,$F4
		.BYTE	$EA,$E0,$03,$FC
		.BYTE	$EA,$F0,$03,$04
		.BYTE	$EC,$CA,$00,$01
		.BYTE	$EC,$CA,$00,$F9
		.BYTE	$FA,$C2,$03,$04
		.BYTE	$FA,$D2,$03,$F4
		.BYTE	$FA,$E2,$03,$FC
		.BYTE	$00
_sprB07_C3:
		.BYTE	$0A
		.BYTE	$EA,$D0,$03,$F4
		.BYTE	$EA,$E0,$03,$FC
		.BYTE	$EA,$F0,$03,$04
		.BYTE	$EF,$CC,$40,$FD
		.BYTE	$F0,$DC,$40,$F7
		.BYTE	$FA,$C2,$03,$04
		.BYTE	$FA,$D2,$03,$F4
		.BYTE	$FA,$E2,$03,$FC
		.BYTE	$FA,$EC,$00,$03
		.BYTE	$FA,$FC,$00,$0B
		.BYTE	$00
_sprB07_C4:
		.BYTE	$0A
		.BYTE	$02,$EC,$00,$EF
		.BYTE	$02,$FC,$00,$F7
		.BYTE	$EA,$D4,$03,$F4
		.BYTE	$EA,$E4,$03,$FC
		.BYTE	$EA,$F4,$03,$04
		.BYTE	$F0,$C8,$00,$F3
		.BYTE	$F8,$C8,$00,$F3
		.BYTE	$FA,$C4,$03,$F4
		.BYTE	$FA,$E6,$03,$FC
		.BYTE	$FA,$F6,$03,$04
		.BYTE	$00
_sprB07_C5:
		.BYTE	$0A
		.BYTE	$EA,$D4,$03,$F4
		.BYTE	$EA,$E4,$03,$FC
		.BYTE	$EA,$F4,$03,$04
		.BYTE	$F0,$CC,$00,$E7
		.BYTE	$F0,$DC,$00,$EF
		.BYTE	$FA,$C4,$03,$F4
		.BYTE	$FA,$E6,$03,$FC
		.BYTE	$FA,$EC,$00,$DE
		.BYTE	$FA,$F6,$03,$04
		.BYTE	$FA,$FC,$00,$E6
		.BYTE	$00
_sprB07_C6:
		.BYTE	$0A
		.BYTE	$E8,$EC,$00,$D9
		.BYTE	$E8,$FC,$00,$E1
		.BYTE	$EA,$D0,$03,$F4
		.BYTE	$EA,$E0,$03,$FC
		.BYTE	$EA,$F0,$03,$04
		.BYTE	$EC,$CA,$00,$E6
		.BYTE	$EC,$CA,$00,$EE
		.BYTE	$FA,$C0,$03,$F4
		.BYTE	$FA,$E2,$03,$FC
		.BYTE	$FA,$F2,$03,$04
		.BYTE	$00
_sprB07_C7:
		.BYTE	$09
		.BYTE	$DB,$EC,$00,$E2
		.BYTE	$DB,$FC,$00,$EA
		.BYTE	$DF,$CC,$40,$EF
		.BYTE	$EA,$D0,$03,$F4
		.BYTE	$EA,$E0,$03,$FC
		.BYTE	$EA,$F0,$03,$04
		.BYTE	$FA,$C0,$03,$F4
		.BYTE	$FA,$E2,$03,$FC
		.BYTE	$FA,$F2,$03,$04
		.BYTE	$00
_sprB07_C8:
		.BYTE	$06
		.BYTE	$EA,$D8,$03,$F4
		.BYTE	$EA,$E8,$03,$FC
		.BYTE	$EA,$F8,$03,$04
		.BYTE	$FA,$DA,$03,$F4
		.BYTE	$FA,$EA,$03,$FC
		.BYTE	$FA,$FA,$03,$04
		.BYTE	$00
_sprB07_C9:
		.BYTE	$09
		.BYTE	$02,$EC,$00,$F0
		.BYTE	$02,$FC,$00,$F8
		.BYTE	$EA,$D8,$03,$F4
		.BYTE	$EA,$E8,$03,$FC
		.BYTE	$EA,$F8,$03,$04
		.BYTE	$FA,$DA,$03,$F4
		.BYTE	$FA,$EA,$03,$FC
		.BYTE	$FA,$FA,$03,$04
		.BYTE	$FF,$C8,$00,$F4
		.BYTE	$00
_sprB07_CA:
		.BYTE	$09
		.BYTE	$02,$EC,$00,$F2
		.BYTE	$02,$FC,$00,$FA
		.BYTE	$EA,$D8,$03,$F6
		.BYTE	$EA,$E8,$03,$FE
		.BYTE	$EA,$F8,$03,$06
		.BYTE	$FA,$DA,$03,$F6
		.BYTE	$FA,$EA,$03,$FE
		.BYTE	$FA,$FA,$03,$06
		.BYTE	$FF,$C8,$00,$F6
		.BYTE	$00
