_sprA01_00:
		.BYTE	$04
		.BYTE	$F0,$31,$43,$08
		.BYTE	$00,$33,$43,$08
		.BYTE	$00,$33,$03,$F0
		.BYTE	$F0,$31,$03,$F0
_sprA01_01:
		.BYTE	$02
		.BYTE	$F0,$EF,$83,$00
		.BYTE	$00,$EF,$03,$00
_sprA01_02:
		.BYTE	$06
		.BYTE	$0B,$F9,$43,$00
		.BYTE	$0B,$F9,$43,$F8
		.BYTE	$0B,$F9,$03,$F0
		.BYTE	$F8,$FB,$03,$00
		.BYTE	$F8,$EB,$03,$F8
		.BYTE	$F8,$DB,$03,$F0
_sprA01_03:
		.BYTE	$04
		.BYTE	$0B,$F9,$03,$F8
		.BYTE	$0B,$F9,$03,$F0
		.BYTE	$F8,$DD,$03,$F8
		.BYTE	$F8,$CD,$03,$F0
_sprA01_04:
		.BYTE	$02
		.BYTE	$0B,$F9,$03,$F0
		.BYTE	$F4,$CB,$03,$F1
_sprA01_05:
		.BYTE	$01
		.BYTE	$00,$D9,$03,$FF
_sprA01_06:
		.BYTE	$01
		.BYTE	$00,$E9,$03,$FF
_sprA01_07:
		.BYTE	$02
		.BYTE	$F0,$AF,$40,$F8
		.BYTE	$00,$8B,$40,$F8
_sprA01_08:
		.BYTE	$04
		.BYTE	$00,$43,$02,$08
		.BYTE	$F0,$41,$02,$08
		.BYTE	$F0,$41,$42,$F0
		.BYTE	$00,$43,$42,$F0
_sprA01_09:
		.BYTE	$04
		.BYTE	$00,$23,$02,$08
		.BYTE	$F0,$21,$02,$08
		.BYTE	$00,$33,$02,$F0
		.BYTE	$F0,$31,$02,$F0
_sprA01_0A:
		.BYTE	$04
		.BYTE	$00,$CF,$00,$08
		.BYTE	$00,$CF,$00,$00
		.BYTE	$00,$CF,$00,$F0
		.BYTE	$00,$CF,$00,$F8
_sprA01_0B:
		.BYTE	$02
		.BYTE	$F0,$DD,$00,$00
		.BYTE	$00,$DF,$00,$00
_sprA01_0C:
		.BYTE	$02
		.BYTE	$00,$CF,$00,$08
		.BYTE	$00,$CF,$00,$00
_sprA01_0D:
		.BYTE	$02
		.BYTE	$F0,$DD,$00,$08
		.BYTE	$00,$DF,$00,$08
_sprA01_0E:
		.BYTE	$08
		.BYTE	$F0,$7D,$03,$08
		.BYTE	$F0,$7D,$03,$00
		.BYTE	$F0,$7D,$03,$F8
		.BYTE	$F0,$7D,$03,$F0
		.BYTE	$00,$7F,$03,$F0
		.BYTE	$00,$7F,$03,$08
		.BYTE	$00,$7F,$03,$00
		.BYTE	$00,$7F,$03,$F8
_sprA01_0F:
		.BYTE	$04
		.BYTE	$00,$6F,$03,$08
		.BYTE	$00,$6F,$03,$00
		.BYTE	$00,$6F,$03,$F8
		.BYTE	$00,$6F,$03,$F0
_sprA01_10:
		.BYTE	$04
		.BYTE	$00,$7D,$03,$08
		.BYTE	$00,$7D,$03,$00
		.BYTE	$00,$7D,$03,$F8
		.BYTE	$00,$7D,$03,$F0
_sprA01_11:
		.BYTE	$02
		.BYTE	$F4,$5F,$03,$00
		.BYTE	$00,$5F,$03,$00
_sprA01_12:
		.BYTE	$02
		.BYTE	$F8,$5D,$03,$00
		.BYTE	$00,$5D,$03,$00
_sprA01_13:
		.BYTE	$02
		.BYTE	$FC,$5D,$03,$00
		.BYTE	$00,$5D,$03,$00
_sprA01_14:
		.BYTE	$01
		.BYTE	$00,$6D,$03,$00
_sprA01_15:
		.BYTE	$07
		.BYTE	$00,$0F,$22,$F0
		.BYTE	$00,$1F,$22,$F8
		.BYTE	$00,$3D,$22,$08
		.BYTE	$00,$3F,$22,$00
		.BYTE	$F0,$0D,$22,$F0
		.BYTE	$F0,$1D,$22,$F8
		.BYTE	$F0,$3B,$22,$00
_sprA01_16:
		.BYTE	$07
		.BYTE	$00,$0F,$62,$08
		.BYTE	$00,$1F,$62,$00
		.BYTE	$00,$3D,$62,$F0
		.BYTE	$00,$3F,$62,$F8
		.BYTE	$F0,$0D,$62,$08
		.BYTE	$F0,$1D,$62,$00
		.BYTE	$F0,$3B,$62,$F8
_sprA01_17:
		.BYTE	$10
		.BYTE	$00,$8E,$03,$18
		.BYTE	$00,$8C,$03,$10
		.BYTE	$00,$8A,$03,$08
		.BYTE	$00,$88,$03,$00
		.BYTE	$00,$7E,$03,$F8
		.BYTE	$00,$7C,$03,$F0
		.BYTE	$00,$7A,$03,$E8
		.BYTE	$00,$78,$03,$E0
		.BYTE	$F0,$76,$03,$18
		.BYTE	$F0,$74,$03,$10
		.BYTE	$F0,$72,$03,$08
		.BYTE	$F0,$68,$03,$E0
		.BYTE	$F0,$6A,$03,$E8
		.BYTE	$F0,$6C,$03,$F0
		.BYTE	$F0,$6E,$03,$F8
		.BYTE	$F0,$70,$03,$00
_sprA01_18:
		.BYTE	$10
		.BYTE	$00,$8F,$03,$18
		.BYTE	$00,$8D,$03,$10
		.BYTE	$00,$8B,$03,$08
		.BYTE	$00,$89,$03,$00
		.BYTE	$00,$7F,$03,$F8
		.BYTE	$00,$7D,$03,$F0
		.BYTE	$00,$7B,$03,$E8
		.BYTE	$00,$79,$03,$E0
		.BYTE	$F0,$77,$03,$18
		.BYTE	$F0,$75,$03,$10
		.BYTE	$F0,$73,$03,$08
		.BYTE	$F0,$69,$03,$E0
		.BYTE	$F0,$6B,$03,$E8
		.BYTE	$F0,$6D,$03,$F0
		.BYTE	$F0,$6F,$03,$F8
		.BYTE	$F0,$71,$03,$00
_sprA01_19:
		.BYTE	$02
		.BYTE	$F8,$BD,$00,$00
		.BYTE	$F8,$AD,$00,$F8
_sprA01_1A:
		.BYTE	$02
		.BYTE	$F8,$BD,$01,$00
		.BYTE	$F8,$AD,$01,$F8
_sprA01_1B:
		.BYTE	$02
		.BYTE	$F8,$BB,$00,$00
		.BYTE	$F8,$AB,$00,$F8
_sprA01_1C:
		.BYTE	$01
		.BYTE	$F8,$BF,$00,$FC
_sprA01_1D:
		.BYTE	$01
		.BYTE	$F8,$AF,$00,$FC
_sprA01_1E:
		.BYTE	$01
		.BYTE	$F8,$BF,$40,$FC
