
_sprA08_04:
		.BYTE	$02
		.BYTE	$F8,$CA,$02,$F8
		.BYTE	$F8,$DA,$02,$00
		.BYTE	$00
_sprA08_05:
		.BYTE	$02
		.BYTE	$F8,$CC,$02,$F8
		.BYTE	$F8,$DC,$02,$00
		.BYTE	$00
_sprA08_06:
		.BYTE	$02
		.BYTE	$F8,$CC,$42,$00
		.BYTE	$F8,$DC,$42,$F8
		.BYTE	$00
_sprA08_07:
		.BYTE	$03
		.BYTE	$00,$58,$00,$F8
		.BYTE	$F7,$58,$00,$FB
		.BYTE	$FD,$58,$00,$00
		.BYTE	$00
_sprA08_08:
		.BYTE	$03
		.BYTE	$02,$48,$00,$FB
		.BYTE	$FC,$48,$00,$FE
		.BYTE	$FD,$48,$00,$FA
		.BYTE	$00
_sprA08_09:
		.BYTE	$08
_sprA08_09_A:
		.BYTE	$10,$3E,$00,$00
		.BYTE	$10,$3E,$40,$F8
		.BYTE	$E8,$A4,$02,$FC
		.BYTE	$E8,$B4,$02,$04
		.BYTE	$E8,$B4,$42,$F4
		.BYTE	$F8,$A6,$02,$FC
		.BYTE	$F8,$B6,$02,$04
		.BYTE	$F8,$B6,$42,$F4
		.BYTE	$00
_sprA08_0A:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$46,$42
		.BYTE	$E8,$8C,$04
		.BYTE	$E8,$9C,$FC
		.BYTE	$E8,$AC,$F4
		.BYTE	$F8,$8E,$04
		.BYTE	$F8,$9E,$FC
		.BYTE	$F8,$AE,$F4
		.BYTE	$00
_sprA08_0B:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$06
		.BYTE	$E8,$80,$02,$F4
		.BYTE	$E8,$80,$42,$04
		.BYTE	$E8,$90,$02,$FC
		.BYTE	$F8,$82,$02,$F4
		.BYTE	$F8,$82,$42,$04
		.BYTE	$F8,$92,$02,$FC
		.BYTE	$00
_sprA08_0C:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$46,$02
		.BYTE	$E8,$8C,$F4
		.BYTE	$E8,$9C,$FC
		.BYTE	$E8,$AC,$04
		.BYTE	$F8,$8E,$F4
		.BYTE	$F8,$9E,$FC
		.BYTE	$F8,$AE,$04
		.BYTE	$00
_sprA08_0D:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$06
		.BYTE	$E8,$84,$02,$F4
		.BYTE	$E8,$84,$42,$04
		.BYTE	$E8,$94,$02,$FC
		.BYTE	$F8,$86,$02,$F4
		.BYTE	$F8,$86,$42,$04
		.BYTE	$F8,$96,$02,$FC
		.BYTE	$00
_sprA08_0E:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$06
_sprA08_0E_B:
		.BYTE	$E8,$88,$42,$04
		.BYTE	$E8,$98,$42,$FC
		.BYTE	$E8,$A8,$42,$F4
		.BYTE	$F8,$8A,$42,$04
		.BYTE	$F8,$9A,$42,$FC
		.BYTE	$F8,$AA,$42,$F4
		.BYTE	$00
_sprA08_0F:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$06
		.BYTE	$E8,$A0,$02,$FC
		.BYTE	$E8,$B0,$02,$04
		.BYTE	$E8,$B0,$42,$F4
		.BYTE	$F8,$A2,$02,$FC
		.BYTE	$F8,$B2,$02,$04
		.BYTE	$F8,$B2,$42,$F4
		.BYTE	$00
_sprA08_10:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$06
_sprA08_10_B:
		.BYTE	$E8,$88,$02,$F4
		.BYTE	$E8,$98,$02,$FC
		.BYTE	$E8,$A8,$02,$04
		.BYTE	$F8,$8A,$02,$F4
		.BYTE	$F8,$9A,$02,$FC
		.BYTE	$F8,$AA,$02,$04
		.BYTE	$00
_sprA08_11:
		.BYTE	$08
_sprA08_11_A:
		.BYTE	$10,$3E,$00,$02
		.BYTE	$10,$3E,$40,$FA
		.BYTE	$E8,$A4,$02,$FE
		.BYTE	$E8,$B4,$02,$06
		.BYTE	$E8,$B4,$42,$F6
		.BYTE	$F8,$A6,$02,$FE
		.BYTE	$F8,$B6,$02,$06
		.BYTE	$F8,$B6,$42,$F6
		.BYTE	$00
_sprA08_12:
		.BYTE	$82
		.WORD	_sprA08_11_A
		.BYTE	$46,$42
		.BYTE	$E8,$8C,$06
		.BYTE	$E8,$9C,$FE
		.BYTE	$E8,$AC,$F6
		.BYTE	$F8,$8E,$06
		.BYTE	$F8,$9E,$FE
		.BYTE	$F8,$AE,$F6
		.BYTE	$00
_sprA08_13:
		.BYTE	$82
		.WORD	_sprA08_11_A
		.BYTE	$06
		.BYTE	$E8,$80,$02,$F6
		.BYTE	$E8,$80,$42,$06
		.BYTE	$E8,$90,$02,$FE
		.BYTE	$F8,$82,$02,$F6
		.BYTE	$F8,$82,$42,$06
		.BYTE	$F8,$92,$02,$FE
		.BYTE	$00
_sprA08_14:
		.BYTE	$82
		.WORD	_sprA08_11_A
		.BYTE	$46,$02
		.BYTE	$E8,$8C,$F6
		.BYTE	$E8,$9C,$FE
		.BYTE	$E8,$AC,$06
		.BYTE	$F8,$8E,$F6
		.BYTE	$F8,$9E,$FE
		.BYTE	$F8,$AE,$06
		.BYTE	$00
_sprA08_15:
		.BYTE	$05
_sprA08_15_A:
		.BYTE	$FF,$CE,$02,$F2
		.BYTE	$FF,$DE,$02,$FA
		.BYTE	$EF,$88,$02,$EE
		.BYTE	$EF,$98,$02,$F6
		.BYTE	$F0,$A8,$02,$FE
		.BYTE	$00
_sprA08_16:
		.BYTE	$82
		.WORD	_sprA08_15_A
		.BYTE	$03
		.BYTE	$F6,$88,$02,$EE
		.BYTE	$F7,$98,$02,$F6
		.BYTE	$F8,$A8,$02,$FE
		.BYTE	$00
_sprA08_17:
		.BYTE	$05
_sprA08_17_A:
		.BYTE	$FF,$CE,$42,$07
		.BYTE	$FF,$DE,$42,$FF
		.BYTE	$EF,$88,$42,$0B
		.BYTE	$EF,$98,$42,$03
		.BYTE	$F0,$A8,$42,$FB
		.BYTE	$00
_sprA08_18:
		.BYTE	$82
		.WORD	_sprA08_17_A
		.BYTE	$03
		.BYTE	$F6,$88,$42,$0B
		.BYTE	$F7,$98,$42,$03
		.BYTE	$F8,$A8,$42,$FB
		.BYTE	$00
_sprA08_19:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$06
_sprA08_19_B:
		.BYTE	$08,$D4,$03,$F8
		.BYTE	$08,$D4,$43,$00
		.BYTE	$E8,$BE,$03,$00
		.BYTE	$E8,$D6,$03,$F8
		.BYTE	$F8,$D8,$03,$F8
		.BYTE	$F8,$D8,$43,$00
		.BYTE	$00
_sprA08_1A:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$45,$43
		.BYTE	$08,$F4,$F8
		.BYTE	$E8,$E0,$00
		.BYTE	$E8,$F0,$F8
		.BYTE	$F8,$E2,$00
		.BYTE	$F8,$F2,$F8
		.BYTE	$00
_sprA08_1B:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$82
		.WORD	_sprA08_19_B
		.BYTE	$04
		.BYTE	$E8,$BA,$03,$00
		.BYTE	$E8,$D0,$03,$F8
		.BYTE	$F8,$D2,$03,$F8
		.BYTE	$F8,$D2,$43,$00
		.BYTE	$00
_sprA08_1C:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$45,$03
		.BYTE	$08,$F4,$00
		.BYTE	$E8,$E0,$F8
		.BYTE	$E8,$F0,$00
		.BYTE	$F8,$E2,$F8
		.BYTE	$F8,$F2,$00
		.BYTE	$00
_sprA08_1D:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$06
_sprA08_1D_B:
		.BYTE	$08,$C4,$03,$F8
		.BYTE	$08,$C4,$43,$00
		.BYTE	$E8,$BC,$03,$00
		.BYTE	$E8,$C6,$03,$F8
		.BYTE	$F8,$C8,$03,$F8
		.BYTE	$F8,$C8,$43,$00
		.BYTE	$00
_sprA08_1E:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$45,$43
		.BYTE	$08,$E4,$F8
		.BYTE	$E8,$E6,$00
		.BYTE	$E8,$F6,$F8
		.BYTE	$F8,$E8,$00
		.BYTE	$F8,$F8,$F8
		.BYTE	$00
_sprA08_1F:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$82
		.WORD	_sprA08_1D_B
		.BYTE	$04
		.BYTE	$E8,$B8,$03,$00
		.BYTE	$E8,$C0,$03,$F8
		.BYTE	$F8,$C2,$03,$F8
		.BYTE	$F8,$C2,$43,$00
		.BYTE	$00
_sprA08_20:
		.BYTE	$82
		.WORD	_sprA08_09_A
		.BYTE	$45,$03
		.BYTE	$08,$E4,$00
		.BYTE	$E8,$E6,$F8
		.BYTE	$E8,$F6,$00
		.BYTE	$F8,$E8,$F8
		.BYTE	$F8,$F8,$00
		.BYTE	$00
_sprA08_21:
		.BYTE	$82
		.WORD	_sprA08_11_A
		.BYTE	$06
_sprA08_21_B:
		.BYTE	$08,$D4,$03,$FA
		.BYTE	$08,$D4,$43,$02
		.BYTE	$E8,$BE,$03,$02
		.BYTE	$E8,$D6,$03,$FA
		.BYTE	$F8,$D8,$03,$FA
		.BYTE	$F8,$D8,$43,$02
		.BYTE	$00
_sprA08_22:
		.BYTE	$82
		.WORD	_sprA08_11_A
		.BYTE	$45,$43
		.BYTE	$08,$F4,$FA
		.BYTE	$E8,$E0,$02
		.BYTE	$E8,$F0,$FA
		.BYTE	$F8,$E2,$02
		.BYTE	$F8,$F2,$FA
		.BYTE	$00
_sprA08_23:
		.BYTE	$82
		.WORD	_sprA08_11_A
		.BYTE	$82
		.WORD	_sprA08_21_B
		.BYTE	$04
		.BYTE	$E8,$BA,$03,$02
		.BYTE	$E8,$D0,$03,$FA
		.BYTE	$F8,$D2,$03,$FA
		.BYTE	$F8,$D2,$43,$02
		.BYTE	$00
_sprA08_24:
		.BYTE	$82
		.WORD	_sprA08_11_A
		.BYTE	$45,$03
		.BYTE	$08,$F4,$02
		.BYTE	$E8,$E0,$FA
		.BYTE	$E8,$F0,$02
		.BYTE	$F8,$E2,$FA
		.BYTE	$F8,$F2,$02
		.BYTE	$00
_sprA08_25:
		.BYTE	$45,$03
		.BYTE	$E6,$E6,$F6
		.BYTE	$E6,$F6,$FE
		.BYTE	$F6,$E8,$F5
		.BYTE	$F6,$F8,$FD
		.BYTE	$FF,$FA,$FA
		.BYTE	$00
_sprA08_26:
		.BYTE	$03
		.BYTE	$F4,$F6,$03,$FF
		.BYTE	$F6,$E6,$03,$F7
		.BYTE	$FF,$FA,$03,$FA
		.BYTE	$00
_sprA08_27:
		.BYTE	$45,$43
		.BYTE	$E6,$E6,$03
		.BYTE	$E6,$F6,$FB
		.BYTE	$F6,$E8,$04
		.BYTE	$F6,$F8,$FC
		.BYTE	$FF,$FA,$FF
		.BYTE	$00
_sprA08_28:
		.BYTE	$03
		.BYTE	$F4,$F6,$43,$FA
		.BYTE	$F6,$E6,$43,$02
		.BYTE	$FF,$FA,$43,$FF
		.BYTE	$00
_sprA08_29:
		.BYTE	$0B
_sprA08_29_A:
		.BYTE	$08,$3E,$03,$00
		.BYTE	$08,$3E,$43,$F8
		.BYTE	$E7,$E3,$00,$F8
		.BYTE	$E7,$E3,$40,$00
		.BYTE	$00,$E2,$02,$F8
		.BYTE	$00,$E2,$42,$00
		.BYTE	$F0,$E0,$02,$F8
		.BYTE	$F0,$E0,$42,$00
		.BYTE	$FD,$C7,$00,$FA
		.BYTE	$FD,$D7,$00,$02
		.BYTE	$FD,$E7,$00,$0A
		.BYTE	$00
_sprA08_2A:
		.BYTE	$84
		.WORD	_sprA08_29_A
		.BYTE	$07
_sprA08_2A_B:
		.BYTE	$01,$E2,$02,$F8
		.BYTE	$01,$E2,$42,$00
		.BYTE	$F1,$F0,$02,$F8
		.BYTE	$F1,$F0,$42,$00
		.BYTE	$FF,$C7,$00,$FA
		.BYTE	$FF,$D7,$00,$02
		.BYTE	$FF,$E7,$00,$0A
		.BYTE	$00
_sprA08_2B:
		.BYTE	$84
		.WORD	_sprA08_2A_B
		.BYTE	$82
		.WORD	_sprA08_29_A
		.BYTE	$05
		.BYTE	$E8,$E3,$00,$F8
		.BYTE	$E8,$E3,$40,$00
		.BYTE	$FE,$C7,$00,$FA
		.BYTE	$FE,$D7,$00,$02
		.BYTE	$FE,$E7,$00,$0A
		.BYTE	$00
_sprA08_2C:
		.BYTE	$0A
_sprA08_2C_A:
		.BYTE	$00,$C4,$42,$00
		.BYTE	$00,$D4,$42,$F8
_sprA08_2C_B:
		.BYTE	$06,$3E,$03,$00
		.BYTE	$06,$3E,$43,$F8
		.BYTE	$E8,$C5,$00,$F9
		.BYTE	$E8,$D5,$00,$01
		.BYTE	$F0,$C2,$42,$00
		.BYTE	$F0,$D2,$42,$F8
		.BYTE	$FD,$E5,$00,$FA
		.BYTE	$FD,$F5,$00,$02
		.BYTE	$00
_sprA08_2D:
		.BYTE	$87
		.WORD	_sprA08_2C_A
		.BYTE	$04
		.BYTE	$F0,$D2,$42,$F8
		.BYTE	$F8,$C7,$00,$FA
		.BYTE	$F8,$D7,$00,$02
		.BYTE	$F8,$E7,$00,$0A
		.BYTE	$00
_sprA08_2E:
		.BYTE	$82
		.WORD	_sprA08_2C_B
		.BYTE	$07
_sprA08_2E_B:
		.BYTE	$EA,$F3,$00,$F8
		.BYTE	$EA,$F3,$40,$00
		.BYTE	$EF,$F2,$02,$F8
		.BYTE	$EF,$F2,$42,$00
		.BYTE	$F1,$F5,$80,$05
		.BYTE	$FF,$F4,$02,$F8
		.BYTE	$FF,$F4,$42,$00
		.BYTE	$00
_sprA08_2F:
		.BYTE	$82
		.WORD	_sprA08_2C_B
		.BYTE	$82
		.WORD	_sprA08_2E_B
		.BYTE	$05
		.BYTE	$E6,$F7,$00,$FA
		.BYTE	$EE,$F2,$02,$F8
		.BYTE	$EE,$F2,$42,$00
		.BYTE	$FE,$F4,$02,$F8
		.BYTE	$FE,$F4,$42,$00
		.BYTE	$00
_sprA08_30:
		.BYTE	$82
		.WORD	_sprA08_2C_B
		.BYTE	$07
		.BYTE	$E9,$F3,$00,$F8
		.BYTE	$E9,$F3,$40,$00
		.BYTE	$ED,$F2,$02,$F8
		.BYTE	$ED,$F2,$42,$00
		.BYTE	$ED,$F5,$C0,$F0
		.BYTE	$FD,$F4,$02,$F8
		.BYTE	$FD,$F4,$42,$00
		.BYTE	$00
_sprA08_31:
		.BYTE	$0B
		.BYTE	$00,$E2,$02,$FA
		.BYTE	$00,$E2,$42,$02
		.BYTE	$08,$3E,$03,$02
		.BYTE	$08,$3E,$43,$FA
		.BYTE	$E7,$E3,$00,$FA
		.BYTE	$E7,$E3,$40,$02
		.BYTE	$F0,$E0,$02,$FA
		.BYTE	$F0,$E0,$42,$02
		.BYTE	$FD,$C7,$00,$FC
		.BYTE	$FD,$D7,$00,$04
		.BYTE	$FD,$E7,$00,$0C
		.BYTE	$00
_sprA08_32:
		.BYTE	$03
		.BYTE	$00,$C6,$02,$F8
		.BYTE	$F0,$D6,$02,$F2
		.BYTE	$F0,$E6,$02,$FA
		.BYTE	$00
_sprA08_33:
		.BYTE	$02
		.BYTE	$F8,$E4,$02,$F0
		.BYTE	$F8,$F6,$02,$F8
		.BYTE	$00
_sprA08_34:
		.BYTE	$03
		.BYTE	$00,$C6,$42,$00
		.BYTE	$F0,$D6,$42,$08
		.BYTE	$F0,$E6,$42,$00
		.BYTE	$00
_sprA08_35:
		.BYTE	$02
		.BYTE	$F8,$E4,$42,$08
		.BYTE	$F8,$F6,$42,$00
		.BYTE	$00
_sprA08_36:
		.BYTE	$01
		.BYTE	$F8,$C0,$01,$FC
		.BYTE	$00
_sprA08_37:
		.BYTE	$01
		.BYTE	$F8,$D0,$01,$FC
		.BYTE	$00
_sprA08_38:
		.BYTE	$01
		.BYTE	$F8,$C0,$41,$FC
		.BYTE	$00
_sprA08_39:
		.BYTE	$01
		.BYTE	$F8,$C8,$01,$FC
		.BYTE	$00
_sprA08_3A:
		.BYTE	$01
		.BYTE	$F8,$C8,$41,$FC
		.BYTE	$00
_sprA08_3B:
		.BYTE	$03
_sprA08_3B_A:
		.BYTE	$08,$82,$00,$F4
		.BYTE	$08,$90,$00,$04
		.BYTE	$08,$80,$00,$FC
		.BYTE	$00
_sprA08_3C:
		.BYTE	$82
		.WORD	_sprA08_3B_A
		.BYTE	$01
		.BYTE	$08,$98,$03,$FC
		.BYTE	$00
_sprA08_3D:
		.BYTE	$03
		.BYTE	$08,$8A,$43,$04
		.BYTE	$08,$90,$43,$F4
		.BYTE	$08,$9A,$43,$FC
		.BYTE	$00
_sprA08_3E:
		.BYTE	$82
		.WORD	_sprA08_3B_A
		.BYTE	$01
		.BYTE	$08,$88,$03,$FC
		.BYTE	$00
_sprA08_3F:
		.BYTE	$03
		.BYTE	$08,$8A,$03,$F4
		.BYTE	$08,$90,$00,$04
		.BYTE	$08,$9A,$03,$FC
		.BYTE	$00
_sprA08_40:
		.BYTE	$83
		.WORD	_sprA08_3B_A
		.BYTE	$06
		.BYTE	$EE,$A6,$03,$FC
		.BYTE	$FE,$A4,$03,$EC
		.BYTE	$FE,$A4,$43,$0C
		.BYTE	$FE,$B4,$03,$F4
		.BYTE	$FE,$B4,$43,$04
		.BYTE	$FE,$C4,$03,$FC
		.BYTE	$00
_sprA08_41:
		.BYTE	$48,$43
		.BYTE	$08,$80,$00
		.BYTE	$08,$80,$F8
		.BYTE	$EE,$A8,$04
		.BYTE	$EE,$B8,$FC
		.BYTE	$FE,$C8,$0C
		.BYTE	$FE,$D8,$04
		.BYTE	$FE,$E8,$FC
		.BYTE	$FE,$F8,$F4
		.BYTE	$00
_sprA08_42:
		.BYTE	$47,$03
		.BYTE	$08,$80,$FC
		.BYTE	$08,$82,$F4
		.BYTE	$08,$90,$04
		.BYTE	$EE,$A2,$FC
		.BYTE	$FE,$A0,$EC
		.BYTE	$FE,$B0,$F4
		.BYTE	$FE,$C0,$FC
		.BYTE	$02
		.BYTE	$FE,$A0,$43,$0C
		.BYTE	$FE,$B0,$43,$04
		.BYTE	$00
_sprA08_43:
		.BYTE	$48,$03
		.BYTE	$08,$80,$00
		.BYTE	$08,$80,$F8
		.BYTE	$EE,$A8,$F4
		.BYTE	$EE,$B8,$FC
		.BYTE	$FE,$C8,$EC
		.BYTE	$FE,$D8,$F4
		.BYTE	$FE,$E8,$FC
		.BYTE	$FE,$F8,$04
		.BYTE	$00
_sprA08_44:
		.BYTE	$47,$03
		.BYTE	$00,$86,$04
		.BYTE	$00,$B6,$F4
		.BYTE	$00,$C6,$FC
		.BYTE	$E0,$A6,$FC
		.BYTE	$F0,$A4,$EC
		.BYTE	$F0,$B4,$F4
		.BYTE	$F0,$C4,$FC
		.BYTE	$02
		.BYTE	$F0,$A4,$43,$0C
		.BYTE	$F0,$B4,$43,$04
		.BYTE	$00
_sprA08_45:
		.BYTE	$4A,$43
		.BYTE	$00,$CA,$0C
		.BYTE	$00,$DA,$04
		.BYTE	$00,$EA,$FC
		.BYTE	$00,$FA,$F4
		.BYTE	$E0,$A8,$04
		.BYTE	$E0,$B8,$FC
		.BYTE	$F0,$C8,$0C
		.BYTE	$F0,$D8,$04
		.BYTE	$F0,$E8,$FC
		.BYTE	$F0,$F8,$F4
		.BYTE	$00
_sprA08_46:
		.BYTE	$47,$03
		.BYTE	$00,$84,$04
		.BYTE	$00,$B2,$F4
		.BYTE	$00,$C2,$FC
		.BYTE	$E0,$A2,$FC
		.BYTE	$F0,$A0,$EC
		.BYTE	$F0,$B0,$F4
		.BYTE	$F0,$C0,$FC
		.BYTE	$02
		.BYTE	$F0,$A0,$43,$0C
		.BYTE	$F0,$B0,$43,$04
		.BYTE	$00
_sprA08_47:
		.BYTE	$4A,$03
		.BYTE	$00,$CA,$F0
		.BYTE	$00,$DA,$F8
		.BYTE	$00,$EA,$00
		.BYTE	$00,$FA,$08
		.BYTE	$E0,$A8,$F8
		.BYTE	$E0,$B8,$00
		.BYTE	$F0,$C8,$F0
		.BYTE	$F0,$D8,$F8
		.BYTE	$F0,$E8,$00
		.BYTE	$F0,$F8,$08
		.BYTE	$00
_sprA08_48:
		.BYTE	$47,$03
		.BYTE	$00,$96,$F4
		.BYTE	$00,$D6,$FC
		.BYTE	$00,$E6,$04
		.BYTE	$E0,$F6,$FC
		.BYTE	$F0,$D4,$FC
		.BYTE	$F0,$E4,$04
		.BYTE	$F0,$F4,$0C
		.BYTE	$02
		.BYTE	$F0,$E4,$43,$F4
		.BYTE	$F0,$F4,$43,$EC
		.BYTE	$00
_sprA08_49:
		.BYTE	$49,$43
		.BYTE	$00,$CE,$04
		.BYTE	$00,$DE,$FC
		.BYTE	$00,$EE,$F4
		.BYTE	$E0,$AA,$04
		.BYTE	$E0,$BA,$FC
		.BYTE	$F0,$BC,$0C
		.BYTE	$F0,$CC,$04
		.BYTE	$F0,$DC,$FC
		.BYTE	$F0,$EC,$F4
		.BYTE	$00
_sprA08_4A:
		.BYTE	$47,$03
		.BYTE	$00,$94,$F4
		.BYTE	$00,$D2,$FC
		.BYTE	$00,$E2,$04
		.BYTE	$E0,$F2,$FC
		.BYTE	$F0,$D0,$FC
		.BYTE	$F0,$E0,$04
		.BYTE	$F0,$F0,$0C
		.BYTE	$02
		.BYTE	$F0,$E0,$43,$F4
		.BYTE	$F0,$F0,$43,$EC
		.BYTE	$00
_sprA08_4B:
		.BYTE	$49,$03
		.BYTE	$00,$CE,$F8
		.BYTE	$00,$DE,$00
		.BYTE	$00,$EE,$08
		.BYTE	$E0,$AA,$F8
		.BYTE	$E0,$BA,$00
		.BYTE	$F0,$BC,$F0
		.BYTE	$F0,$CC,$F8
		.BYTE	$F0,$DC,$00
		.BYTE	$F0,$EC,$08
		.BYTE	$00
_sprA08_4C:
		.BYTE	$47,$03
		.BYTE	$00,$86,$06
		.BYTE	$00,$B6,$F6
		.BYTE	$00,$C6,$FE
		.BYTE	$E0,$A6,$FE
		.BYTE	$F0,$A4,$EE
		.BYTE	$F0,$B4,$F6
		.BYTE	$F0,$C4,$FE
		.BYTE	$02
		.BYTE	$F0,$A4,$43,$0E
		.BYTE	$F0,$B4,$43,$06
		.BYTE	$00
_sprA08_4D:
		.BYTE	$4A,$43
		.BYTE	$00,$CA,$0E
		.BYTE	$00,$DA,$06
		.BYTE	$00,$EA,$FE
		.BYTE	$00,$FA,$F6
		.BYTE	$E0,$A8,$06
		.BYTE	$E0,$B8,$FE
		.BYTE	$F0,$C8,$0E
		.BYTE	$F0,$D8,$06
		.BYTE	$F0,$E8,$FE
		.BYTE	$F0,$F8,$F6
		.BYTE	$00
_sprA08_4E:
		.BYTE	$47,$03
		.BYTE	$00,$84,$07
		.BYTE	$00,$B2,$F7
		.BYTE	$00,$C2,$FF
		.BYTE	$E0,$A2,$FF
		.BYTE	$F0,$A0,$EF
		.BYTE	$F0,$B0,$F7
		.BYTE	$F0,$C0,$FF
		.BYTE	$02
		.BYTE	$F0,$A0,$43,$0F
		.BYTE	$F0,$B0,$43,$07
		.BYTE	$00
_sprA08_4F:
		.BYTE	$4A,$03
		.BYTE	$00,$CA,$F2
		.BYTE	$00,$DA,$FA
		.BYTE	$00,$EA,$02
		.BYTE	$00,$FA,$0A
		.BYTE	$E0,$A8,$FA
		.BYTE	$E0,$B8,$02
		.BYTE	$F0,$C8,$F2
		.BYTE	$F0,$D8,$FA
		.BYTE	$F0,$E8,$02
		.BYTE	$F0,$F8,$0A
		.BYTE	$00
_sprA08_50:
		.BYTE	$4A,$03
		.BYTE	$DF,$AA,$F2
		.BYTE	$DF,$BA,$FA
		.BYTE	$EF,$C8,$EA
		.BYTE	$EF,$D8,$F2
		.BYTE	$EF,$E8,$FA
		.BYTE	$EF,$F8,$02
		.BYTE	$FF,$9E,$F2
		.BYTE	$FF,$AE,$FA
		.BYTE	$FF,$BE,$02
		.BYTE	$FF,$CA,$EA
		.BYTE	$00
_sprA08_51:
		.BYTE	$44,$03
		.BYTE	$07,$8E,$F9
		.BYTE	$07,$BE,$01
		.BYTE	$F7,$C8,$F9
		.BYTE	$F7,$F8,$01
		.BYTE	$00
_sprA08_52:
		.BYTE	$4A,$43
		.BYTE	$DF,$AA,$07
		.BYTE	$DF,$BA,$FF
		.BYTE	$EF,$C8,$0F
		.BYTE	$EF,$D8,$07
		.BYTE	$EF,$E8,$FF
		.BYTE	$EF,$F8,$F7
		.BYTE	$FF,$9E,$07
		.BYTE	$FF,$AE,$FF
		.BYTE	$FF,$BE,$F7
		.BYTE	$FF,$CA,$0F
		.BYTE	$00
_sprA08_53:
		.BYTE	$44,$43
		.BYTE	$06,$8E,$02
		.BYTE	$06,$BE,$FA
		.BYTE	$F6,$C8,$02
		.BYTE	$F6,$F8,$FA
		.BYTE	$00
_sprA08_54:
		.BYTE	$03
		.BYTE	$0E,$92,$01,$FC
		.BYTE	$E3,$92,$01,$FC
		.BYTE	$F9,$92,$41,$FC
		.BYTE	$00
_sprA08_55:
		.BYTE	$03
		.BYTE	$04,$92,$01,$FC
		.BYTE	$D8,$92,$41,$FC
		.BYTE	$EE,$92,$41,$FC
		.BYTE	$00
_sprA08_56:
		.BYTE	$03
		.BYTE	$F2,$92,$01,$0D
		.BYTE	$F5,$92,$41,$F7
		.BYTE	$F8,$92,$41,$E1
		.BYTE	$00
_sprA08_57:
		.BYTE	$03
		.BYTE	$F0,$92,$41,$18
		.BYTE	$F3,$92,$01,$02
		.BYTE	$F7,$92,$41,$EC
		.BYTE	$00
_sprA08_58:
		.BYTE	$03
		.BYTE	$F0,$92,$01,$E0
		.BYTE	$F3,$92,$41,$F6
		.BYTE	$F7,$92,$01,$0C
		.BYTE	$00
_sprA08_59:
		.BYTE	$03
		.BYTE	$F2,$92,$41,$EB
		.BYTE	$F5,$92,$01,$01
		.BYTE	$F8,$92,$01,$18
		.BYTE	$00
_sprA08_5A:
		.BYTE	$C4,$01
		.WORD	_sprA08_6A_A
		.BYTE	$C6,$01
		.WORD	_sprA08_0E_B
		.BYTE	$00
_sprA08_5B:
		.BYTE	$CC,$01
		.WORD	_sprA08_6B_A
		.BYTE	$00
_sprA08_5C:
		.BYTE	$C4,$01
		.WORD	_sprA08_6C_A
		.BYTE	$C6,$01
		.WORD	_sprA08_10_B
		.BYTE	$00
_sprA08_5D:
		.BYTE	$CC,$01
		.WORD	_sprA08_6D_A
		.BYTE	$00
_sprA08_5E:
		.BYTE	$82
		.WORD	_sprA08_5F_A
		.BYTE	$48,$43
		.BYTE	$07,$8C,$00
		.BYTE	$07,$BC,$F8
		.BYTE	$E7,$88,$04
		.BYTE	$E7,$98,$FC
		.BYTE	$E7,$A8,$F4
		.BYTE	$F7,$8A,$04
		.BYTE	$F7,$9A,$FC
		.BYTE	$F7,$AA,$F4
		.BYTE	$00
_sprA08_5F:
		.BYTE	$0C
_sprA08_5F_A:
		.BYTE	$07,$9E,$03,$08
		.BYTE	$07,$9E,$43,$F0
		.BYTE	$07,$8E,$03,$00
		.BYTE	$07,$8E,$43,$F8
		.BYTE	$E7,$80,$03,$F0
		.BYTE	$E7,$80,$43,$08
		.BYTE	$E7,$90,$03,$F8
		.BYTE	$E7,$90,$43,$00
		.BYTE	$F7,$82,$03,$F0
		.BYTE	$F7,$82,$43,$08
		.BYTE	$F7,$92,$03,$F8
		.BYTE	$F7,$92,$43,$00
		.BYTE	$00
_sprA08_60:
		.BYTE	$82
		.WORD	_sprA08_5F_A
		.BYTE	$48,$03
		.BYTE	$07,$8C,$F8
		.BYTE	$07,$BC,$00
		.BYTE	$E7,$88,$F4
		.BYTE	$E7,$98,$FC
		.BYTE	$E7,$A8,$04
		.BYTE	$F7,$8A,$F4
		.BYTE	$F7,$9A,$FC
		.BYTE	$F7,$AA,$04
		.BYTE	$00
_sprA08_61:
		.BYTE	$84
		.WORD	_sprA08_5F_A
		.BYTE	$08
		.BYTE	$E7,$A0,$03,$00
		.BYTE	$E7,$A0,$43,$F8
		.BYTE	$E7,$B0,$03,$08
		.BYTE	$E7,$B0,$43,$F0
		.BYTE	$F7,$A2,$03,$00
		.BYTE	$F7,$A2,$43,$F8
		.BYTE	$F7,$B2,$03,$08
		.BYTE	$F7,$B2,$43,$F0
		.BYTE	$00
_sprA08_62:
		.BYTE	$C2,$01
		.WORD	_sprA08_6A_B
		.BYTE	$48,$43
		.BYTE	$08,$AC,$00
		.BYTE	$08,$BC,$F8
		.BYTE	$E8,$88,$03
		.BYTE	$E8,$98,$FB
		.BYTE	$E8,$A8,$F3
		.BYTE	$F8,$8A,$03
		.BYTE	$F8,$9A,$FB
		.BYTE	$F8,$AA,$F3
		.BYTE	$00
_sprA08_63:
		.BYTE	$C2,$01
		.WORD	_sprA08_6A_B
		.BYTE	$02
		.BYTE	$08,$AE,$03,$F8
		.BYTE	$08,$BE,$03,$00
		.BYTE	$C8,$01
		.WORD	_sprA08_6B_B
		.BYTE	$00
_sprA08_64:
		.BYTE	$C2,$01
		.WORD	_sprA08_6A_B
		.BYTE	$48,$03
		.BYTE	$08,$AC,$F8
		.BYTE	$08,$BC,$00
		.BYTE	$E8,$88,$F5
		.BYTE	$E8,$98,$FD
		.BYTE	$E8,$A8,$05
		.BYTE	$F8,$8A,$F5
		.BYTE	$F8,$9A,$FD
		.BYTE	$F8,$AA,$05
		.BYTE	$00
_sprA08_65:
		.BYTE	$C2,$01
		.WORD	_sprA08_6A_B
		.BYTE	$01
		.BYTE	$E8,$A0,$03,$00
		.BYTE	$C7,$01
		.WORD	_sprA08_6D_B
		.BYTE	$02
		.BYTE	$08,$B8,$03,$F8
		.BYTE	$08,$BA,$03,$00
		.BYTE	$00
_sprA08_66:
		.BYTE	$CA,$01
		.WORD	_sprA08_6E_A
		.BYTE	$00
_sprA08_67:
		.BYTE	$CC,$01
		.WORD	_sprA08_6F_A
		.BYTE	$00
_sprA08_68:
		.BYTE	$CA,$01
		.WORD	_sprA08_70_A
		.BYTE	$00
_sprA08_69:
		.BYTE	$CC,$01
		.WORD	_sprA08_71_A
		.BYTE	$00
_sprA08_6A:
		.BYTE	$04
_sprA08_6A_A:
		.BYTE	$08,$8C,$42,$00
		.BYTE	$08,$9C,$42,$F8
_sprA08_6A_B:
		.BYTE	$08,$9E,$02,$08
		.BYTE	$08,$9E,$42,$F0
		.BYTE	$86
		.WORD	_sprA08_0E_B
		.BYTE	$00
_sprA08_6B:
		.BYTE	$0C
_sprA08_6B_A:
		.BYTE	$08,$84,$02,$F0
		.BYTE	$08,$84,$42,$08
		.BYTE	$08,$94,$02,$F8
		.BYTE	$08,$94,$42,$00
_sprA08_6B_B:
		.BYTE	$E8,$80,$02,$F0
		.BYTE	$E8,$80,$42,$08
		.BYTE	$E8,$90,$02,$F8
		.BYTE	$E8,$90,$42,$00
		.BYTE	$F8,$82,$02,$F0
		.BYTE	$F8,$82,$42,$08
		.BYTE	$F8,$92,$02,$F8
		.BYTE	$F8,$92,$42,$00
		.BYTE	$00
_sprA08_6C:
		.BYTE	$04
_sprA08_6C_A:
		.BYTE	$08,$8C,$02,$F8
		.BYTE	$08,$9C,$02,$00
		.BYTE	$08,$9E,$02,$08
		.BYTE	$08,$9E,$42,$F0
		.BYTE	$86
		.WORD	_sprA08_10_B
		.BYTE	$00
_sprA08_6D:
		.BYTE	$0C
_sprA08_6D_A:
		.BYTE	$08,$A4,$02,$00
		.BYTE	$08,$A4,$42,$F8
		.BYTE	$08,$B4,$02,$08
		.BYTE	$08,$B4,$42,$F0
		.BYTE	$E8,$A0,$02,$00
_sprA08_6D_B:
		.BYTE	$E8,$A0,$42,$F8
		.BYTE	$E8,$B0,$02,$08
		.BYTE	$E8,$B0,$42,$F0
		.BYTE	$F8,$A2,$02,$00
		.BYTE	$F8,$A2,$42,$F8
		.BYTE	$F8,$B2,$02,$08
		.BYTE	$F8,$B2,$42,$F0
		.BYTE	$00
_sprA08_6E:
		.BYTE	$0A
_sprA08_6E_A:
		.BYTE	$08,$8C,$42,$02
		.BYTE	$08,$9C,$42,$FA
		.BYTE	$08,$9E,$02,$0A
		.BYTE	$08,$9E,$42,$F2
		.BYTE	$E8,$88,$42,$06
		.BYTE	$E8,$98,$42,$FE
		.BYTE	$E8,$A8,$42,$F6
		.BYTE	$F8,$8A,$42,$06
		.BYTE	$F8,$9A,$42,$FE
		.BYTE	$F8,$AA,$42,$F6
		.BYTE	$00
_sprA08_6F:
		.BYTE	$0C
_sprA08_6F_A:
		.BYTE	$08,$84,$02,$F2
		.BYTE	$08,$84,$42,$0A
		.BYTE	$08,$94,$02,$FA
		.BYTE	$08,$94,$42,$02
		.BYTE	$E8,$80,$02,$F2
		.BYTE	$E8,$80,$42,$0A
		.BYTE	$E8,$90,$02,$FA
		.BYTE	$E8,$90,$42,$02
		.BYTE	$F8,$82,$02,$F2
		.BYTE	$F8,$82,$42,$0A
		.BYTE	$F8,$92,$02,$FA
		.BYTE	$F8,$92,$42,$02
		.BYTE	$00
_sprA08_70:
		.BYTE	$0A
_sprA08_70_A:
		.BYTE	$08,$8C,$02,$FA
		.BYTE	$08,$9C,$02,$02
		.BYTE	$08,$9E,$02,$0A
		.BYTE	$08,$9E,$42,$F2
		.BYTE	$E8,$88,$02,$F6
		.BYTE	$E8,$98,$02,$FE
		.BYTE	$E8,$A8,$02,$06
		.BYTE	$F8,$8A,$02,$F6
		.BYTE	$F8,$9A,$02,$FE
		.BYTE	$F8,$AA,$02,$06
		.BYTE	$00
_sprA08_71:
		.BYTE	$0C
_sprA08_71_A:
		.BYTE	$08,$A4,$02,$02
		.BYTE	$08,$A4,$42,$FA
		.BYTE	$08,$B4,$02,$0A
		.BYTE	$08,$B4,$42,$F2
		.BYTE	$E8,$A0,$02,$02
		.BYTE	$E8,$A0,$42,$FA
		.BYTE	$E8,$B0,$02,$0A
		.BYTE	$E8,$B0,$42,$F2
		.BYTE	$F8,$A2,$02,$02
		.BYTE	$F8,$A2,$42,$FA
		.BYTE	$F8,$B2,$02,$0A
		.BYTE	$F8,$B2,$42,$F2
		.BYTE	$00
_sprA08_72:
		.BYTE	$46,$03
		.BYTE	$08,$D0,$F0
		.BYTE	$08,$E0,$F8
		.BYTE	$E8,$80,$E8
		.BYTE	$E8,$90,$F0
		.BYTE	$F8,$92,$F0
		.BYTE	$F8,$C0,$00
		.BYTE	$44,$43
		.BYTE	$E8,$80,$00
		.BYTE	$E8,$90,$F8
		.BYTE	$F8,$92,$F8
		.BYTE	$F8,$C0,$E8
		.BYTE	$00
_sprA08_73:
		.BYTE	$06
		.BYTE	$00,$C2,$03,$F0
		.BYTE	$00,$D2,$03,$F8
		.BYTE	$F0,$80,$03,$E8
		.BYTE	$F0,$80,$43,$00
		.BYTE	$F0,$90,$03,$F0
		.BYTE	$F0,$90,$43,$F8
		.BYTE	$00
_sprA08_74:
		.BYTE	$44,$03
		.BYTE	$E8,$80,$F8
		.BYTE	$E8,$90,$00
		.BYTE	$F8,$92,$00
		.BYTE	$F8,$C0,$10
		.BYTE	$46,$43
		.BYTE	$08,$D0,$08
		.BYTE	$08,$E0,$00
		.BYTE	$E8,$80,$10
		.BYTE	$E8,$90,$08
		.BYTE	$F8,$92,$08
		.BYTE	$F8,$C0,$F8
		.BYTE	$00
_sprA08_75:
		.BYTE	$06
		.BYTE	$00,$C2,$43,$08
		.BYTE	$00,$D2,$43,$00
		.BYTE	$F0,$80,$03,$F8
		.BYTE	$F0,$80,$43,$10
		.BYTE	$F0,$90,$03,$00
		.BYTE	$F0,$90,$43,$08
		.BYTE	$00
_sprA08_76:
		.BYTE	$02
		.BYTE	$00,$36,$03,$00
		.BYTE	$00,$36,$43,$F8
		.BYTE	$82
		.WORD	_sprA08_77_A
		.BYTE	$00
_sprA08_77:
		.BYTE	$04
_sprA08_77_A:
		.BYTE	$F0,$A6,$03,$F8
		.BYTE	$F0,$A6,$43,$00
		.BYTE	$00,$4E,$03,$F8
		.BYTE	$00,$4E,$43,$00
		.BYTE	$00
_sprA08_78:
		.BYTE	$84
		.WORD	_sprA08_77_A
		.BYTE	$02
		.BYTE	$F0,$58,$03,$F0
		.BYTE	$F8,$58,$03,$08
		.BYTE	$00
_sprA08_79:
		.BYTE	$84
		.WORD	_sprA08_77_A
		.BYTE	$02
		.BYTE	$F0,$48,$03,$F0
		.BYTE	$F8,$48,$03,$08
		.BYTE	$00
_sprA08_7A:
		.BYTE	$02
		.BYTE	$FC,$96,$01,$00
		.BYTE	$FC,$96,$01,$F8
		.BYTE	$00
_sprA08_7B:
		.BYTE	$01
		.BYTE	$FC,$96,$01,$FC
		.BYTE	$00
_sprA08_80:
		.BYTE	$02
		.BYTE	$F8,$86,$41,$00
		.BYTE	$F8,$86,$01,$F8
		.BYTE	$00
_sprA08_81:
		.BYTE	$02
		.BYTE	$F8,$F0,$C1,$00
		.BYTE	$F8,$F0,$01,$F8
		.BYTE	$00
_sprA08_82:
		.BYTE	$02
		.BYTE	$F8,$B6,$01,$F8
		.BYTE	$F8,$B6,$41,$00
		.BYTE	$00
_sprA08_83:
		.BYTE	$02
		.BYTE	$F8,$F0,$41,$00
		.BYTE	$F8,$F0,$81,$F8
		.BYTE	$00
_sprA08_84:
		.BYTE	$4E,$02
		.BYTE	$06,$A8,$F0
		.BYTE	$06,$B8,$F8
		.BYTE	$14,$AA,$F1
		.BYTE	$14,$BA,$F8
		.BYTE	$18,$9A,$E8
		.BYTE	$22,$9C,$EA
		.BYTE	$22,$AC,$F1
		.BYTE	$CC,$80,$F8
		.BYTE	$CC,$A0,$F0
		.BYTE	$DA,$92,$EC
		.BYTE	$DC,$82,$F8
		.BYTE	$DC,$A2,$F1
		.BYTE	$EA,$B4,$F8
		.BYTE	$EA,$DA,$0B
		.BYTE	$4D,$42
		.BYTE	$05,$A8,$07
		.BYTE	$06,$B8,$00
		.BYTE	$14,$AA,$08
		.BYTE	$14,$BA,$00
		.BYTE	$22,$9C,$10
		.BYTE	$24,$AC,$08
		.BYTE	$CC,$80,$00
		.BYTE	$CC,$A0,$08
		.BYTE	$DA,$92,$0C
		.BYTE	$DC,$82,$00
		.BYTE	$DC,$A2,$08
		.BYTE	$EA,$B4,$00
		.BYTE	$EA,$DA,$EE
		.BYTE	$04
_sprA08_84_A:
		.BYTE	$F8,$B6,$02,$F8
		.BYTE	$F8,$B6,$42,$00
		.BYTE	$F8,$BE,$02,$07
		.BYTE	$F8,$BE,$42,$F1
		.BYTE	$00
_sprA08_85:
		.BYTE	$4B,$02
		.BYTE	$04,$A8,$F1
		.BYTE	$04,$B8,$F8
		.BYTE	$11,$AA,$F1
		.BYTE	$12,$BA,$F8
		.BYTE	$1D,$9C,$EA
		.BYTE	$1F,$AC,$F1
		.BYTE	$CE,$80,$F8
		.BYTE	$DC,$92,$F0
		.BYTE	$DE,$82,$F8
		.BYTE	$EA,$DA,$08
		.BYTE	$EC,$B4,$F8
		.BYTE	$4B,$42
		.BYTE	$03,$A8,$07
		.BYTE	$04,$B8,$00
		.BYTE	$11,$AA,$08
		.BYTE	$12,$BA,$00
		.BYTE	$1F,$9C,$10
		.BYTE	$20,$AC,$08
		.BYTE	$CE,$80,$00
		.BYTE	$DA,$92,$08
		.BYTE	$DE,$82,$00
		.BYTE	$EA,$DA,$F0
		.BYTE	$EC,$B4,$00
		.BYTE	$84
		.WORD	_sprA08_84_A
		.BYTE	$00
_sprA08_86:
		.BYTE	$47,$02
		.BYTE	$00,$C4,$F0
		.BYTE	$00,$D4,$F8
		.BYTE	$10,$C6,$F0
		.BYTE	$10,$D6,$F8
		.BYTE	$E0,$D0,$F8
		.BYTE	$F0,$C2,$F0
		.BYTE	$F0,$D2,$F8
		.BYTE	$47,$42
		.BYTE	$00,$C4,$08
		.BYTE	$00,$D4,$00
		.BYTE	$10,$C6,$08
		.BYTE	$10,$D6,$00
		.BYTE	$E0,$D0,$00
		.BYTE	$F0,$C2,$08
		.BYTE	$F0,$D2,$00
		.BYTE	$00
_sprA08_87:
		.BYTE	$47,$02
		.BYTE	$00,$E4,$F0
		.BYTE	$00,$F4,$F8
		.BYTE	$10,$E6,$F0
		.BYTE	$10,$F6,$F8
		.BYTE	$E0,$F0,$F8
		.BYTE	$F0,$E2,$F0
		.BYTE	$F0,$F2,$F8
		.BYTE	$47,$42
		.BYTE	$00,$E4,$08
		.BYTE	$00,$F4,$00
		.BYTE	$10,$E6,$08
		.BYTE	$10,$F6,$00
		.BYTE	$E0,$F0,$00
		.BYTE	$F0,$E2,$08
		.BYTE	$F0,$F2,$00
		.BYTE	$00
_sprA08_88:
		.BYTE	$0C
		.BYTE	$E0,$FA,$02,$F8
		.BYTE	$F0,$EA,$02,$F0
		.BYTE	$F0,$FA,$02,$F8
		.BYTE	$E0,$FA,$42,$00
		.BYTE	$F0,$EA,$42,$08
		.BYTE	$F0,$FA,$42,$00
		.BYTE	$00,$FA,$82,$F8
		.BYTE	$10,$FA,$82,$00
		.BYTE	$10,$FA,$82,$F0
		.BYTE	$00,$FA,$C2,$00
		.BYTE	$10,$FA,$C2,$08
		.BYTE	$10,$FA,$C2,$F8
		.BYTE	$00
_sprA08_89:
		.BYTE	$01
		.BYTE	$F8,$8C,$01,$FC
		.BYTE	$00
_sprA08_8A:
		.BYTE	$01
		.BYTE	$F8,$8C,$00,$FC
		.BYTE	$00
_sprA08_8B:
		.BYTE	$01
		.BYTE	$F8,$8A,$01,$FC
		.BYTE	$00
_sprA08_8C:
		.BYTE	$01
		.BYTE	$F8,$8A,$00,$FC
		.BYTE	$00
_sprA08_8D:
		.BYTE	$02
		.BYTE	$F8,$88,$41,$00
		.BYTE	$F8,$88,$01,$F8
		.BYTE	$00
_sprA08_8E:
		.BYTE	$02
		.BYTE	$F8,$88,$40,$00
		.BYTE	$F8,$88,$00,$F8
		.BYTE	$00
_sprA08_8F:
		.BYTE	$02
		.BYTE	$F8,$98,$41,$00
		.BYTE	$F8,$98,$01,$F8
		.BYTE	$00
_sprA08_90:
		.BYTE	$02
		.BYTE	$F8,$98,$40,$00
		.BYTE	$F8,$98,$00,$F8
		.BYTE	$00
_sprA08_91:
		.BYTE	$02
		.BYTE	$F8,$9B,$00,$00
		.BYTE	$F8,$8B,$00,$F8
		.BYTE	$00
_sprA08_92:
		.BYTE	$04
		.BYTE	$00,$D5,$00,$F8
		.BYTE	$00,$E5,$00,$00
_sprA08_92_A:
		.BYTE	$F1,$C5,$00,$00
		.BYTE	$F1,$C5,$40,$F8
		.BYTE	$00
_sprA08_93:
		.BYTE	$04
		.BYTE	$00,$E5,$00,$00
		.BYTE	$00,$E5,$40,$F8
		.BYTE	$F0,$C5,$00,$00
		.BYTE	$F0,$C5,$40,$F8
		.BYTE	$00
_sprA08_94:
		.BYTE	$02
		.BYTE	$00,$D5,$40,$00
		.BYTE	$00,$E5,$40,$F8
		.BYTE	$82
		.WORD	_sprA08_92_A
		.BYTE	$00
_sprB08_C0:
		.BYTE	$26
_sprB08_C0_A:
		.BYTE	$F8,$B6,$02,$F8
		.BYTE	$F8,$B6,$42,$00
		.BYTE	$08,$A8,$02,$F0
		.BYTE	$08,$A8,$42,$08
		.BYTE	$08,$B8,$02,$F8
		.BYTE	$08,$B8,$42,$00
		.BYTE	$18,$9A,$02,$E8
		.BYTE	$18,$9A,$42,$10
		.BYTE	$18,$AA,$02,$F0
		.BYTE	$18,$AA,$42,$08
		.BYTE	$18,$BA,$02,$F8
		.BYTE	$18,$BA,$42,$00
		.BYTE	$28,$9C,$02,$E8
		.BYTE	$28,$9C,$42,$10
		.BYTE	$28,$AC,$02,$F0
		.BYTE	$28,$AC,$42,$08
		.BYTE	$C8,$A0,$02,$F0
		.BYTE	$C8,$A0,$42,$08
		.BYTE	$C8,$B0,$02,$F8
		.BYTE	$C8,$B0,$42,$00
_sprB08_C0_B:
		.BYTE	$D8,$92,$02,$E8
		.BYTE	$D8,$92,$42,$10
		.BYTE	$D8,$A2,$02,$F0
		.BYTE	$D8,$A2,$42,$08
		.BYTE	$D8,$B2,$02,$F8
		.BYTE	$D8,$B2,$42,$00
		.BYTE	$E8,$A4,$02,$F0
		.BYTE	$E8,$B4,$02,$F8
		.BYTE	$F8,$96,$02,$E8
		.BYTE	$F8,$A6,$02,$F0
_sprB08_C0_C:
		.BYTE	$E8,$A4,$42,$08
		.BYTE	$E8,$B4,$42,$00
		.BYTE	$F8,$96,$42,$10
		.BYTE	$F8,$A6,$42,$08
		.BYTE	$E8,$84,$02,$E0
		.BYTE	$E8,$84,$42,$18
		.BYTE	$E8,$94,$02,$E8
		.BYTE	$E8,$94,$42,$10
		.BYTE	$00
_sprB08_C1:
		.BYTE	$9A
		.WORD	_sprB08_C0_A
		.BYTE	$08
_sprB08_C1_A:
		.BYTE	$E8,$B4,$42,$00
		.BYTE	$E8,$CA,$02,$08
		.BYTE	$E8,$DA,$02,$10
		.BYTE	$F8,$BE,$02,$08
		.BYTE	$E8,$CA,$42,$F0
		.BYTE	$E8,$DA,$42,$E8
		.BYTE	$F8,$BE,$42,$F0
		.BYTE	$E8,$B4,$02,$F8
		.BYTE	$00
_sprB08_C2:
		.BYTE	$95
		.WORD	_sprB08_C0_A
		.BYTE	$4A,$02
		.BYTE	$D8,$A2,$F0
		.BYTE	$D8,$B2,$F8
		.BYTE	$E8,$B4,$F8
		.BYTE	$F8,$BE,$08
		.BYTE	$D8,$CC,$00
		.BYTE	$D8,$DC,$08
		.BYTE	$D8,$EC,$10
		.BYTE	$E8,$CE,$00
		.BYTE	$E8,$DE,$08
		.BYTE	$E8,$EE,$10
		.BYTE	$44,$42
		.BYTE	$E8,$C8,$F0
		.BYTE	$E8,$D8,$E8
		.BYTE	$F8,$E8,$F0
		.BYTE	$F8,$F8,$E8
		.BYTE	$00
_sprB08_C3:
		.BYTE	$9A
		.WORD	_sprB08_C0_A
		.BYTE	$44,$02
		.BYTE	$F8,$BE,$08
		.BYTE	$E8,$8E,$00
		.BYTE	$E8,$9E,$08
		.BYTE	$E8,$AE,$10
		.BYTE	$44,$42
		.BYTE	$F8,$BE,$F0
		.BYTE	$E8,$8E,$F8
		.BYTE	$E8,$9E,$F0
		.BYTE	$E8,$AE,$E8
		.BYTE	$00
_sprB08_C4:
		.BYTE	$94
		.WORD	_sprB08_C0_A
		.BYTE	$44,$02
		.BYTE	$E8,$C8,$08
		.BYTE	$E8,$D8,$10
		.BYTE	$F8,$E8,$08
		.BYTE	$F8,$F8,$10
		.BYTE	$4B,$42
		.BYTE	$D8,$92,$10
		.BYTE	$D8,$A2,$08
		.BYTE	$D8,$B2,$00
		.BYTE	$E8,$B4,$00
		.BYTE	$F8,$BE,$F0
		.BYTE	$D8,$CC,$F8
		.BYTE	$D8,$DC,$F0
		.BYTE	$D8,$EC,$E8
		.BYTE	$E8,$CE,$F8
		.BYTE	$E8,$DE,$F0
		.BYTE	$E8,$EE,$E8
		.BYTE	$00
_sprB08_C5:
		.BYTE	$9E
		.WORD	_sprB08_C0_A
		.BYTE	$45,$02
		.BYTE	$E8,$84,$E0
		.BYTE	$E8,$94,$E8
		.BYTE	$E8,$CA,$08
		.BYTE	$E8,$DA,$10
		.BYTE	$F8,$BE,$08
		.BYTE	$01
		.BYTE	$E8,$B4,$42,$00
		.BYTE	$00
_sprB08_C6:
		.BYTE	$9A
		.WORD	_sprB08_C0_A
		.BYTE	$84
		.WORD	_sprB08_C0_C
		.BYTE	$45,$42
		.BYTE	$E8,$84,$18
		.BYTE	$E8,$94,$10
		.BYTE	$E8,$CA,$F0
		.BYTE	$E8,$DA,$E8
		.BYTE	$F8,$BE,$F0
		.BYTE	$01
		.BYTE	$E8,$B4,$02,$F8
		.BYTE	$00
_sprB08_C7:
		.BYTE	$92
		.WORD	_sprB08_C0_A
		.BYTE	$84
		.WORD	_sprB08_C0_B
		.BYTE	$87
		.WORD	_sprB08_C1_A
		.BYTE	$05
		.BYTE	$E8,$B4,$02,$F8
		.BYTE	$C8,$80,$02,$F8
		.BYTE	$C8,$80,$42,$00
		.BYTE	$D8,$82,$02,$F8
		.BYTE	$D8,$82,$42,$00
		.BYTE	$00
