
_sprA05_04:
		.BYTE	$26
		.BYTE	$01,$A4,$02,$F8
		.BYTE	$01,$A4,$42,$00
		.BYTE	$F1,$94,$02,$F8
		.BYTE	$F1,$94,$42,$00
_sprA05_04_A:
		.BYTE	$08,$3E,$02,$00
		.BYTE	$08,$3E,$42,$F8
_sprA05_05:
		.BYTE	$44,$42
		.BYTE	$01,$A2,$00
		.BYTE	$01,$B2,$F8
		.BYTE	$F1,$92,$00
		.BYTE	$F1,$B0,$F8
		.BYTE	$22
_sprA05_05_A:
		.BYTE	$06,$3E,$02,$00
		.BYTE	$06,$3E,$42,$F8
_sprA05_06:
		.BYTE	$04
		.BYTE	$01,$82,$02,$F8
		.BYTE	$01,$82,$42,$00
		.BYTE	$F1,$90,$02,$F8
		.BYTE	$F1,$90,$42,$00
		.BYTE	$A2
		.WORD	_sprA05_04_A
_sprA05_07:
		.BYTE	$44,$02
		.BYTE	$01,$A2,$F8
		.BYTE	$01,$B2,$00
		.BYTE	$F1,$92,$F8
		.BYTE	$F1,$B0,$00
		.BYTE	$A2
		.WORD	_sprA05_05_A
_sprA05_08:
		.BYTE	$04
		.BYTE	$00,$A4,$02,$F8
		.BYTE	$00,$A4,$42,$00
		.BYTE	$F0,$84,$02,$F8
		.BYTE	$F0,$84,$42,$00
		.BYTE	$A2
		.WORD	_sprA05_04_A
_sprA05_09:
		.BYTE	$44,$42
		.BYTE	$00,$A2,$00
		.BYTE	$00,$B2,$F8
		.BYTE	$F0,$A0,$00
		.BYTE	$F0,$B0,$F8
		.BYTE	$A2
		.WORD	_sprA05_05_A
_sprA05_0A:
		.BYTE	$04
_sprA05_0A_A:
		.BYTE	$00,$82,$02,$F8
		.BYTE	$00,$82,$42,$00
		.BYTE	$F0,$80,$02,$F8
		.BYTE	$F0,$80,$42,$00
		.BYTE	$A2
		.WORD	_sprA05_04_A
_sprA05_0B:
		.BYTE	$44,$02
		.BYTE	$00,$A2,$F8
		.BYTE	$00,$B2,$00
		.BYTE	$F0,$A0,$F8
		.BYTE	$F0,$B0,$00
		.BYTE	$A2
		.WORD	_sprA05_05_A
_sprA05_0C:
		.BYTE	$26
		.BYTE	$00,$A4,$02,$FA
		.BYTE	$00,$A4,$42,$02
		.BYTE	$F0,$84,$02,$FA
		.BYTE	$F0,$84,$42,$02
_sprA05_0C_A:
		.BYTE	$08,$3E,$02,$02
		.BYTE	$08,$3E,$42,$FA
_sprA05_0D:
		.BYTE	$26
		.BYTE	$00,$A2,$42,$02
		.BYTE	$00,$B2,$42,$FA
		.BYTE	$F0,$A0,$42,$02
		.BYTE	$F0,$B0,$42,$FA
_sprA05_0D_A:
		.BYTE	$06,$3E,$02,$02
		.BYTE	$06,$3E,$42,$FA
_sprA05_0E:
		.BYTE	$04
		.BYTE	$00,$82,$02,$FA
		.BYTE	$00,$82,$42,$02
		.BYTE	$F0,$80,$02,$FA
		.BYTE	$F0,$80,$42,$02
		.BYTE	$A2
		.WORD	_sprA05_0C_A
_sprA05_0F:
		.BYTE	$44,$02
		.BYTE	$00,$A2,$FA
		.BYTE	$00,$B2,$02
		.BYTE	$F0,$A0,$FA
		.BYTE	$F0,$B0,$02
		.BYTE	$A2
		.WORD	_sprA05_0D_A
_sprA05_10:
		.BYTE	$23
		.BYTE	$00,$B4,$02,$F8
		.BYTE	$F0,$96,$02,$F8
		.BYTE	$F0,$86,$02,$F0
_sprA05_11:
		.BYTE	$22
		.BYTE	$F8,$B6,$02,$F8
		.BYTE	$F8,$A6,$02,$F0
_sprA05_12:
		.BYTE	$23
		.BYTE	$00,$B4,$42,$00
		.BYTE	$F0,$96,$42,$00
		.BYTE	$F0,$86,$42,$08
_sprA05_13:
		.BYTE	$22
		.BYTE	$F8,$A6,$42,$08
		.BYTE	$F8,$B6,$42,$00
_sprA05_14:
		.BYTE	$24
		.BYTE	$00,$F9,$00,$02
		.BYTE	$00,$F9,$00,$F7
		.BYTE	$F0,$E9,$03,$F8
		.BYTE	$F0,$E9,$43,$00
_sprA05_15:
		.BYTE	$22
		.BYTE	$F8,$CF,$03,$F8
		.BYTE	$F8,$DF,$03,$00
_sprA05_16:
		.BYTE	$22
		.BYTE	$F8,$DF,$43,$F8
		.BYTE	$F8,$CF,$43,$00
_sprA05_17:
		.BYTE	$22
		.BYTE	$F8,$CF,$C3,$00
		.BYTE	$F8,$DF,$C3,$F8
_sprA05_18:
		.BYTE	$22
		.BYTE	$F8,$DF,$83,$00
		.BYTE	$F8,$CF,$83,$F8
_sprA05_19:
		.BYTE	$22
		.BYTE	$F8,$E1,$00,$F8
		.BYTE	$F8,$F1,$00,$00
_sprA05_1A:
		.BYTE	$22
		.BYTE	$F8,$F1,$40,$F8
		.BYTE	$F8,$E1,$40,$00
_sprA05_1B:
		.BYTE	$22
		.BYTE	$F8,$E1,$C0,$00
		.BYTE	$F8,$F1,$C0,$F8
_sprA05_1C:
		.BYTE	$22
		.BYTE	$F8,$F1,$80,$00
		.BYTE	$F8,$E1,$80,$F8
_sprA05_1D:
		.BYTE	$22
		.BYTE	$F8,$E7,$03,$F8
		.BYTE	$F8,$F7,$03,$00
_sprA05_1E:
		.BYTE	$22
		.BYTE	$F8,$F7,$43,$F8
		.BYTE	$F8,$E7,$43,$00
_sprA05_1F:
		.BYTE	$22
		.BYTE	$F8,$E7,$C3,$00
		.BYTE	$F8,$F7,$C3,$F8
_sprA05_20:
		.BYTE	$22
		.BYTE	$F8,$F7,$83,$00
		.BYTE	$F8,$E7,$83,$F8
_sprA05_21:
		.BYTE	$22
		.BYTE	$F8,$CB,$03,$F8
		.BYTE	$F8,$DB,$03,$00
_sprA05_22:
		.BYTE	$22
		.BYTE	$F8,$DB,$43,$F8
		.BYTE	$F8,$CB,$43,$00
_sprA05_23:
		.BYTE	$22
		.BYTE	$F8,$CB,$C3,$00
		.BYTE	$F8,$DB,$C3,$F8
_sprA05_24:
		.BYTE	$22
		.BYTE	$F8,$DB,$83,$00
		.BYTE	$F8,$CB,$83,$F8
_sprA05_25:
		.BYTE	$24
_sprA05_25_A:
		.BYTE	$F8,$5B,$03,$F8
		.BYTE	$F8,$5B,$43,$00
		.BYTE	$F9,$4B,$00,$F9
		.BYTE	$F9,$4B,$40,$01
_sprA05_26:
		.BYTE	$82
		.WORD	_sprA05_25_A
		.BYTE	$22
		.BYTE	$FA,$4B,$00,$F9
		.BYTE	$FA,$4B,$40,$01
_sprA05_27:
		.BYTE	$82
		.WORD	_sprA05_25_A
		.BYTE	$22
		.BYTE	$FC,$4B,$00,$F9
		.BYTE	$FC,$4B,$40,$01
_sprA05_28:
		.BYTE	$82
		.WORD	_sprA05_25_A
		.BYTE	$22
		.BYTE	$FE,$4B,$00,$F9
		.BYTE	$FE,$4B,$40,$01
_sprA05_29:
		.BYTE	$82
		.WORD	_sprA05_25_A
		.BYTE	$22
		.BYTE	$01,$4B,$00,$F9
		.BYTE	$01,$4B,$40,$01
_sprA05_2A:
		.BYTE	$82
		.WORD	_sprA05_25_A
		.BYTE	$22
		.BYTE	$05,$4B,$00,$F9
		.BYTE	$05,$4B,$40,$01
_sprA05_2B:
		.BYTE	$82
		.WORD	_sprA05_25_A
		.BYTE	$22
		.BYTE	$0B,$4B,$00,$F9
		.BYTE	$0B,$4B,$40,$01
_sprA05_2C:
		.BYTE	$82
		.WORD	_sprA05_25_A
		.BYTE	$22
		.BYTE	$11,$4B,$00,$F9
		.BYTE	$11,$4B,$40,$01
_sprA05_2D:
		.BYTE	$28
		.BYTE	$EA,$BA,$03,$F8
		.BYTE	$EA,$BA,$43,$00
		.BYTE	$F6,$BC,$00,$F8
		.BYTE	$F6,$BC,$40,$00
		.BYTE	$FA,$A4,$03,$F8
		.BYTE	$FA,$A4,$43,$00
		.BYTE	$02,$3E,$03,$00
		.BYTE	$02,$3E,$43,$F8
_sprA05_2E:
		.BYTE	$28
		.BYTE	$EB,$BA,$03,$F8
		.BYTE	$EB,$BA,$43,$00
		.BYTE	$F9,$BC,$00,$F8
		.BYTE	$F9,$BC,$40,$00
		.BYTE	$FB,$A4,$03,$F8
		.BYTE	$FB,$A4,$43,$00
		.BYTE	$03,$3E,$03,$00
		.BYTE	$03,$3E,$43,$F8
_sprA05_2F:
		.BYTE	$28
		.BYTE	$EA,$BA,$03,$FA
		.BYTE	$EA,$BA,$43,$02
		.BYTE	$F6,$BC,$00,$FA
		.BYTE	$F6,$BC,$40,$02
		.BYTE	$FA,$A4,$03,$FA
		.BYTE	$FA,$A4,$43,$02
		.BYTE	$02,$3E,$03,$02
		.BYTE	$02,$3E,$43,$FA
_sprA05_30:
		.BYTE	$23
		.BYTE	$00,$C6,$03,$F8
		.BYTE	$F0,$88,$03,$F3
		.BYTE	$F0,$98,$03,$FB
_sprA05_31:
		.BYTE	$22
		.BYTE	$F8,$AE,$03,$F0
		.BYTE	$F8,$BE,$03,$F8
_sprA05_32:
		.BYTE	$23
		.BYTE	$00,$C6,$43,$00
		.BYTE	$F0,$88,$43,$05
		.BYTE	$F0,$98,$43,$FD
_sprA05_33:
		.BYTE	$22
		.BYTE	$F8,$AE,$43,$08
		.BYTE	$F8,$BE,$43,$00
_sprA05_34:
		.BYTE	$27
_sprA05_34_A:
		.BYTE	$02,$AA,$03,$F8
		.BYTE	$02,$AA,$43,$00
		.BYTE	$F2,$A8,$03,$F8
		.BYTE	$F2,$B8,$03,$00
		.BYTE	$F0,$E1,$42,$F0
_sprA05_34_C:
		.BYTE	$0A,$3E,$03,$00
		.BYTE	$0A,$3E,$43,$F8
_sprA05_35:
		.BYTE	$05
_sprA05_35_A:
		.BYTE	$02,$86,$43,$00
		.BYTE	$02,$96,$43,$F8
		.BYTE	$F2,$84,$43,$00
		.BYTE	$F2,$94,$43,$F8
		.BYTE	$F1,$E1,$42,$F0
		.BYTE	$A2
		.WORD	_sprA05_34_C
_sprA05_36:
		.BYTE	$05
_sprA05_36_A:
		.BYTE	$02,$A4,$03,$F8
		.BYTE	$02,$A4,$43,$00
		.BYTE	$F2,$A0,$03,$F8
		.BYTE	$F2,$B0,$03,$00
		.BYTE	$F1,$E1,$02,$08
		.BYTE	$A2
		.WORD	_sprA05_34_C
_sprA05_37:
		.BYTE	$05
_sprA05_37_A:
		.BYTE	$02,$86,$03,$F8
		.BYTE	$02,$96,$03,$00
		.BYTE	$F2,$84,$03,$F8
		.BYTE	$F2,$94,$03,$00
		.BYTE	$F1,$E1,$02,$08
		.BYTE	$A2
		.WORD	_sprA05_34_C
_sprA05_38:
		.BYTE	$82
		.WORD	_sprA05_34_A
		.BYTE	$03
_sprA05_38_A:
		.BYTE	$F2,$A6,$03,$F8
		.BYTE	$F2,$B6,$03,$00
		.BYTE	$EC,$E1,$42,$F1
		.BYTE	$A2
		.WORD	_sprA05_34_C
_sprA05_39:
		.BYTE	$82
		.WORD	_sprA05_35_A
		.BYTE	$03
_sprA05_39_A:
		.BYTE	$F2,$88,$43,$00
		.BYTE	$F2,$98,$43,$F8
		.BYTE	$EA,$E1,$42,$F1
		.BYTE	$A2
		.WORD	_sprA05_34_C
_sprA05_3A:
		.BYTE	$82
		.WORD	_sprA05_36_A
		.BYTE	$03
_sprA05_3A_A:
		.BYTE	$F2,$A2,$03,$F8
		.BYTE	$F2,$B2,$03,$00
		.BYTE	$E9,$E1,$02,$03
		.BYTE	$A2
		.WORD	_sprA05_34_C
_sprA05_3B:
		.BYTE	$05
_sprA05_3B_A:
		.BYTE	$02,$86,$03,$F8
		.BYTE	$02,$96,$03,$00
		.BYTE	$F2,$88,$03,$F8
		.BYTE	$F2,$98,$03,$00
		.BYTE	$EA,$E1,$02,$07
		.BYTE	$A2
		.WORD	_sprA05_34_C
_sprA05_3C:
		.BYTE	$82
		.WORD	_sprA05_36_A
		.BYTE	$82
		.WORD	_sprA05_38_A
		.BYTE	$01
		.BYTE	$EC,$E1,$42,$F1
		.BYTE	$A2
		.WORD	_sprA05_34_C
_sprA05_3D:
		.BYTE	$05
_sprA05_3D_A:
		.BYTE	$02,$8A,$43,$00
		.BYTE	$02,$9A,$43,$F8
		.BYTE	$F2,$88,$43,$00
		.BYTE	$F2,$98,$43,$F8
		.BYTE	$EA,$E1,$42,$F1
		.BYTE	$A2
		.WORD	_sprA05_34_C
_sprA05_3E:
		.BYTE	$05
_sprA05_3E_A:
		.BYTE	$02,$B4,$03,$F8
		.BYTE	$02,$B4,$43,$00
		.BYTE	$F2,$A2,$03,$F8
		.BYTE	$F2,$B2,$03,$00
		.BYTE	$E9,$E1,$02,$03
		.BYTE	$A2
		.WORD	_sprA05_34_C
_sprA05_3F:
		.BYTE	$05
_sprA05_3F_A:
		.BYTE	$02,$8A,$03,$F8
		.BYTE	$02,$9A,$03,$00
		.BYTE	$F2,$88,$03,$F8
		.BYTE	$F2,$98,$03,$00
		.BYTE	$EA,$E1,$02,$07
		.BYTE	$A2
		.WORD	_sprA05_34_C
_sprA05_40:
		.BYTE	$27
_sprA05_40_A:
		.BYTE	$02,$A4,$03,$FA
		.BYTE	$02,$A4,$43,$02
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$A6,$03,$FA
		.BYTE	$F2,$B6,$03,$02
		.BYTE	$EC,$E1,$42,$F3
_sprA05_41:
		.BYTE	$27
_sprA05_41_A:
		.BYTE	$02,$8A,$43,$02
		.BYTE	$02,$9A,$43,$FA
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$88,$43,$02
		.BYTE	$F2,$98,$43,$FA
		.BYTE	$EA,$E1,$42,$F3
_sprA05_42:
		.BYTE	$27
_sprA05_42_A:
		.BYTE	$02,$B4,$03,$FA
		.BYTE	$02,$B4,$43,$02
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$A2,$03,$FA
		.BYTE	$F2,$B2,$03,$02
		.BYTE	$E9,$E1,$02,$05
_sprA05_43:
		.BYTE	$27
_sprA05_43_A:
		.BYTE	$02,$8A,$03,$FA
		.BYTE	$02,$9A,$03,$02
		.BYTE	$0A,$3E,$03,$02
		.BYTE	$0A,$3E,$43,$FA
		.BYTE	$F2,$88,$03,$FA
		.BYTE	$F2,$98,$03,$02
		.BYTE	$EA,$E1,$02,$09
_sprA05_44:
		.BYTE	$84
		.WORD	_sprA05_34_A
		.BYTE	$22
		.BYTE	$F0,$C3,$42,$F0
		.BYTE	$F0,$D3,$42,$E8
_sprA05_45:
		.BYTE	$84
		.WORD	_sprA05_35_A
		.BYTE	$22
		.BYTE	$F1,$C3,$42,$F0
		.BYTE	$F1,$D3,$42,$E8
_sprA05_46:
		.BYTE	$84
		.WORD	_sprA05_36_A
		.BYTE	$22
_sprA05_46_A:
		.BYTE	$F1,$C3,$02,$08
		.BYTE	$F1,$D3,$02,$10
_sprA05_47:
		.BYTE	$84
		.WORD	_sprA05_37_A
		.BYTE	$A2
		.WORD	_sprA05_46_A
_sprA05_48:
 		.BYTE	$82
		.WORD	_sprA05_34_A
		.BYTE	$82
		.WORD	_sprA05_38_A
		.BYTE	$22
_sprA05_48_A:
		.BYTE	$EC,$C3,$42,$F1
		.BYTE	$EC,$D3,$42,$E9
_sprA05_49:
		.BYTE	$82
		.WORD	_sprA05_35_A
		.BYTE	$82
		.WORD	_sprA05_39_A
		.BYTE	$22
_sprA05_49_A:
		.BYTE	$EA,$C3,$42,$F1
		.BYTE	$EA,$D3,$42,$E9
_sprA05_4A:
		.BYTE	$82
		.WORD	_sprA05_36_A
		.BYTE	$82
		.WORD	_sprA05_3A_A
		.BYTE	$22
_sprA05_4A_A:
		.BYTE	$E9,$C3,$02,$03
		.BYTE	$E9,$D3,$02,$0B
_sprA05_4B:
		.BYTE	$84
		.WORD	_sprA05_3B_A
		.BYTE	$22
_sprA05_4B_A:
		.BYTE	$EA,$C3,$02,$07
		.BYTE	$EA,$D3,$02,$0F
_sprA05_4C:
		.BYTE	$82
		.WORD	_sprA05_36_A
		.BYTE	$82
		.WORD	_sprA05_38_A
		.BYTE	$A2
		.WORD	_sprA05_48_A
_sprA05_4D:
		.BYTE	$84
		.WORD	_sprA05_3D_A
		.BYTE	$A2
		.WORD	_sprA05_49_A
_sprA05_4E:
		.BYTE	$84
		.WORD	_sprA05_3E_A
		.BYTE	$A2
		.WORD	_sprA05_4A_A
_sprA05_4F:
		.BYTE	$84
		.WORD	_sprA05_3F_A
		.BYTE	$A2
		.WORD	_sprA05_4B_A
_sprA05_50:
		.BYTE	$86
		.WORD	_sprA05_40_A
		.BYTE	$22
		.BYTE	$EC,$C3,$42,$F3
		.BYTE	$EC,$D3,$42,$EB
_sprA05_51:
		.BYTE	$86
		.WORD	_sprA05_41_A
		.BYTE	$22
		.BYTE	$EA,$C3,$42,$F3
		.BYTE	$EA,$D3,$42,$EB
_sprA05_52:
		.BYTE	$86
		.WORD	_sprA05_42_A
		.BYTE	$22
		.BYTE	$E9,$C3,$02,$05
		.BYTE	$E9,$D3,$02,$0D
_sprA05_53:
		.BYTE	$86
		.WORD	_sprA05_43_A
		.BYTE	$22
		.BYTE	$EA,$C3,$02,$09
		.BYTE	$EA,$D3,$02,$11
_sprA05_56:
		.BYTE	$A4
		.WORD	_sprA05_0A_A
_sprA05_57:
		.BYTE	$24
_sprA05_57_A:
		.BYTE	$F8,$90,$02,$F0
		.BYTE	$F8,$90,$42,$08
		.BYTE	$F8,$92,$02,$F8
		.BYTE	$F8,$92,$42,$00
_sprA05_58:
		.BYTE	$02
		.BYTE	$F1,$9C,$03,$F8
		.BYTE	$F1,$9C,$43,$00
		.BYTE	$A4
		.WORD	_sprA05_0A_A
_sprA05_59:
		.BYTE	$02
		.BYTE	$F2,$8E,$43,$01
		.BYTE	$F2,$9E,$43,$F9
		.BYTE	$A4
		.WORD	_sprA05_57_A
_sprA05_5A:
		.BYTE	$02
		.BYTE	$F3,$8C,$03,$F8
		.BYTE	$F3,$8C,$43,$00
		.BYTE	$A4
		.WORD	_sprA05_0A_A
_sprA05_5B:
		.BYTE	$02
		.BYTE	$F2,$8E,$03,$F7
		.BYTE	$F2,$9E,$03,$FF
		.BYTE	$A4
		.WORD	_sprA05_57_A
_sprA05_5C:
		.BYTE	$26
_sprA05_5C_A:
		.BYTE	$08,$3E,$03,$00
		.BYTE	$08,$3E,$43,$F8
		.BYTE	$00,$A4,$03,$F8
		.BYTE	$00,$A4,$43,$00
		.BYTE	$F0,$A6,$03,$F8
		.BYTE	$F0,$B6,$03,$00
_sprA05_5D:
		.BYTE	$82
		.WORD	_sprA05_5C_A
		.BYTE	$64,$43
		.BYTE	$00,$8A,$00
		.BYTE	$00,$9A,$F8
		.BYTE	$F0,$88,$00
		.BYTE	$F0,$98,$F8
_sprA05_5E:
		.BYTE	$82
		.WORD	_sprA05_5C_A
		.BYTE	$24
		.BYTE	$00,$B4,$03,$F8
		.BYTE	$00,$B4,$43,$00
		.BYTE	$F0,$A2,$03,$F8
		.BYTE	$F0,$B2,$03,$00
_sprA05_5F:
		.BYTE	$82
		.WORD	_sprA05_5C_A
		.BYTE	$64,$03
		.BYTE	$00,$8A,$F8
		.BYTE	$00,$9A,$00
		.BYTE	$F0,$88,$F8
		.BYTE	$F0,$98,$00
_sprA05_60:
		.BYTE	$26
_sprA05_60_A:
		.BYTE	$08,$3E,$03,$02
		.BYTE	$08,$3E,$43,$FA
		.BYTE	$00,$A4,$03,$FA
		.BYTE	$00,$A4,$43,$02
		.BYTE	$F0,$A6,$03,$FA
		.BYTE	$F0,$B6,$03,$02
_sprA05_61:
		.BYTE	$82
		.WORD	_sprA05_60_A
		.BYTE	$64,$43
		.BYTE	$00,$8A,$02
		.BYTE	$00,$9A,$FA
		.BYTE	$F0,$88,$02
		.BYTE	$F0,$98,$FA
_sprA05_62:
		.BYTE	$82
		.WORD	_sprA05_60_A
		.BYTE	$24
		.BYTE	$00,$B4,$03,$FA
		.BYTE	$00,$B4,$43,$02
		.BYTE	$F0,$A2,$03,$FA
		.BYTE	$F0,$B2,$03,$02
_sprA05_63:
		.BYTE	$82
		.WORD	_sprA05_60_A
		.BYTE	$64,$03
		.BYTE	$00,$8A,$FA
		.BYTE	$00,$9A,$02
		.BYTE	$F0,$88,$FA
		.BYTE	$F0,$98,$02
_sprA05_64:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$E8,$03,$F8
		.BYTE	$F6,$E8,$43,$00
_sprA05_65:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$F8,$03,$FA
		.BYTE	$F6,$F8,$43,$02
_sprA05_66:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$F8,$03,$F8
		.BYTE	$F6,$F8,$43,$00
_sprA05_67:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$EA,$03,$F8
		.BYTE	$F6,$EA,$43,$00
_sprA05_68:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$FA,$03,$FA
		.BYTE	$F6,$FA,$43,$02
_sprA05_69:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$FA,$03,$F8
		.BYTE	$F6,$FA,$43,$00
_sprA05_6A:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$EC,$03,$F8
		.BYTE	$F6,$EC,$43,$00
_sprA05_6B:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$FC,$03,$FA
		.BYTE	$F6,$FC,$43,$02
_sprA05_6C:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$FC,$03,$F8
		.BYTE	$F6,$FC,$43,$00
_sprA05_6D:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$CA,$03,$F8
		.BYTE	$F6,$CA,$43,$00
_sprA05_6E:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$DA,$03,$FA
		.BYTE	$F6,$DA,$43,$02
_sprA05_6F:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$DA,$03,$F8
		.BYTE	$F6,$DA,$43,$00
_sprA05_70:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$CC,$03,$F8
		.BYTE	$F6,$CC,$43,$00
_sprA05_71:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$DC,$03,$FA
		.BYTE	$F6,$DC,$43,$02
_sprA05_72:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$DC,$03,$F8
		.BYTE	$F6,$DC,$43,$00
_sprA05_73:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$CE,$03,$F8
		.BYTE	$F6,$CE,$43,$00
_sprA05_74:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FE
		.BYTE	$F6,$DE,$03,$FA
		.BYTE	$F6,$DE,$43,$02
_sprA05_75:
		.BYTE	$23
		.BYTE	$02,$AC,$00,$FC
		.BYTE	$F6,$DE,$03,$F8
		.BYTE	$F6,$DE,$43,$00
_sprA05_77:
		.BYTE	$22
		.BYTE	$F4,$DA,$03,$F0
		.BYTE	$F4,$FE,$03,$F8
_sprA05_79:
		.BYTE	$22
		.BYTE	$F4,$FE,$43,$00
		.BYTE	$F4,$DA,$43,$08
_sprA05_7A:
		.BYTE	$21
		.BYTE	$F8,$D8,$03,$FC
_sprA05_7B:
		.BYTE	$21
		.BYTE	$F8,$D8,$C3,$FC
_sprA05_7C:
		.BYTE	$22
		.BYTE	$F8,$98,$00,$00
		.BYTE	$F8,$88,$00,$F8
_sprA05_7D:
		.BYTE	$22
		.BYTE	$F8,$88,$80,$F8
		.BYTE	$F8,$98,$80,$00
_sprA05_7E:
		.BYTE	$22
		.BYTE	$F8,$98,$C0,$F8
		.BYTE	$F8,$88,$C0,$00
_sprA05_7F:
		.BYTE	$22
		.BYTE	$F8,$88,$40,$00
		.BYTE	$F8,$98,$40,$F8
_sprA05_80:
		.BYTE	$22
		.BYTE	$F8,$B8,$00,$00
		.BYTE	$F8,$A8,$00,$F8
_sprA05_81:
		.BYTE	$22
		.BYTE	$F8,$A8,$80,$F8
		.BYTE	$F8,$B8,$80,$00
_sprA05_82:
		.BYTE	$22
		.BYTE	$F8,$B8,$C0,$F8
		.BYTE	$F8,$A8,$C0,$00
_sprA05_83:
		.BYTE	$22
		.BYTE	$F8,$A8,$40,$00
		.BYTE	$F8,$B8,$40,$F8
_sprA05_84:
		.BYTE	$22
		.BYTE	$F8,$9E,$00,$00
		.BYTE	$F8,$8E,$00,$F8
_sprA05_85:
		.BYTE	$22
		.BYTE	$F8,$8E,$40,$00
		.BYTE	$F8,$9E,$40,$F8
_sprA05_86:
		.BYTE	$22
		.BYTE	$F8,$9E,$C0,$F8
		.BYTE	$F8,$8E,$C0,$00
_sprA05_87:
		.BYTE	$22
		.BYTE	$F8,$9E,$80,$00
		.BYTE	$F8,$8E,$80,$F8
_sprA05_88:
		.BYTE	$22
		.BYTE	$F8,$9A,$00,$00
		.BYTE	$F8,$8A,$00,$F8
_sprA05_89:
		.BYTE	$22
		.BYTE	$F8,$8A,$40,$00
		.BYTE	$F8,$9A,$40,$F8
_sprA05_8A:
		.BYTE	$22
		.BYTE	$F8,$9A,$C0,$F8
		.BYTE	$F8,$8A,$C0,$00
_sprA05_8B:
		.BYTE	$22
		.BYTE	$F8,$8A,$80,$F8
		.BYTE	$F8,$9A,$80,$00
_sprA05_8F:
		.BYTE	$22
		.BYTE	$F8,$BA,$00,$00
		.BYTE	$F8,$AA,$00,$F8
_sprA05_93:
		.BYTE	$22
		.BYTE	$F8,$9C,$00,$00
		.BYTE	$F8,$8C,$00,$F8
_sprA05_97:
		.BYTE	$22
		.BYTE	$F8,$BC,$00,$00
		.BYTE	$F8,$AC,$00,$F8
_sprA06_04:
		.BYTE	$64,$03
		.BYTE	$EE,$84,$F0
		.BYTE	$EE,$94,$F8
		.BYTE	$FE,$8C,$F0
		.BYTE	$FE,$8E,$F8
_sprA06_05:
		.BYTE	$64,$03
		.BYTE	$F6,$84,$F0
		.BYTE	$F6,$94,$F8
		.BYTE	$FE,$6E,$F0
		.BYTE	$FE,$7E,$F8
_sprA06_06:
		.BYTE	$64,$43
		.BYTE	$EE,$84,$08
		.BYTE	$EE,$94,$00
		.BYTE	$FE,$8C,$08
		.BYTE	$FE,$8E,$00
_sprA06_07:
		.BYTE	$64,$43
		.BYTE	$F6,$84,$08
		.BYTE	$F6,$94,$00
		.BYTE	$FE,$6E,$08
		.BYTE	$FE,$7E,$00
_sprA06_08:
		.BYTE	$24
		.BYTE	$EE,$8C,$03,$F3
		.BYTE	$EE,$8C,$43,$FB
		.BYTE	$FE,$A0,$03,$F3
		.BYTE	$FE,$B0,$03,$FB
_sprA06_09:
		.BYTE	$22
		.BYTE	$FD,$80,$03,$F2
		.BYTE	$FD,$90,$03,$FA
_sprA06_0A:
		.BYTE	$24
		.BYTE	$EE,$8C,$03,$FE
		.BYTE	$EE,$8C,$43,$06
		.BYTE	$FE,$A0,$43,$06
		.BYTE	$FE,$B0,$43,$FE
_sprA06_0B:
		.BYTE	$22
		.BYTE	$FD,$80,$43,$07
		.BYTE	$FD,$90,$43,$FF
_sprA06_0C:
		.BYTE	$21
		.BYTE	$F8,$B8,$83,$FC
_sprA06_0D:
		.BYTE	$22
		.BYTE	$00,$8E,$83,$FC
		.BYTE	$F8,$B8,$83,$FC
_sprA06_0E:
		.BYTE	$A2
		.WORD	_sprA06_0F_A
_sprA06_0F:
		.BYTE	$23
_sprA06_0F_A:
		.BYTE	$08,$8E,$83,$FC
		.BYTE	$F8,$B8,$83,$FC
		.BYTE	$10,$8E,$03,$FC
_sprA06_10:
		.BYTE	$82
		.WORD	_sprA06_0F_A
		.BYTE	$21
		.BYTE	$18,$8E,$03,$FC
_sprA06_11:
		.BYTE	$A2
		.WORD	_sprA06_14_A
_sprA06_12:
		.BYTE	$A3
		.WORD	_sprA06_14_A
_sprA06_13:
		.BYTE	$A4
		.WORD	_sprA06_14_A
_sprA06_14:
		.BYTE	$25
_sprA06_14_A:
		.BYTE	$F5,$84,$43,$00
		.BYTE	$F5,$94,$43,$F8
		.BYTE	$F5,$A4,$43,$F0
		.BYTE	$F5,$A4,$43,$E8
		.BYTE	$F5,$A4,$43,$E0
_sprA06_15:
		.BYTE	$21
		.BYTE	$F8,$B8,$03,$FC
_sprA06_16:
		.BYTE	$22
		.BYTE	$F0,$8E,$03,$FC
		.BYTE	$F8,$B8,$03,$FC
_sprA06_17:
		.BYTE	$A2
		.WORD	_sprA06_19_A
_sprA06_18:
		.BYTE	$01
		.BYTE	$E1,$8E,$03,$FC
		.BYTE	$A2
		.WORD	_sprA06_19_A
_sprA06_19:
		.BYTE	$23
		.BYTE	$D8,$8E,$03,$FC
_sprA06_19_A:
		.BYTE	$E8,$8E,$03,$FC
		.BYTE	$F8,$B8,$03,$FC
_sprA06_1A:
		.BYTE	$A2
		.WORD	_sprA06_1D_A
_sprA06_1B:
		.BYTE	$A3
		.WORD	_sprA06_1D_A
_sprA06_1C:
		.BYTE	$A4
		.WORD	_sprA06_1D_A
_sprA06_1D:
		.BYTE	$25
_sprA06_1D_A:
		.BYTE	$F5,$84,$03,$F8
		.BYTE	$F5,$94,$03,$00
		.BYTE	$F5,$A4,$03,$08
		.BYTE	$F5,$A4,$03,$10
		.BYTE	$F5,$A4,$03,$18
_sprA06_1E:
		.BYTE	$24
_sprA06_1E_A:
		.BYTE	$00,$C2,$40,$00
		.BYTE	$00,$D2,$40,$F8
_sprA06_1E_B:
		.BYTE	$F1,$E8,$00,$F8
		.BYTE	$F1,$F8,$00,$00
_sprA06_1F:
		.BYTE	$26
_sprA06_1F_A:
		.BYTE	$00,$C6,$40,$00
		.BYTE	$00,$D6,$40,$F8
_sprA06_1F_B:
		.BYTE	$F1,$E4,$40,$00
		.BYTE	$F1,$F4,$40,$F8
		.BYTE	$F2,$C8,$40,$09
		.BYTE	$F2,$D8,$40,$01
_sprA06_20:
		.BYTE	$82
		.WORD	_sprA06_1E_A
		.BYTE	$A3
		.WORD	_sprA06_28_B
_sprA06_21:
		.BYTE	$26
_sprA06_21_A:
		.BYTE	$00,$C6,$00,$F8
		.BYTE	$00,$D6,$00,$00
_sprA06_21_B:
		.BYTE	$F1,$E4,$00,$F8
		.BYTE	$F1,$F4,$00,$00
		.BYTE	$F2,$C8,$00,$EF
		.BYTE	$F2,$D8,$00,$F7
_sprA06_22:
		.BYTE	$25
_sprA06_22_A:
		.BYTE	$00,$E2,$00,$F8
		.BYTE	$00,$F2,$00,$00
		.BYTE	$E8,$FA,$80,$FE
		.BYTE	$F0,$E8,$00,$F8
		.BYTE	$F0,$F8,$00,$00
_sprA06_23:
		.BYTE	$25
_sprA06_23_A:
		.BYTE	$00,$E6,$40,$00
		.BYTE	$00,$F6,$40,$F8
_sprA06_23_B:
		.BYTE	$F0,$E4,$40,$00
		.BYTE	$F0,$F4,$40,$F8
		.BYTE	$EC,$FA,$C0,$01
_sprA06_24:
		.BYTE	$03
		.BYTE	$00,$FA,$00,$FC
		.BYTE	$F0,$C4,$00,$F8
		.BYTE	$F0,$D4,$00,$00
		.BYTE	$A2
		.WORD	_sprA06_22_A
_sprA06_25:
		.BYTE	$25
_sprA06_25_A:
		.BYTE	$00,$E6,$00,$F8
		.BYTE	$00,$F6,$00,$00
_sprA06_25_B:
		.BYTE	$F0,$E4,$00,$F8
		.BYTE	$F0,$F4,$00,$00
		.BYTE	$EC,$FA,$80,$F7
_sprA06_26:
		.BYTE	$82
		.WORD	_sprA06_28_A
		.BYTE	$A2
		.WORD	_sprA06_1E_B
_sprA06_27:
		.BYTE	$82
		.WORD	_sprA06_28_A
		.BYTE	$A4
		.WORD	_sprA06_1F_B
_sprA06_28:
		.BYTE	$25
_sprA06_28_A:
		.BYTE	$00,$C2,$00,$F8
		.BYTE	$00,$D2,$00,$00
_sprA06_28_B:
		.BYTE	$E8,$FA,$80,$FC
		.BYTE	$F1,$C4,$00,$F8
		.BYTE	$F1,$D4,$00,$00
_sprA06_29:
		.BYTE	$82
		.WORD	_sprA06_1E_A
		.BYTE	$A4
		.WORD	_sprA06_21_B
_sprA06_2A:
		.BYTE	$82
		.WORD	_sprA06_22_A
		.BYTE	$22
		.BYTE	$F0,$C0,$00,$F8
		.BYTE	$F0,$D0,$00,$00
_sprA06_2B:
		.BYTE	$02
		.BYTE	$00,$E2,$40,$00
		.BYTE	$00,$F2,$40,$F8
		.BYTE	$A2
		.WORD	_sprA06_23_B
_sprA06_2C:
		.BYTE	$82
		.WORD	_sprA06_22_A
		.BYTE	$22
		.BYTE	$F0,$E0,$00,$F8
		.BYTE	$F0,$F0,$00,$00
_sprA06_2D:
		.BYTE	$82
		.WORD	_sprA06_22_A
		.BYTE	$A2
		.WORD	_sprA06_25_B
_sprA06_2E:
		.BYTE	$24
_sprA06_2E_A:
		.BYTE	$00,$E2,$00,$FA
		.BYTE	$00,$F2,$00,$02
		.BYTE	$F0,$C0,$00,$FA
		.BYTE	$F0,$D0,$00,$02
_sprA06_2F:
		.BYTE	$64,$40
		.BYTE	$00,$E2,$02
		.BYTE	$00,$F2,$FA
		.BYTE	$F0,$E4,$02
		.BYTE	$F0,$F4,$FA
_sprA06_30:
		.BYTE	$82
		.WORD	_sprA06_2E_A
		.BYTE	$22
		.BYTE	$F0,$E0,$00,$FA
		.BYTE	$F0,$F0,$00,$02
_sprA06_31:
		.BYTE	$82
		.WORD	_sprA06_2E_A
		.BYTE	$22
		.BYTE	$F0,$E4,$00,$FA
		.BYTE	$F0,$F4,$00,$02
_sprA06_32:
		.BYTE	$64,$00
		.BYTE	$07,$EC,$F2
		.BYTE	$07,$FC,$FA
		.BYTE	$F7,$E4,$F2
		.BYTE	$F7,$F4,$FA
_sprA06_33:
		.BYTE	$22
		.BYTE	$FF,$CC,$00,$F2
		.BYTE	$FF,$DC,$00,$FA
_sprA06_34:
		.BYTE	$64,$40
		.BYTE	$08,$EC,$07
		.BYTE	$08,$FC,$FF
		.BYTE	$F8,$E4,$07
		.BYTE	$F8,$F4,$FF
_sprA06_35:
		.BYTE	$22
		.BYTE	$FF,$CC,$40,$07
		.BYTE	$FF,$DC,$40,$FF
_sprA06_36:
		.BYTE	$82
		.WORD	_sprA06_28_A
		.BYTE	$23
_sprA06_36_A:
		.BYTE	$EE,$EA,$00,$FC
		.BYTE	$F1,$C0,$00,$F8
		.BYTE	$F1,$F8,$00,$00
_sprA06_37:
		.BYTE	$84
		.WORD	_sprA06_1F_A
		.BYTE	$21
		.BYTE	$F7,$EA,$00,$FD
_sprA06_38:
		.BYTE	$82
		.WORD	_sprA06_28_A
		.BYTE	$23
_sprA06_38_A:
		.BYTE	$F1,$D4,$00,$00
		.BYTE	$F1,$E0,$00,$F8
		.BYTE	$F4,$DA,$80,$FC
_sprA06_39:
		.BYTE	$84
		.WORD	_sprA06_21_A
		.BYTE	$21
		.BYTE	$F7,$EA,$40,$FB
_sprA06_3A:
		.BYTE	$82
		.WORD	_sprA06_22_A
		.BYTE	$23
		.BYTE	$E9,$EA,$40,$FF
		.BYTE	$F0,$C0,$00,$F8
		.BYTE	$F0,$F8,$00,$00
_sprA06_3B:
		.BYTE	$84
		.WORD	_sprA06_23_A
		.BYTE	$21
		.BYTE	$F5,$DA,$40,$02
_sprA06_3C:
		.BYTE	$82
		.WORD	_sprA06_22_A
		.BYTE	$23
		.BYTE	$F0,$D4,$00,$00
		.BYTE	$F0,$E0,$00,$F8
		.BYTE	$F5,$EA,$80,$01
_sprA06_3D:
		.BYTE	$84
		.WORD	_sprA06_25_A
		.BYTE	$21
		.BYTE	$F5,$DA,$00,$F6
_sprA06_3E:
		.BYTE	$82
		.WORD	_sprA06_1E_A
		.BYTE	$A3
		.WORD	_sprA06_36_A
_sprA06_3F:
		.BYTE	$82
		.WORD	_sprA06_28_A
		.BYTE	$82
		.WORD	_sprA06_1F_B
		.BYTE	$21
		.BYTE	$F7,$EA,$40,$FD
_sprA06_40:
		.BYTE	$82
		.WORD	_sprA06_1E_A
		.BYTE	$A3
		.WORD	_sprA06_38_A
_sprA06_41:
		.BYTE	$82
		.WORD	_sprA06_1E_A
		.BYTE	$82
		.WORD	_sprA06_21_B
		.BYTE	$21
		.BYTE	$F7,$EA,$00,$FB
_sprA06_42:
		.BYTE	$21
		.BYTE	$FD,$CA,$00,$FD
_sprA06_43:
		.BYTE	$21
		.BYTE	$FD,$CA,$40,$FD
_sprA06_44:
		.BYTE	$21
		.BYTE	$F5,$CA,$C0,$FD
_sprA06_45:
		.BYTE	$21
		.BYTE	$F5,$CA,$80,$FD
_sprA06_46:
		.BYTE	$22
		.BYTE	$F8,$CE,$03,$02
		.BYTE	$F8,$BE,$03,$FA
_sprA06_47:
		.BYTE	$22
		.BYTE	$FF,$BE,$03,$F1
		.BYTE	$FF,$6E,$03,$F9
_sprA06_48:
		.BYTE	$21
		.BYTE	$FF,$FE,$03,$F9
_sprA06_49:
		.BYTE	$22
		.BYTE	$FF,$BE,$43,$08
		.BYTE	$FF,$6E,$43,$00
_sprA06_4A:
		.BYTE	$21
		.BYTE	$FF,$FE,$43,$00
_sprA06_4B:
		.BYTE	$22
		.BYTE	$F4,$E0,$03,$F8
		.BYTE	$F4,$E0,$43,$00
_sprA06_4C:
		.BYTE	$22
		.BYTE	$F4,$E2,$03,$F8
		.BYTE	$F4,$E2,$43,$00
_sprA06_4D:
		.BYTE	$22
		.BYTE	$F4,$E4,$03,$F8
		.BYTE	$F4,$E4,$43,$00
_sprA06_4E:
		.BYTE	$22
		.BYTE	$F4,$E0,$03,$FA
		.BYTE	$F4,$E0,$43,$02
_sprA06_50:
		.BYTE	$21
		.BYTE	$05,$CE,$03,$FA
_sprA06_51:
		.BYTE	$22
		.BYTE	$02,$E4,$83,$F8
		.BYTE	$02,$E4,$C3,$00
_sprA06_52:
		.BYTE	$21
		.BYTE	$05,$CE,$43,$FF
_sprA06_53:
		.BYTE	$22
		.BYTE	$F4,$F0,$03,$F8
		.BYTE	$F4,$F0,$43,$00
_sprA06_54:
		.BYTE	$24
		.BYTE	$04,$F4,$03,$F8
		.BYTE	$04,$F4,$43,$00
		.BYTE	$F4,$F2,$03,$F8
		.BYTE	$F4,$F2,$43,$00
_sprA06_55:
		.BYTE	$24
		.BYTE	$04,$E8,$03,$F8
		.BYTE	$04,$E8,$43,$00
		.BYTE	$F4,$E6,$03,$F8
		.BYTE	$F4,$E6,$43,$00
_sprA06_56:
		.BYTE	$24
		.BYTE	$04,$F8,$03,$F8
		.BYTE	$04,$F8,$43,$00
		.BYTE	$F4,$F6,$03,$F8
		.BYTE	$F4,$F6,$43,$00
_sprA06_57:
		.BYTE	$24
		.BYTE	$04,$F4,$03,$FA
		.BYTE	$04,$F4,$43,$02
		.BYTE	$F4,$F2,$03,$FA
		.BYTE	$F4,$F2,$43,$02
_sprA06_58:
		.BYTE	$24
		.BYTE	$05,$EA,$03,$F3
		.BYTE	$05,$FA,$03,$FB
		.BYTE	$F5,$F2,$03,$F3
		.BYTE	$F5,$F2,$43,$FB
_sprA06_59:
		.BYTE	$22
		.BYTE	$FE,$EC,$03,$F1
		.BYTE	$FE,$FC,$03,$F9
_sprA06_5A:
		.BYTE	$24
		.BYTE	$06,$EA,$43,$07
		.BYTE	$06,$FA,$43,$FF
		.BYTE	$F6,$F2,$03,$FF
		.BYTE	$F6,$F2,$43,$07
_sprA06_5B:
		.BYTE	$22
		.BYTE	$FD,$EC,$43,$09
		.BYTE	$FD,$FC,$43,$01
_sprA06_5C:
		.BYTE	$21
		.BYTE	$FC,$FE,$01,$FD
_sprA06_5D:
		.BYTE	$21
		.BYTE	$FC,$EE,$01,$FC
_sprA06_5E:
		.BYTE	$26
_sprA06_5E_A:
		.BYTE	$04,$C2,$03,$FC
		.BYTE	$04,$D2,$03,$04
		.BYTE	$04,$D2,$43,$F4
		.BYTE	$F4,$D0,$03,$04
		.BYTE	$F4,$D0,$43,$F4
		.BYTE	$F4,$DE,$03,$FC
_sprA06_5F:
		.BYTE	$26
_sprA06_5F_A:
		.BYTE	$04,$CA,$03,$FC
		.BYTE	$04,$DA,$03,$04
		.BYTE	$F4,$CC,$03,$F4
		.BYTE	$F4,$D8,$03,$04
		.BYTE	$04,$D2,$43,$F4
		.BYTE	$F4,$DC,$03,$FC
_sprA06_60:
		.BYTE	$26
_sprA06_60_A:
		.BYTE	$04,$D2,$03,$04
		.BYTE	$04,$D2,$43,$F4
		.BYTE	$04,$D6,$03,$FC
		.BYTE	$F4,$C4,$43,$04
		.BYTE	$F4,$C6,$43,$F4
		.BYTE	$F4,$D4,$43,$FC
_sprA06_61:
		.BYTE	$26
_sprA06_61_A:
		.BYTE	$04,$CA,$43,$FC
		.BYTE	$04,$DA,$43,$F4
		.BYTE	$F4,$CC,$43,$04
		.BYTE	$F4,$D8,$43,$F4
		.BYTE	$04,$D2,$43,$FD
		.BYTE	$F4,$C8,$43,$FC
_sprA06_62:
		.BYTE	$85
		.WORD	_sprA06_5E_A
		.BYTE	$21
		.BYTE	$F4,$C0,$03,$FC
_sprA06_63:
		.BYTE	$84
		.WORD	_sprA06_5F_A
		.BYTE	$22
		.BYTE	$04,$D2,$03,$FB
		.BYTE	$F4,$C8,$03,$FC
_sprA06_64:
		.BYTE	$83
		.WORD	_sprA06_60_A
		.BYTE	$23
		.BYTE	$F4,$C4,$03,$F4
		.BYTE	$F4,$C6,$03,$04
		.BYTE	$F4,$D4,$03,$FC
_sprA06_65:
		.BYTE	$84
		.WORD	_sprA06_61_A
		.BYTE	$22
		.BYTE	$04,$D2,$03,$04
		.BYTE	$F4,$DC,$43,$FC
_sprA06_66:
		.BYTE	$26
		.BYTE	$04,$C2,$03,$FE
		.BYTE	$04,$D2,$03,$06
		.BYTE	$04,$D2,$43,$F6
		.BYTE	$F4,$C0,$03,$FE
		.BYTE	$F4,$D0,$03,$06
		.BYTE	$F4,$D0,$43,$F6
_sprA06_67:
		.BYTE	$24
		.BYTE	$07,$CE,$03,$FA
		.BYTE	$F7,$C0,$03,$FA
		.BYTE	$F7,$C6,$03,$02
		.BYTE	$F7,$C6,$43,$F2
_sprA06_68:
		.BYTE	$21
		.BYTE	$FE,$BE,$03,$FA
_sprA06_69:
		.BYTE	$24
		.BYTE	$07,$CE,$43,$00
		.BYTE	$F7,$C0,$43,$00
		.BYTE	$F7,$C6,$03,$08
		.BYTE	$F7,$C6,$43,$F8
_sprA06_6A:
		.BYTE	$21
		.BYTE	$FE,$BE,$43,$FF
_sprA06_6B:
		.BYTE	$22
		.BYTE	$F8,$C9,$01,$D8
		.BYTE	$F8,$C9,$01,$20
_sprA06_6C:
		.BYTE	$22
		.BYTE	$F8,$C7,$01,$D8
		.BYTE	$F8,$C7,$01,$20
_sprA06_6D:
		.BYTE	$22
		.BYTE	$00,$05,$00,$FC
		.BYTE	$F0,$03,$00,$FC
_sprB06_C0:
		.BYTE	$27
_sprB06_C0_A:
		.BYTE	$0A,$3E,$00,$00
		.BYTE	$0A,$3E,$40,$F8
		.BYTE	$EC,$88,$03,$F8
		.BYTE	$EC,$98,$03,$00
		.BYTE	$EC,$B8,$03,$08
		.BYTE	$FC,$8A,$03,$F8
		.BYTE	$FC,$9A,$03,$00
_sprB06_C1:
		.BYTE	$82
		.WORD	_sprB06_C0_A
		.BYTE	$66,$43
		.BYTE	$EC,$84,$00
		.BYTE	$EC,$94,$F8
		.BYTE	$EC,$BC,$08
		.BYTE	$FC,$86,$00
		.BYTE	$FC,$96,$F8
		.BYTE	$FC,$AC,$08
_sprB06_C2:
		.BYTE	$82
		.WORD	_sprB06_C0_A
		.BYTE	$66,$03
		.BYTE	$EC,$80,$F8
		.BYTE	$EC,$90,$00
		.BYTE	$EC,$9C,$F0
		.BYTE	$FC,$82,$F8
		.BYTE	$FC,$92,$00
		.BYTE	$FC,$9E,$F0
_sprB06_C3:
		.BYTE	$82
		.WORD	_sprB06_C0_A
		.BYTE	$66,$03
		.BYTE	$EC,$84,$F8
		.BYTE	$EC,$94,$00
		.BYTE	$EC,$BC,$F0
		.BYTE	$FC,$86,$F8
		.BYTE	$FC,$96,$00
		.BYTE	$FC,$AC,$F0
_sprB06_C4:
		.BYTE	$82
		.WORD	_sprB06_C0_A
		.BYTE	$24
		.BYTE	$EC,$88,$43,$00
		.BYTE	$EC,$A8,$03,$F8
		.BYTE	$FC,$8A,$43,$00
		.BYTE	$FC,$AA,$03,$F8
_sprB06_C5:
		.BYTE	$82
		.WORD	_sprB06_C0_A
		.BYTE	$65,$43
		.BYTE	$EC,$A4,$00
		.BYTE	$EC,$B4,$F8
		.BYTE	$FC,$A6,$00
		.BYTE	$FC,$B6,$F8
		.BYTE	$FC,$BA,$08
_sprB06_C6:
		.BYTE	$82
		.WORD	_sprB06_C0_A
		.BYTE	$64,$03
		.BYTE	$EC,$A0,$F8
		.BYTE	$EC,$B0,$00
		.BYTE	$FC,$A2,$F8
		.BYTE	$FC,$B2,$00
_sprB06_C7:
		.BYTE	$82
		.WORD	_sprB06_C0_A
		.BYTE	$65,$03
		.BYTE	$EC,$A4,$F8
		.BYTE	$EC,$B4,$00
		.BYTE	$FC,$A6,$F8
		.BYTE	$FC,$B6,$00
		.BYTE	$FC,$BA,$F0
_sprB06_C8:
		.BYTE	$27
_sprB06_C8_A:
		.BYTE	$0A,$3E,$00,$02
		.BYTE	$0A,$3E,$40,$FA
		.BYTE	$EC,$88,$03,$FA
		.BYTE	$EC,$98,$03,$02
		.BYTE	$EC,$B8,$03,$0A
		.BYTE	$FC,$8A,$03,$FA
		.BYTE	$FC,$9A,$03,$02
_sprB06_C9:
		.BYTE	$82
		.WORD	_sprB06_C8_A
		.BYTE	$66,$43
		.BYTE	$EC,$84,$02
		.BYTE	$EC,$94,$FA
		.BYTE	$EC,$BC,$0A
		.BYTE	$FC,$86,$02
		.BYTE	$FC,$96,$FA
		.BYTE	$FC,$AC,$0A
_sprB06_CA:
		.BYTE	$82
		.WORD	_sprB06_C8_A
		.BYTE	$66,$03
		.BYTE	$EC,$80,$FA
		.BYTE	$EC,$90,$02
		.BYTE	$EC,$9C,$F2
		.BYTE	$FC,$82,$FA
		.BYTE	$FC,$92,$02
		.BYTE	$FC,$9E,$F2
_sprB06_CB:
		.BYTE	$82
		.WORD	_sprB06_C8_A
		.BYTE	$66,$03
		.BYTE	$EC,$84,$FA
		.BYTE	$EC,$94,$02
		.BYTE	$EC,$BC,$F2
		.BYTE	$FC,$86,$FA
		.BYTE	$FC,$96,$02
		.BYTE	$FC,$AC,$F2
_sprB06_CC:
_sprB06_D8:
		.BYTE	$84
		.WORD	_sprB06_CE_A
		.BYTE	$22
		.BYTE	$F4,$AC,$03,$F8
		.BYTE	$F4,$AC,$43,$00
_sprB06_CD:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$25
_sprB06_CD_A:
		.BYTE	$E4,$B4,$43,$F8
		.BYTE	$F4,$A6,$43,$00
		.BYTE	$F4,$B6,$43,$F8
		.BYTE	$F4,$A2,$43,$10
		.BYTE	$F4,$B2,$43,$08
_sprB06_CE:
		.BYTE	$27
_sprB06_CE_A:
		.BYTE	$06,$3E,$00,$00
		.BYTE	$06,$3E,$40,$F8
		.BYTE	$E4,$8C,$03,$F8
		.BYTE	$E4,$8C,$43,$00
		.BYTE	$F4,$9C,$03,$F8
		.BYTE	$F4,$9C,$43,$00
		.BYTE	$04,$BC,$03,$F8
_sprB06_CF:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$25
_sprB06_CF_A:
		.BYTE	$E4,$B4,$03,$00
		.BYTE	$F4,$A6,$03,$F8
		.BYTE	$F4,$B6,$03,$00
		.BYTE	$F4,$A2,$03,$E8
		.BYTE	$F4,$B2,$03,$F0
_sprB06_D0:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$25
_sprB06_D0_A:
		.BYTE	$F3,$8A,$03,$F0
		.BYTE	$F3,$8A,$43,$08
		.BYTE	$F3,$AA,$03,$F8
		.BYTE	$F3,$AA,$43,$00
		.BYTE	$EB,$BA,$C3,$00
_sprB06_D1:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$24
_sprB06_D1_A:
		.BYTE	$F3,$96,$43,$F8
		.BYTE	$F3,$A6,$43,$00
		.BYTE	$F3,$82,$43,$10
		.BYTE	$F3,$92,$43,$08
_sprB06_D2:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$82
		.WORD	_sprB06_D0_A
		.BYTE	$23
_sprB06_D2_A:
		.BYTE	$F3,$9A,$03,$F8
		.BYTE	$F3,$9A,$43,$00
		.BYTE	$03,$BA,$43,$F8
_sprB06_D3:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$24
_sprB06_D3_A:
		.BYTE	$F3,$96,$03,$00
		.BYTE	$F3,$A6,$03,$F8
		.BYTE	$F3,$82,$03,$E8
		.BYTE	$F3,$92,$03,$F0
_sprB06_D4:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$25
_sprB06_D4_A:
		.BYTE	$F2,$88,$03,$F0
		.BYTE	$F2,$88,$43,$08
		.BYTE	$F2,$A8,$43,$00
		.BYTE	$EA,$B8,$C3,$00
		.BYTE	$F2,$A8,$03,$F8
_sprB06_D5:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$24
_sprB06_D5_A:
		.BYTE	$F2,$86,$43,$F8
		.BYTE	$F2,$A6,$43,$00
		.BYTE	$F2,$84,$43,$10
		.BYTE	$F2,$94,$43,$08
_sprB06_D6:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$82
		.WORD	_sprB06_D4_A
		.BYTE	$23
_sprB06_D6_A:
		.BYTE	$F2,$98,$03,$F8
		.BYTE	$F2,$98,$43,$00
		.BYTE	$02,$B8,$43,$F8
_sprB06_D7:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$24
		.BYTE	$F2,$84,$03,$E8
		.BYTE	$F2,$86,$03,$00
		.BYTE	$F2,$94,$03,$F0
		.BYTE	$F2,$A6,$03,$F8
_sprB06_D9:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$A3
		.WORD	_sprB06_CD_A
_sprB06_DA:
		.BYTE	$A6
		.WORD	_sprB06_CE_A
_sprB06_DB:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$A3
		.WORD	_sprB06_CF_A
_sprB06_DC:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$A4
		.WORD	_sprB06_D0_A
_sprB06_DD:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$A2
		.WORD	_sprB06_D1_A
_sprB06_DE:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$82
		.WORD	_sprB06_D0_A
		.BYTE	$A2
		.WORD	_sprB06_D2_A
_sprB06_DF:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$A2
		.WORD	_sprB06_D3_A
_sprB06_E0:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$83
		.WORD	_sprB06_D4_A
		.BYTE	$21
		.BYTE	$F2,$A8,$03,$F8
_sprB06_E1:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$A2
		.WORD	_sprB06_D5_A
_sprB06_E2:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$82
		.WORD	_sprB06_D4_A
		.BYTE	$A2
		.WORD	_sprB06_D6_A
_sprB06_E3:
		.BYTE	$82
		.WORD	_sprB06_CE_A
		.BYTE	$22
		.BYTE	$F2,$86,$03,$00
		.BYTE	$F2,$A6,$03,$F8
_sprB06_E4:
		.BYTE	$26
_sprB06_E4_A:
		.BYTE	$06,$3E,$00,$02
		.BYTE	$06,$3E,$40,$FA
		.BYTE	$E4,$8C,$03,$FA
		.BYTE	$E4,$8C,$43,$02
		.BYTE	$F4,$AC,$03,$FA
		.BYTE	$F4,$AC,$43,$02
_sprB06_E5:
		.BYTE	$82
		.WORD	_sprB06_E4_A
		.BYTE	$25
		.BYTE	$E4,$B4,$43,$FA
		.BYTE	$F4,$A2,$43,$12
		.BYTE	$F4,$A6,$43,$02
		.BYTE	$F4,$B2,$43,$0A
		.BYTE	$F4,$B6,$43,$FA
_sprB06_E6:
		.BYTE	$84
		.WORD	_sprB06_E4_A
		.BYTE	$23
		.BYTE	$04,$BC,$03,$FA
		.BYTE	$F4,$9C,$03,$FA
		.BYTE	$F4,$9C,$43,$02
_sprB06_E7:
		.BYTE	$82
		.WORD	_sprB06_E4_A
		.BYTE	$25
		.BYTE	$E4,$B4,$03,$02
		.BYTE	$F4,$A2,$03,$EA
		.BYTE	$F4,$A6,$03,$FA
		.BYTE	$F4,$B2,$03,$F2
		.BYTE	$F4,$B6,$03,$02
_sprB06_E8:
		.BYTE	$22
		.BYTE	$F8,$CE,$03,$00
		.BYTE	$F8,$BE,$03,$F8
_sprB06_E9:
		.BYTE	$22
		.BYTE	$F8,$EE,$03,$00
		.BYTE	$F8,$DE,$03,$F8
_sprB06_EA:
		.BYTE	$22
		.BYTE	$F8,$EE,$43,$F8
		.BYTE	$F8,$DE,$43,$00
_sprB06_EB:
		.BYTE	$22
		.BYTE	$F8,$9E,$03,$F8
		.BYTE	$F8,$AE,$03,$00
_sprA07_04:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$24
_sprA07_04_A:
		.BYTE	$02,$8A,$02,$F8
		.BYTE	$02,$9A,$02,$00
		.BYTE	$F2,$8E,$02,$F8
		.BYTE	$F2,$9E,$02,$00
_sprA07_06:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$24
_sprA07_06_A:
		.BYTE	$02,$8A,$42,$00
		.BYTE	$02,$9A,$42,$F8
		.BYTE	$F2,$8E,$42,$00
		.BYTE	$F2,$9E,$42,$F8
_sprA07_07:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$24
		.BYTE	$04,$9A,$02,$00
		.BYTE	$04,$9A,$42,$F8
		.BYTE	$F4,$9E,$02,$00
		.BYTE	$F4,$9E,$42,$F8
_sprA07_08:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$24
_sprA07_08_A:
		.BYTE	$02,$8C,$42,$00
		.BYTE	$02,$9C,$42,$F8
		.BYTE	$F2,$A8,$42,$00
		.BYTE	$F2,$B8,$42,$F8
_sprA07_09:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$24
_sprA07_09_A:
		.BYTE	$03,$AC,$02,$F8
		.BYTE	$03,$AC,$42,$00
		.BYTE	$F3,$AA,$42,$00
		.BYTE	$F3,$B8,$42,$F8
_sprA07_0A:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$24
_sprA07_0A_A:
		.BYTE	$02,$8C,$02,$F8
		.BYTE	$02,$9C,$02,$00
		.BYTE	$F2,$AA,$42,$00
		.BYTE	$F2,$BA,$42,$F8
_sprA07_0B:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$83
		.WORD	_sprA07_09_A
		.BYTE	$21
		.BYTE	$F3,$BA,$42,$F8
_sprA07_0C:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$82
		.WORD	_sprA07_04_A
		.BYTE	$22
		.BYTE	$F2,$88,$02,$F8
		.BYTE	$F2,$98,$02,$00
_sprA07_0E:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$82
		.WORD	_sprA07_06_A
		.BYTE	$22
		.BYTE	$F2,$88,$42,$00
		.BYTE	$F2,$98,$42,$F8
_sprA07_0F:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$24
		.BYTE	$03,$9A,$02,$00
		.BYTE	$03,$9A,$42,$F8
		.BYTE	$F3,$98,$02,$00
		.BYTE	$F3,$98,$42,$F8
_sprA07_10:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$82
		.WORD	_sprA07_0A_A
		.BYTE	$22
		.BYTE	$F2,$A8,$02,$F8
		.BYTE	$F2,$B8,$02,$00
_sprA07_11:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$24
_sprA07_11_A:
		.BYTE	$03,$AC,$02,$F8
		.BYTE	$03,$AC,$42,$00
		.BYTE	$F3,$AA,$02,$F8
		.BYTE	$F3,$B8,$02,$00
_sprA07_12:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$82
		.WORD	_sprA07_08_A
		.BYTE	$22
		.BYTE	$F2,$AA,$02,$F8
		.BYTE	$F2,$BA,$02,$00
_sprA07_13:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$83
		.WORD	_sprA07_11_A
		.BYTE	$21
		.BYTE	$F3,$BA,$02,$00
_sprA07_14:
		.BYTE	$82
		.WORD	_sprA05_0C_A
		.BYTE	$24
_sprA07_14_A:
		.BYTE	$02,$8A,$02,$FA
		.BYTE	$02,$9A,$02,$02
		.BYTE	$F2,$8E,$02,$FA
		.BYTE	$F2,$9E,$02,$02
_sprA07_15:
		.BYTE	$82
		.WORD	_sprA05_0C_A
		.BYTE	$24
		.BYTE	$02,$8C,$42,$02
		.BYTE	$02,$9C,$42,$FA
		.BYTE	$F2,$A8,$42,$02
		.BYTE	$F2,$B8,$42,$FA
_sprA07_16:
		.BYTE	$82
		.WORD	_sprA05_0C_A
		.BYTE	$82
		.WORD	_sprA07_14_A
		.BYTE	$22
		.BYTE	$F2,$88,$02,$FA
		.BYTE	$F2,$98,$02,$02
_sprA07_17:
		.BYTE	$82
		.WORD	_sprA05_0C_A
		.BYTE	$24
		.BYTE	$02,$8C,$02,$FA
		.BYTE	$02,$9C,$02,$02
		.BYTE	$F2,$A8,$02,$FA
		.BYTE	$F2,$B8,$02,$02
_sprA07_18:
		.BYTE	$23
		.BYTE	$00,$B4,$02,$F6
		.BYTE	$F0,$A8,$02,$F0
		.BYTE	$F0,$B8,$02,$F8
_sprA07_19:
		.BYTE	$22
		.BYTE	$F8,$AE,$02,$F0
		.BYTE	$F8,$BE,$02,$F8
_sprA07_1A:
		.BYTE	$23
		.BYTE	$00,$B4,$42,$02
		.BYTE	$F0,$A8,$42,$08
		.BYTE	$F0,$B8,$42,$00
_sprA07_1B:
		.BYTE	$22
		.BYTE	$F8,$AE,$42,$08
		.BYTE	$F8,$BE,$42,$00
_sprA07_1C:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$25
_sprA07_1C_A:
		.BYTE	$00,$C8,$02,$F8
		.BYTE	$00,$C8,$42,$00
		.BYTE	$F0,$C6,$02,$F8
		.BYTE	$F0,$C6,$42,$00
		.BYTE	$F4,$E6,$40,$F4
_sprA07_1D:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$26
		.BYTE	$F9,$D6,$00,$FD
		.BYTE	$F9,$E6,$00,$05
_sprA07_1D_A:
		.BYTE	$00,$EC,$02,$F8
		.BYTE	$00,$FC,$02,$00
		.BYTE	$F0,$EA,$02,$F8
		.BYTE	$F0,$FA,$02,$00
_sprA07_1E:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$26
		.BYTE	$F9,$D6,$00,$FA
		.BYTE	$F9,$E6,$00,$02
_sprA07_1E_A:
		.BYTE	$00,$E4,$02,$F8
		.BYTE	$00,$E4,$42,$00
		.BYTE	$F0,$C4,$02,$F8
		.BYTE	$F0,$C4,$42,$00
_sprA07_1F:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$26
		.BYTE	$F9,$D6,$40,$FB
		.BYTE	$F9,$E6,$40,$F3
_sprA07_1F_A:
		.BYTE	$00,$EC,$42,$00
		.BYTE	$00,$FC,$42,$F8
		.BYTE	$F0,$EA,$42,$00
		.BYTE	$F0,$FA,$42,$F8
_sprA07_20:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$84
		.WORD	_sprA07_1C_A
		.BYTE	$21
		.BYTE	$F4,$E8,$40,$F4
_sprA07_21:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$02
		.BYTE	$F9,$D8,$00,$FD
		.BYTE	$F9,$E8,$00,$05
		.BYTE	$A4
		.WORD	_sprA07_1D_A
_sprA07_22:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$02
		.BYTE	$F9,$D8,$00,$FA
		.BYTE	$F9,$E8,$00,$02
		.BYTE	$A4
		.WORD	_sprA07_1E_A
_sprA07_23:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$02
		.BYTE	$F9,$D8,$40,$FB
		.BYTE	$F9,$E8,$40,$F3
		.BYTE	$A4
		.WORD	_sprA07_1F_A
_sprA07_24:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$26
_sprA07_24_A:
		.BYTE	$00,$F6,$02,$F8
		.BYTE	$00,$F6,$42,$00
		.BYTE	$F0,$F4,$02,$F8
		.BYTE	$F0,$F4,$42,$00
		.BYTE	$E9,$D6,$40,$00
		.BYTE	$E9,$E6,$40,$F8
_sprA07_25:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$26
		.BYTE	$EE,$D6,$00,$FA
		.BYTE	$EE,$E6,$00,$02
_sprA07_25_A:
		.BYTE	$00,$CC,$02,$F8
		.BYTE	$00,$DC,$02,$00
		.BYTE	$F0,$CA,$02,$F8
		.BYTE	$F0,$DA,$02,$00
_sprA07_26:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$26
		.BYTE	$ED,$D6,$00,$F9
		.BYTE	$ED,$E6,$00,$01
_sprA07_26_A:
		.BYTE	$00,$E4,$02,$F8
		.BYTE	$00,$E4,$42,$00
		.BYTE	$F0,$D4,$02,$F8
		.BYTE	$F0,$D4,$42,$00
_sprA07_27:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$26
		.BYTE	$EE,$D6,$40,$FE
		.BYTE	$EE,$E6,$40,$F6
_sprA07_27_A:
		.BYTE	$00,$CC,$42,$00
		.BYTE	$00,$DC,$42,$F8
		.BYTE	$F0,$CA,$42,$00
		.BYTE	$F0,$DA,$42,$F8
_sprA07_28:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$84
		.WORD	_sprA07_24_A
		.BYTE	$22
		.BYTE	$E9,$D8,$40,$00
		.BYTE	$E9,$E8,$40,$F8
_sprA07_29:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$02
		.BYTE	$EE,$D8,$00,$FA
		.BYTE	$EE,$E8,$00,$02
		.BYTE	$A4
		.WORD	_sprA07_25_A
_sprA07_2A:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$02
		.BYTE	$ED,$D8,$00,$F9
		.BYTE	$ED,$E8,$00,$01
		.BYTE	$A4
		.WORD	_sprA07_26_A
_sprA07_2B:
		.BYTE	$82
		.WORD	_sprA05_04_A
		.BYTE	$02
		.BYTE	$EE,$D8,$40,$FE
		.BYTE	$EE,$E8,$40,$F6
		.BYTE	$A4
		.WORD	_sprA07_27_A
_sprA07_2C:
		.BYTE	$82
		.WORD	_sprA05_0C_A
		.BYTE	$26
		.BYTE	$00,$F6,$02,$FA
		.BYTE	$00,$F6,$42,$02
		.BYTE	$F0,$F4,$02,$FA
		.BYTE	$F0,$F4,$42,$02
		.BYTE	$E9,$D6,$40,$02
		.BYTE	$E9,$E6,$40,$FA
_sprA07_2D:
		.BYTE	$82
		.WORD	_sprA05_0C_A
		.BYTE	$26
		.BYTE	$00,$CC,$02,$FA
		.BYTE	$00,$DC,$02,$02
		.BYTE	$EE,$D6,$00,$FC
		.BYTE	$EE,$E6,$00,$04
		.BYTE	$F0,$CA,$02,$FA
		.BYTE	$F0,$DA,$02,$02
_sprA07_2E:
		.BYTE	$82
		.WORD	_sprA05_0C_A
		.BYTE	$26
		.BYTE	$00,$E4,$02,$FA
		.BYTE	$00,$E4,$42,$02
		.BYTE	$ED,$D6,$00,$FB
		.BYTE	$ED,$E6,$00,$03
		.BYTE	$F0,$D4,$02,$FA
		.BYTE	$F0,$D4,$42,$02
_sprA07_2F:
		.BYTE	$82
		.WORD	_sprA05_0C_A
		.BYTE	$26
		.BYTE	$00,$CC,$42,$02
		.BYTE	$00,$DC,$42,$FA
		.BYTE	$EE,$D6,$40,$00
		.BYTE	$EE,$E6,$40,$F8
		.BYTE	$F0,$CA,$42,$02
		.BYTE	$F0,$DA,$42,$FA
_sprA07_30:
		.BYTE	$23
		.BYTE	$00,$B4,$02,$F8
		.BYTE	$F0,$CA,$42,$F8
		.BYTE	$F0,$DA,$42,$F0
_sprA07_31:
		.BYTE	$22
		.BYTE	$F8,$CE,$42,$F8
		.BYTE	$F8,$DE,$42,$F0
_sprA07_32:
		.BYTE	$23
		.BYTE	$00,$B4,$42,$00
		.BYTE	$F0,$CA,$02,$00
		.BYTE	$F0,$DA,$02,$08
_sprA07_33:
		.BYTE	$22
		.BYTE	$F8,$CE,$02,$00
		.BYTE	$F8,$DE,$02,$08
_sprA07_34:
		.BYTE	$22
		.BYTE	$08,$3E,$40,$F8
		.BYTE	$08,$3E,$00,$00
_sprA07_35:
		.BYTE	$21
		.BYTE	$F8,$F8,$02,$FC
_sprA07_36:
		.BYTE	$23
		.BYTE	$F4,$F8,$02,$FC
		.BYTE	$FC,$E0,$02,$F8
		.BYTE	$FC,$E0,$42,$00
_sprA07_37:
		.BYTE	$2B
		.BYTE	$00,$E0,$02,$F8
		.BYTE	$00,$E0,$42,$00
		.BYTE	$F1,$F8,$02,$FC
_sprA07_37_A:
		.BYTE	$F4,$E2,$82,$F8
		.BYTE	$F4,$E2,$C2,$00
		.BYTE	$F7,$E2,$82,$F8
		.BYTE	$F7,$E2,$C2,$00
_sprA07_37_B:
		.BYTE	$FA,$E2,$82,$F8
		.BYTE	$FA,$E2,$C2,$00
		.BYTE	$FD,$E2,$82,$F8
		.BYTE	$FD,$E2,$C2,$00
_sprA07_38:
		.BYTE	$09
		.BYTE	$02,$E0,$02,$F8
		.BYTE	$02,$E0,$42,$00
		.BYTE	$EE,$F8,$02,$FC
		.BYTE	$F2,$E2,$82,$F8
		.BYTE	$F2,$E2,$C2,$00
		.BYTE	$FE,$E2,$82,$F8
		.BYTE	$FE,$E2,$C2,$00
_sprA07_38_A:
		.BYTE	$F6,$E2,$82,$F8
		.BYTE	$F6,$E2,$C2,$00
		.BYTE	$A2
		.WORD	_sprA07_37_B
_sprA07_39:
		.BYTE	$09
		.BYTE	$00,$E2,$82,$F8
		.BYTE	$00,$E2,$C2,$00
		.BYTE	$05,$E0,$02,$F8
		.BYTE	$05,$E0,$42,$00
		.BYTE	$EC,$F8,$02,$FC
		.BYTE	$F1,$E2,$82,$F8
		.BYTE	$F1,$E2,$C2,$00
_sprA07_39_A:
		.BYTE	$FB,$E2,$82,$F8
		.BYTE	$FB,$E2,$C2,$00
		.BYTE	$A2
		.WORD	_sprA07_38_A
_sprA07_3A:
		.BYTE	$09
		.BYTE	$01,$E2,$82,$F8
		.BYTE	$01,$E2,$C2,$00
		.BYTE	$07,$E0,$02,$F8
		.BYTE	$07,$E0,$42,$00
		.BYTE	$E9,$F8,$02,$FC
		.BYTE	$EF,$E2,$82,$F8
		.BYTE	$EF,$E2,$C2,$00
_sprA07_3A_A:
		.BYTE	$F5,$E2,$82,$F8
		.BYTE	$F5,$E2,$C2,$00
		.BYTE	$A2
		.WORD	_sprA07_39_A
_sprA07_3B:
		.BYTE	$09
		.BYTE	$03,$E2,$82,$F8
		.BYTE	$03,$E2,$C2,$00
		.BYTE	$0A,$E0,$02,$F8
		.BYTE	$0A,$E0,$42,$00
		.BYTE	$E7,$F8,$02,$FC
		.BYTE	$EE,$E2,$82,$F8
		.BYTE	$EE,$E2,$C2,$00
_sprA07_3B_A:
		.BYTE	$FC,$E2,$82,$F8
		.BYTE	$FC,$E2,$C2,$00
		.BYTE	$A2
		.WORD	_sprA07_3A_A
_sprA07_3C:
		.BYTE	$07
		.BYTE	$04,$E2,$82,$F8
		.BYTE	$04,$E2,$C2,$00
		.BYTE	$0C,$E0,$02,$F8
		.BYTE	$0C,$E0,$42,$00
		.BYTE	$E4,$F8,$02,$FC
		.BYTE	$EC,$E2,$82,$F8
		.BYTE	$EC,$E2,$C2,$00
		.BYTE	$82
		.WORD	_sprA07_37_A
		.BYTE	$A2
		.WORD	_sprA07_3B_A
_sprA07_3D:
		.BYTE	$2B
		.BYTE	$04,$E2,$82,$FA
		.BYTE	$04,$E2,$C2,$02
		.BYTE	$0C,$E0,$02,$FA
		.BYTE	$0C,$E0,$42,$02
		.BYTE	$E4,$F8,$02,$FE
		.BYTE	$EC,$E2,$82,$FA
		.BYTE	$EC,$E2,$C2,$02
		.BYTE	$F4,$E2,$82,$FA
		.BYTE	$F4,$E2,$C2,$02
		.BYTE	$FC,$E2,$82,$FA
		.BYTE	$FC,$E2,$C2,$02
_sprA07_3E:
		.BYTE	$24
		.BYTE	$F4,$C0,$02,$EC
		.BYTE	$F4,$D0,$02,$F4
		.BYTE	$F8,$F2,$C2,$F3
		.BYTE	$FD,$F2,$02,$F8
_sprA07_3F:
		.BYTE	$23
		.BYTE	$00,$B4,$02,$F8
		.BYTE	$F8,$C0,$02,$F0
		.BYTE	$F8,$D0,$02,$F8
_sprA07_40:
		.BYTE	$24
		.BYTE	$F4,$C0,$42,$0D
		.BYTE	$F4,$D0,$42,$05
		.BYTE	$F8,$F2,$82,$06
		.BYTE	$FD,$F2,$42,$01
_sprA07_41:
		.BYTE	$23
		.BYTE	$00,$B4,$42,$00
		.BYTE	$F8,$C0,$42,$08
		.BYTE	$F8,$D0,$42,$00
_sprA07_42:
		.BYTE	$02
		.BYTE	$FC,$EC,$00,$EE
		.BYTE	$FC,$FC,$00,$F6
		.BYTE	$66,$03
		.BYTE	$EE,$D8,$F2
		.BYTE	$EE,$E0,$FA
		.BYTE	$EE,$F0,$02
		.BYTE	$FE,$CE,$F2
		.BYTE	$FE,$DE,$FA
		.BYTE	$FE,$EE,$02
_sprA07_43:
		.BYTE	$64,$03
		.BYTE	$06,$AE,$FA
		.BYTE	$06,$BE,$02
		.BYTE	$F6,$E0,$FA
		.BYTE	$F6,$F0,$02
_sprA07_44:
		.BYTE	$A4
		.WORD	_sprA07_4B_G
_sprA07_45:
		.BYTE	$A5
		.WORD	_sprA07_4B_F
_sprA07_46:
		.BYTE	$A6
		.WORD	_sprA07_4B_E
_sprA07_47:
		.BYTE	$A7
		.WORD	_sprA07_4B_D
_sprA07_48:
		.BYTE	$A8
		.WORD	_sprA07_4B_C
_sprA07_49:
		.BYTE	$A9
		.WORD	_sprA07_4B_B
_sprA07_4A:
		.BYTE	$AA
		.WORD	_sprA07_4B_A
_sprA07_4B:
		.BYTE	$2B
		.BYTE	$6A,$C8,$00,$FC
_sprA07_4B_A:
		.BYTE	$7A,$C8,$00,$FC
_sprA07_4B_B:
		.BYTE	$8A,$C8,$00,$FC
_sprA07_4B_C:
		.BYTE	$9A,$C8,$00,$FC
_sprA07_4B_D:
		.BYTE	$AA,$C8,$00,$FC
_sprA07_4B_E:
		.BYTE	$BA,$C8,$00,$FC
_sprA07_4B_F:
		.BYTE	$CA,$C8,$00,$FC
_sprA07_4B_G:
		.BYTE	$DA,$C8,$00,$FC
		.BYTE	$EA,$C8,$00,$FC
		.BYTE	$F8,$EC,$00,$F8
		.BYTE	$F8,$FC,$00,$00
_sprA07_4C:
		.BYTE	$26
		.BYTE	$04,$96,$02,$F8
		.BYTE	$04,$96,$42,$00
		.BYTE	$F4,$94,$02,$F8
		.BYTE	$F4,$94,$42,$00
_sprA07_4C_A:
		.BYTE	$10,$E8,$00,$F8
		.BYTE	$10,$E8,$40,$00
_sprA07_4D:
		.BYTE	$44,$42
		.BYTE	$04,$8A,$00
		.BYTE	$04,$9A,$F8
		.BYTE	$F4,$88,$00
		.BYTE	$F4,$98,$F8
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_4E:
		.BYTE	$04
		.BYTE	$04,$92,$02,$F8
		.BYTE	$04,$92,$42,$00
		.BYTE	$F4,$90,$02,$F8
		.BYTE	$F4,$90,$42,$00
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_4F:
		.BYTE	$44,$02
		.BYTE	$04,$8A,$F8
		.BYTE	$04,$9A,$00
		.BYTE	$F4,$88,$F8
		.BYTE	$F4,$98,$00
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_50:
		.BYTE	$04
		.BYTE	$04,$86,$02,$F8
		.BYTE	$04,$86,$42,$00
		.BYTE	$F4,$84,$02,$F8
		.BYTE	$F4,$84,$42,$00
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_51:
		.BYTE	$44,$42
		.BYTE	$04,$8E,$00
		.BYTE	$04,$9E,$F8
		.BYTE	$F4,$8C,$00
		.BYTE	$F4,$9C,$F8
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_52:
		.BYTE	$04
		.BYTE	$04,$82,$02,$F8
		.BYTE	$04,$82,$42,$00
		.BYTE	$F4,$80,$02,$F8
		.BYTE	$F4,$80,$42,$00
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_53:
		.BYTE	$44,$02
		.BYTE	$04,$8E,$F8
		.BYTE	$04,$9E,$00
		.BYTE	$F4,$8C,$F8
		.BYTE	$F4,$9C,$00
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_54:
		.BYTE	$26
		.BYTE	$04,$96,$02,$FA
		.BYTE	$04,$96,$42,$02
		.BYTE	$F4,$94,$02,$FA
		.BYTE	$F4,$94,$42,$02
_sprA07_54_A:
		.BYTE	$10,$E8,$00,$FA
		.BYTE	$10,$E8,$40,$02
_sprA07_55:
		.BYTE	$44,$42
		.BYTE	$04,$8A,$02
		.BYTE	$04,$9A,$FA
		.BYTE	$F4,$88,$02
		.BYTE	$F4,$98,$FA
		.BYTE	$A2
		.WORD	_sprA07_54_A
_sprA07_56:
		.BYTE	$04
		.BYTE	$04,$92,$02,$FA
		.BYTE	$04,$92,$42,$02
		.BYTE	$F4,$90,$02,$FA
		.BYTE	$F4,$90,$42,$02
		.BYTE	$A2
		.WORD	_sprA07_54_A
_sprA07_57:
		.BYTE	$44,$02
		.BYTE	$04,$8A,$FA
		.BYTE	$04,$9A,$02
		.BYTE	$F4,$88,$FA
		.BYTE	$F4,$98,$02
		.BYTE	$A2
		.WORD	_sprA07_54_A
_sprA07_58:
		.BYTE	$64,$02
		.BYTE	$ED,$C2,$F3
		.BYTE	$ED,$D2,$FB
		.BYTE	$FD,$C4,$F3
		.BYTE	$FD,$D4,$FB
_sprA07_59:
		.BYTE	$22
		.BYTE	$FC,$C6,$02,$F3
		.BYTE	$FC,$D6,$02,$FB
_sprA07_5A:
		.BYTE	$64,$42
		.BYTE	$ED,$C2,$06
		.BYTE	$ED,$D2,$FE
		.BYTE	$FD,$C4,$06
		.BYTE	$FD,$D4,$FE
_sprA07_5B:
		.BYTE	$22
		.BYTE	$FC,$C6,$42,$06
		.BYTE	$FC,$D6,$42,$FE
_sprA07_5C:
		.BYTE	$02
		.BYTE	$04,$E2,$02,$F8
		.BYTE	$F4,$E0,$02,$F8
		.BYTE	$82
		.WORD	_sprA07_5E_A
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_5D:
		.BYTE	$02
		.BYTE	$04,$E2,$42,$00
		.BYTE	$F4,$E0,$42,$00
		.BYTE	$82
		.WORD	_sprA07_5E_B
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_5E:
		.BYTE	$04
_sprA07_5E_A:
		.BYTE	$04,$F2,$02,$00
		.BYTE	$F4,$F0,$02,$00
_sprA07_5E_B:
		.BYTE	$04,$F2,$42,$F8
		.BYTE	$F4,$F0,$42,$F8
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_5F:
		.BYTE	$02
		.BYTE	$04,$E6,$02,$F8
		.BYTE	$F4,$E4,$02,$F8
		.BYTE	$82
		.WORD	_sprA07_61_A
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_60:
		.BYTE	$02
		.BYTE	$04,$E6,$42,$00
		.BYTE	$F4,$E4,$42,$00
		.BYTE	$82
		.WORD	_sprA07_61_B
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_61:
		.BYTE	$04
_sprA07_61_A:
		.BYTE	$04,$F6,$02,$00
		.BYTE	$F4,$F4,$02,$00
_sprA07_61_B:
		.BYTE	$04,$F6,$42,$F8
		.BYTE	$F4,$F4,$42,$F8
		.BYTE	$A2
		.WORD	_sprA07_4C_A
_sprA07_62:
		.BYTE	$22
		.BYTE	$FA,$48,$00,$FA
		.BYTE	$FC,$48,$00,$FF
_sprA07_63:
		.BYTE	$23
		.BYTE	$F4,$58,$00,$FC
		.BYTE	$FA,$58,$00,$00
		.BYTE	$FA,$58,$00,$F8
_sprA07_64:
		.BYTE	$65,$00
		.BYTE	$E7,$58,$F6
		.BYTE	$E8,$58,$02
		.BYTE	$F4,$58,$F1
		.BYTE	$F7,$58,$08
		.BYTE	$FD,$58,$FC
_sprA07_65:
		.BYTE	$65,$00
		.BYTE	$05,$48,$FC
		.BYTE	$E4,$48,$F4
		.BYTE	$E5,$48,$06
		.BYTE	$F7,$48,$EE
		.BYTE	$FC,$48,$0F
_sprA07_66:
		.BYTE	$24
_sprA07_66_A:
		.BYTE	$00,$AA,$00,$F8
		.BYTE	$00,$BA,$00,$00
		.BYTE	$F0,$A8,$00,$F8
		.BYTE	$F0,$B8,$00,$00
_sprA07_67:
		.BYTE	$24
_sprA07_67_A:
		.BYTE	$00,$AA,$40,$01
		.BYTE	$00,$BA,$40,$F9
		.BYTE	$F0,$A8,$40,$01
		.BYTE	$F0,$B8,$40,$F9
_sprA07_68:
		.BYTE	$82
		.WORD	_sprA07_66_A
		.BYTE	$22
		.BYTE	$F0,$C8,$40,$00
		.BYTE	$F0,$D8,$40,$F8
_sprA07_69:
		.BYTE	$82
		.WORD	_sprA07_67_A
		.BYTE	$22
		.BYTE	$F0,$C8,$00,$F9
		.BYTE	$F0,$D8,$00,$01
_sprA07_6A:
		.BYTE	$24
_sprA07_6A_A:
		.BYTE	$00,$AE,$00,$F8
		.BYTE	$00,$AE,$40,$00
		.BYTE	$F0,$BC,$00,$00
		.BYTE	$F0,$BC,$40,$F8
_sprA07_6B:
		.BYTE	$82
		.WORD	_sprA07_6A_A
		.BYTE	$22
		.BYTE	$F0,$AC,$00,$F8
		.BYTE	$F0,$AC,$40,$00
_sprA07_6C:
		.BYTE	$21
		.BYTE	$FC,$A6,$02,$FC
_sprA07_6D:
		.BYTE	$21
		.BYTE	$FC,$A4,$42,$FC
_sprA07_6E:
		.BYTE	$21
		.BYTE	$FC,$A2,$42,$FC
_sprA07_6F:
		.BYTE	$21
		.BYTE	$FC,$A4,$02,$FC
_sprA07_70:
		.BYTE	$21
		.BYTE	$FC,$B6,$02,$FC
_sprA07_71:
		.BYTE	$21
		.BYTE	$FC,$B4,$42,$FC
_sprA07_72:
		.BYTE	$21
		.BYTE	$FC,$B2,$42,$FC
_sprA07_73:
		.BYTE	$21
		.BYTE	$FC,$B4,$02,$FC
_sprA07_74:
		.BYTE	$21
		.BYTE	$FC,$B6,$02,$FE
_sprA07_75:
		.BYTE	$21
		.BYTE	$FC,$B4,$42,$FE
_sprA07_76:
		.BYTE	$21
		.BYTE	$FC,$B2,$42,$FE
_sprA07_77:
		.BYTE	$21
		.BYTE	$FC,$B4,$02,$FE
_sprA07_78:
		.BYTE	$21
		.BYTE	$02,$B4,$02,$FB
_sprA07_79:
		.BYTE	$21
		.BYTE	$02,$A4,$02,$FA
_sprA07_7A:
		.BYTE	$21
		.BYTE	$02,$B4,$42,$FE
_sprA07_7B:
		.BYTE	$21
		.BYTE	$02,$A4,$42,$FE
_sprA07_7C:
		.BYTE	$24
_sprA07_7C_A:
		.BYTE	$08,$B4,$00,$00
		.BYTE	$08,$B4,$40,$F8
		.BYTE	$F8,$A2,$00,$00
		.BYTE	$F8,$A2,$40,$F8
_sprA07_7D:
		.BYTE	$24
_sprA07_7D_A:
		.BYTE	$08,$84,$40,$00
		.BYTE	$08,$94,$40,$F8
_sprA07_7D_B:
		.BYTE	$F9,$82,$40,$00
		.BYTE	$F9,$92,$40,$F8
_sprA07_7E:
		.BYTE	$64,$40
		.BYTE	$08,$28,$00
		.BYTE	$08,$38,$F8
		.BYTE	$F8,$82,$00
		.BYTE	$F8,$92,$F8
_sprA07_7F:
		.BYTE	$82
		.WORD	_sprA07_83_A
		.BYTE	$A2
		.WORD	_sprA07_7D_B
_sprA07_80:
		.BYTE	$82
		.WORD	_sprA07_7C_A
		.BYTE	$22
		.BYTE	$F8,$B2,$00,$00
		.BYTE	$F8,$B2,$40,$F8
_sprA07_81:
		.BYTE	$82
		.WORD	_sprA07_7D_A
		.BYTE	$A2
		.WORD	_sprA07_83_B
_sprA07_82:
		.BYTE	$64,$00
		.BYTE	$08,$28,$F8
		.BYTE	$08,$38,$00
		.BYTE	$F8,$82,$F8
		.BYTE	$F8,$92,$00
_sprA07_83:
		.BYTE	$24
_sprA07_83_A:
		.BYTE	$08,$84,$00,$F8
		.BYTE	$08,$94,$00,$00
_sprA07_83_B:
		.BYTE	$F9,$82,$00,$F8
		.BYTE	$F9,$92,$00,$00
_sprA07_84:
		.BYTE	$22
		.BYTE	$F8,$E0,$00,$F8
		.BYTE	$F8,$F0,$00,$00
_sprA07_85:
		.BYTE	$22
		.BYTE	$F8,$A0,$00,$F8
		.BYTE	$F8,$B0,$00,$00
_sprA07_86:
		.BYTE	$49,$03
		.BYTE	$F0,$F8,$08
		.BYTE	$F8,$DC,$F8
		.BYTE	$F8,$EC,$00
		.BYTE	$08,$DE,$F8
		.BYTE	$08,$EE,$00
		.BYTE	$00,$EA,$00
		.BYTE	$E0,$E6,$00
		.BYTE	$E0,$F6,$F8
		.BYTE	$F0,$E8,$00
		.BYTE	$23
		.BYTE	$F0,$F8,$43,$F0
		.BYTE	$00,$EA,$43,$F8
		.BYTE	$F0,$E8,$43,$F8
_sprA07_87:
		.BYTE	$01
		.BYTE	$FA,$FC,$03,$01
		.BYTE	$AA
		.WORD	_sprA07_88_A
_sprA07_88:
		.BYTE	$2D
		.BYTE	$0A,$DA,$03,$00
		.BYTE	$0B,$CA,$03,$F8
_sprA07_88_A:
		.BYTE	$08,$C4,$03,$F8
		.BYTE	$08,$D4,$03,$00
		.BYTE	$08,$E4,$03,$08
		.BYTE	$08,$F4,$03,$10
		.BYTE	$E8,$C0,$03,$F8
		.BYTE	$E8,$D0,$03,$00
		.BYTE	$F8,$C2,$03,$F8
		.BYTE	$F8,$D2,$03,$00
		.BYTE	$F8,$E2,$03,$08
		.BYTE	$F8,$F2,$03,$10
		.BYTE	$06,$C6,$03,$FB
_sprA07_89:
		.BYTE	$03
_sprA07_89_A:
		.BYTE	$0E,$D8,$03,$01
		.BYTE	$15,$DA,$03,$01
		.BYTE	$16,$CA,$03,$F9
		.BYTE	$AB
		.WORD	_sprA07_88_A
_sprA07_8A:
		.BYTE	$05
_sprA07_8A_A:
		.BYTE	$06,$D6,$03,$03
		.BYTE	$16,$C8,$03,$FB
		.BYTE	$16,$D8,$03,$03
		.BYTE	$24,$DA,$03,$03
		.BYTE	$26,$CA,$03,$FB
		.BYTE	$AB
		.WORD	_sprA07_88_A
_sprA07_8B:
		.BYTE	$02
		.BYTE	$26,$80,$00,$FD
		.BYTE	$26,$90,$00,$05
		.BYTE	$85
		.WORD	_sprA07_8A_A
		.BYTE	$AB
		.WORD	_sprA07_88_A
_sprA07_8C:
		.BYTE	$02
		.BYTE	$16,$80,$00,$FB
		.BYTE	$16,$90,$00,$03
		.BYTE	$83
		.WORD	_sprA07_89_A
		.BYTE	$AB
		.WORD	_sprA07_88_A
_sprA07_8D:
		.BYTE	$04
		.BYTE	$0B,$80,$00,$F8
		.BYTE	$0B,$90,$00,$00
		.BYTE	$0B,$CA,$03,$F8
		.BYTE	$0B,$DA,$03,$FF
		.BYTE	$AB
		.WORD	_sprA07_88_A
_sprB07_C0:
		.BYTE	$29
		.BYTE	$D6,$EC,$00,$F0
		.BYTE	$D6,$FC,$00,$F8
		.BYTE	$DE,$C8,$00,$F4
_sprB07_C0_A:
		.BYTE	$EA,$D4,$03,$F4
		.BYTE	$EA,$E4,$03,$FC
		.BYTE	$EA,$F4,$03,$04
		.BYTE	$FA,$C6,$03,$04
		.BYTE	$FA,$D6,$03,$F4
		.BYTE	$FA,$E6,$03,$FC
_sprB07_C1:
		.BYTE	$03
		.BYTE	$DA,$EC,$00,$FA
		.BYTE	$DA,$FC,$00,$02
		.BYTE	$DF,$CC,$00,$F7
		.BYTE	$A6
		.WORD	_sprB07_C0_A
_sprB07_C2:
		.BYTE	$2A
		.BYTE	$E8,$EC,$00,$07
		.BYTE	$E8,$FC,$00,$0F
		.BYTE	$EC,$CA,$00,$01
		.BYTE	$EC,$CA,$00,$F9
_sprB07_C2_A:
		.BYTE	$EA,$D0,$03,$F4
		.BYTE	$EA,$E0,$03,$FC
		.BYTE	$EA,$F0,$03,$04
		.BYTE	$FA,$C2,$03,$04
		.BYTE	$FA,$D2,$03,$F4
		.BYTE	$FA,$E2,$03,$FC
_sprB07_C3:
		.BYTE	$04
		.BYTE	$EF,$CC,$40,$FD
		.BYTE	$F0,$DC,$40,$F7
		.BYTE	$FA,$EC,$00,$03
		.BYTE	$FA,$FC,$00,$0B
		.BYTE	$A6
		.WORD	_sprB07_C2_A
_sprB07_C4:
		.BYTE	$44,$00
		.BYTE	$02,$EC,$EF
		.BYTE	$02,$FC,$F7
		.BYTE	$F0,$C8,$F3
		.BYTE	$F8,$C8,$F3
		.BYTE	$83
		.WORD	_sprB07_C0_A
		.BYTE	$23
_sprB07_C4_A:
		.BYTE	$FA,$E6,$03,$FC
		.BYTE	$FA,$C4,$03,$F4
		.BYTE	$FA,$F6,$03,$04
_sprB07_C5:
		.BYTE	$44,$00
		.BYTE	$F0,$CC,$E7
		.BYTE	$F0,$DC,$EF
		.BYTE	$FA,$EC,$DE
		.BYTE	$FA,$FC,$E6
		.BYTE	$83
		.WORD	_sprB07_C0_A
		.BYTE	$A3
		.WORD	_sprB07_C4_A
_sprB07_C6:
		.BYTE	$44,$00
		.BYTE	$E8,$EC,$D9
		.BYTE	$E8,$FC,$E1
		.BYTE	$EC,$CA,$E6
		.BYTE	$EC,$CA,$EE
		.BYTE	$83
		.WORD	_sprB07_C2_A
		.BYTE	$23
_sprB07_C6_A:
		.BYTE	$FA,$E2,$03,$FC
		.BYTE	$FA,$C0,$03,$F4
		.BYTE	$FA,$F2,$03,$04
_sprB07_C7:
		.BYTE	$03
		.BYTE	$DB,$EC,$00,$E2
		.BYTE	$DB,$FC,$00,$EA
		.BYTE	$DF,$CC,$40,$EF
		.BYTE	$83
		.WORD	_sprB07_C2_A
		.BYTE	$A3
		.WORD	_sprB07_C6_A
_sprB07_C8:
		.BYTE	$A6
		.WORD	_sprB07_C9_A
_sprB07_C9:
		.BYTE	$29
		.BYTE	$02,$EC,$00,$F0
		.BYTE	$02,$FC,$00,$F8
		.BYTE	$FF,$C8,$00,$F4
_sprB07_C9_A:
		.BYTE	$EA,$D8,$03,$F4
		.BYTE	$EA,$E8,$03,$FC
		.BYTE	$EA,$F8,$03,$04
		.BYTE	$FA,$DA,$03,$F4
		.BYTE	$FA,$EA,$03,$FC
		.BYTE	$FA,$FA,$03,$04
_sprB07_CA:
		.BYTE	$03
		.BYTE	$FF,$C8,$00,$F6
		.BYTE	$02,$EC,$00,$F2
		.BYTE	$02,$FC,$00,$FA
		.BYTE	$66,$03
		.BYTE	$EA,$D8,$F6
		.BYTE	$EA,$E8,$FE
		.BYTE	$EA,$F8,$06
		.BYTE	$FA,$DA,$F6
		.BYTE	$FA,$EA,$FE
		.BYTE	$FA,$FA,$06
