
_sprA00_00:
		.BYTE	$0C
		.BYTE	$00,$86,$02,$E8
		.BYTE	$00,$96,$02,$F0
		.BYTE	$00,$A6,$02,$F8
		.BYTE	$00,$B6,$02,$00
		.BYTE	$00,$C6,$02,$08
		.BYTE	$00,$D6,$02,$10
		.BYTE	$F0,$84,$02,$E8
		.BYTE	$F0,$94,$02,$F0
		.BYTE	$F0,$A4,$02,$F8
		.BYTE	$F0,$B4,$02,$00
		.BYTE	$F0,$C4,$02,$08
		.BYTE	$F0,$D4,$02,$10
_sprA00_01:
		.BYTE	$0C
		.BYTE	$00,$82,$02,$E8
		.BYTE	$00,$92,$02,$F0
		.BYTE	$00,$A2,$02,$F8
		.BYTE	$00,$B2,$02,$00
		.BYTE	$00,$C2,$02,$08
		.BYTE	$00,$D2,$02,$10
		.BYTE	$F0,$80,$02,$E8
		.BYTE	$F0,$90,$02,$F0
		.BYTE	$F0,$A0,$02,$F8
		.BYTE	$F0,$B0,$02,$00
		.BYTE	$F0,$C0,$02,$08
		.BYTE	$F0,$D0,$02,$10
_sprA00_02:
		.BYTE	$04
		.BYTE	$00,$8A,$03,$F8
		.BYTE	$00,$8A,$43,$00
		.BYTE	$F0,$88,$03,$F8
		.BYTE	$F0,$88,$43,$00
_sprA00_03:
		.BYTE	$04
		.BYTE	$00,$8E,$03,$F8
		.BYTE	$00,$8E,$43,$00
		.BYTE	$F0,$8C,$03,$F8
		.BYTE	$F0,$8C,$43,$00
_sprA00_04:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.WORD	_sprA03_0A_B
_sprA00_04_A:
		.BYTE	$02
		.BYTE	$00,$5E,$00,$00
		.BYTE	$00,$5E,$40,$F8
_sprA00_0B:
		.BYTE	$82
		.WORD	_sprA00_0B_A
		.WORD	_sprA00_0B_B
_sprA00_0B_A:
		.BYTE	$02
		.BYTE	$00,$6E,$00,$FE
		.BYTE	$00,$7E,$00,$06
_sprA00_0B_B:
		.BYTE	$02
		.BYTE	$F0,$C8,$00,$FE
		.BYTE	$F0,$D8,$00,$06
_sprA00_0C:
		.BYTE	$82
		.WORD	_sprA00_0C_A
		.WORD	_sprA00_0C_B
_sprA00_0C_A:
		.BYTE	$02
		.BYTE	$00,$EC,$00,$F8
		.BYTE	$00,$EC,$40,$00
_sprA00_0C_B:
		.BYTE	$02
		.BYTE	$F0,$E0,$00,$F8
		.BYTE	$F0,$F0,$00,$00
_sprA00_0D:
		.BYTE	$82
		.WORD	_sprA00_0D_A
		.WORD	_sprA00_0F
_sprA00_0D_A:
		.BYTE	$02
		.BYTE	$00,$6E,$40,$FA
		.BYTE	$00,$7E,$40,$F2
_sprA00_0E:
		.BYTE	$82
		.WORD	_sprA00_45
		.WORD	_sprA03_02_B
_sprA00_0F:
		.BYTE	$02
		.BYTE	$F0,$C8,$40,$FA
		.BYTE	$F0,$D8,$40,$F2
_sprA00_10:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.WORD	_sprA03_2A_B
_sprA00_17:
		.BYTE	$82
		.WORD	_sprA00_0B_A
		.WORD	_sprA00_17_B
_sprA00_17_B:
		.BYTE	$02
		.BYTE	$F0,$CC,$00,$FE
		.BYTE	$F0,$DC,$00,$06
_sprA00_18:
		.BYTE	$82
		.WORD	_sprA00_0C_A
		.WORD	_sprA00_18_B
_sprA00_18_B:
		.BYTE	$02
		.BYTE	$F0,$E4,$00,$F8
		.BYTE	$F0,$F4,$00,$00
_sprA00_19:
		.BYTE	$82
		.WORD	_sprA00_0D_A
		.WORD	_sprA00_1B
_sprA00_1A:
		.BYTE	$82
		.WORD	_sprA00_45
		.WORD	_sprA03_22_B
_sprA00_1B:
		.BYTE	$02
		.BYTE	$F0,$CC,$40,$FA
		.BYTE	$F0,$DC,$40,$F2
_sprA00_1C:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.WORD	_sprA03_3A_B
_sprA00_23:
		.BYTE	$82
		.WORD	_sprA00_0B_A
		.WORD	_sprA00_23_B
_sprA00_23_B:
		.BYTE	$02
		.BYTE	$F0,$CE,$00,$FE
		.BYTE	$F0,$DE,$00,$06
_sprA00_24:
		.BYTE	$82
		.WORD	_sprA00_0C_A
		.WORD	_sprA00_24_B
_sprA00_24_B:
		.BYTE	$02
		.BYTE	$F0,$E6,$00,$F8
		.BYTE	$F0,$F6,$00,$00
_sprA00_25:
		.BYTE	$82
		.WORD	_sprA00_0D_A
		.WORD	_sprA00_27
_sprA00_26:
		.BYTE	$82
		.WORD	_sprA00_45
		.WORD	_sprA03_32_B
_sprA00_27:
		.BYTE	$02
		.BYTE	$F0,$CE,$40,$FA
		.BYTE	$F0,$DE,$40,$F2
_sprA00_28:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.WORD	_sprA03_1A_B
_sprA00_2F:
		.BYTE	$82
		.WORD	_sprA00_0B_A
		.WORD	_sprA00_2F_B
_sprA00_2F_B:
		.BYTE	$02
		.BYTE	$F0,$CA,$00,$FE
		.BYTE	$F0,$DA,$00,$06
_sprA00_30:
		.BYTE	$82
		.WORD	_sprA00_0C_A
		.WORD	_sprA00_30_B
_sprA00_30_B:
		.BYTE	$02
		.BYTE	$F0,$E2,$00,$F8
		.BYTE	$F0,$F2,$00,$00
_sprA00_31:
		.BYTE	$82
		.WORD	_sprA00_0D_A
		.WORD	_sprA00_33
_sprA00_32:
		.BYTE	$82
		.WORD	_sprA00_45
		.WORD	_sprA03_12_B
_sprA00_33:
		.BYTE	$02
		.BYTE	$F0,$CA,$40,$FA
		.BYTE	$F0,$DA,$40,$F2
_sprA00_3B:
		.BYTE	$82
		.WORD	_sprA00_0B_A
		.WORD	_sprA00_3B_B
_sprA00_3B_B:
		.BYTE	$02
		.BYTE	$F0,$EA,$00,$FE
		.BYTE	$F0,$FA,$00,$06
_sprA00_3C:
		.BYTE	$82
		.WORD	_sprA00_0C_A
		.WORD	_sprA00_3C_B
_sprA00_3C_B:
		.BYTE	$02
		.BYTE	$F0,$E8,$00,$F8
		.BYTE	$F0,$F8,$00,$00
_sprA00_3D:
		.BYTE	$82
		.WORD	_sprA00_0D_A
		.WORD	_sprA00_3F
_sprA00_3E:
		.BYTE	$82
		.WORD	_sprA00_45
		.WORD	_sprA03_42_B
_sprA00_3F:
		.BYTE	$02
		.BYTE	$F0,$EA,$40,$FA
		.BYTE	$F0,$FA,$40,$F2
_sprA00_40:
		.BYTE	$05
		.BYTE	$F4,$D3,$02,$04
		.BYTE	$F4,$D3,$02,$F4
		.BYTE	$F4,$E9,$02,$EC
		.BYTE	$F4,$ED,$02,$0C
		.BYTE	$F4,$F1,$02,$FC
_sprA00_41:
		.BYTE	$03
		.BYTE	$F4,$CB,$02,$FC
		.BYTE	$F4,$ED,$02,$F4
		.BYTE	$F4,$FB,$02,$04
_sprA00_42:
		.BYTE	$04
		.BYTE	$F4,$D3,$02,$F0
		.BYTE	$F4,$D7,$02,$F8
		.BYTE	$F4,$E5,$02,$08
		.BYTE	$F4,$E7,$02,$00
_sprA00_43:
		.BYTE	$07
		.BYTE	$F4,$DB,$02,$EC
		.BYTE	$F4,$E5,$02,$14
		.BYTE	$F4,$E5,$02,$F4
		.BYTE	$F4,$E7,$02,$0C
		.BYTE	$F4,$EF,$02,$FC
		.BYTE	$F4,$F1,$02,$04
		.BYTE	$F4,$F7,$02,$E4
_sprA00_44:
		.BYTE	$05
		.BYTE	$F4,$DB,$02,$04
		.BYTE	$F4,$E1,$02,$EC
		.BYTE	$F4,$E7,$02,$F4
		.BYTE	$F4,$EF,$02,$0C
		.BYTE	$F4,$F3,$02,$FC
_sprA00_45:
		.BYTE	$02
		.BYTE	$00,$EE,$00,$F8
		.BYTE	$00,$EE,$40,$00
_sprA00_46:
		.BYTE	$06
		.BYTE	$F0,$DB,$02,$F4
		.BYTE	$F0,$FB,$02,$04
		.BYTE	$00,$FD,$02,$04
		.BYTE	$00,$DD,$02,$F4
		.BYTE	$00,$ED,$02,$FC
		.BYTE	$F0,$EB,$02,$FC
_sprA00_47:
		.BYTE	$04
		.BYTE	$00,$E9,$02,$F8
		.BYTE	$00,$F9,$02,$00
		.BYTE	$F0,$F7,$02,$00
		.BYTE	$F0,$E7,$02,$F8
_sprA00_48:
		.BYTE	$04
		.BYTE	$00,$D9,$02,$00
		.BYTE	$00,$C9,$02,$F8
		.BYTE	$F0,$C7,$02,$F8
		.BYTE	$F0,$D7,$02,$00
_sprA00_49:
		.BYTE	$04
		.BYTE	$00,$B9,$02,$00
		.BYTE	$00,$A9,$02,$F8
		.BYTE	$F0,$A7,$02,$F8
		.BYTE	$F0,$B7,$02,$00
_sprA00_4A:
		.BYTE	$07
		.BYTE	$F0,$97,$02,$0C
		.BYTE	$F0,$87,$02,$04
		.BYTE	$00,$89,$02,$04
		.BYTE	$00,$79,$02,$FC
		.BYTE	$F0,$77,$02,$FC
		.BYTE	$00,$69,$02,$F4
		.BYTE	$F0,$67,$02,$F4
_sprA00_4B:
		.BYTE	$0B
		.BYTE	$F0,$9B,$00,$04
		.BYTE	$00,$8B,$00,$04
		.BYTE	$00,$7B,$00,$FC
		.BYTE	$00,$6B,$00,$F4
		.BYTE	$F0,$99,$02,$F4
		.BYTE	$F0,$17,$02,$0C
		.BYTE	$F0,$07,$02,$04
		.BYTE	$F0,$19,$02,$FC
		.BYTE	$00,$2B,$02,$04
		.BYTE	$00,$1B,$02,$FC
		.BYTE	$00,$CB,$02,$F4
_sprA00_4C:
		.BYTE	$0E
		.BYTE	$00,$CF,$01,$10
		.BYTE	$F0,$CD,$01,$10
		.BYTE	$F0,$BD,$01,$08
		.BYTE	$00,$BF,$01,$08
		.BYTE	$00,$AF,$01,$00
		.BYTE	$F0,$AD,$01,$00
		.BYTE	$F0,$9D,$01,$F8
		.BYTE	$00,$9F,$01,$F8
		.BYTE	$00,$8F,$01,$F0
		.BYTE	$F0,$8D,$01,$F0
		.BYTE	$F0,$7D,$01,$E8
		.BYTE	$00,$7F,$01,$E8
		.BYTE	$00,$6F,$01,$E0
		.BYTE	$F0,$6D,$01,$E0

_sprA02_00:
		.BYTE	$04
		.BYTE	$00,$A2,$22,$F8
		.BYTE	$00,$B2,$22,$00
		.BYTE	$F0,$A0,$22,$F8
		.BYTE	$F0,$B0,$22,$00
_sprA02_01:
		.BYTE	$82
		.WORD	_sprA02_01_A
		.WORD	_sprA02_01_B
_sprA02_01_A:
		.BYTE	$04
		.BYTE	$00,$82,$22,$F8
		.BYTE	$00,$92,$22,$00
		.BYTE	$F0,$80,$22,$F8
		.BYTE	$F0,$90,$22,$00
_sprA02_01_B:
		.BYTE	$01
		.BYTE	$EF,$94,$20,$F8
_sprA02_02:
		.BYTE	$82
		.WORD	_sprA02_01_A
		.WORD	_sprA02_02_B
_sprA02_02_B:
		.BYTE	$01
		.BYTE	$F1,$94,$20,$F4
_sprA02_03:
		.BYTE	$82
		.WORD	_sprA02_03_A
		.WORD	_sprA02_03_B
_sprA02_03_A:
		.BYTE	$02
		.BYTE	$00,$C2,$62,$00
		.BYTE	$00,$D2,$62,$F8
_sprA02_03_B:
		.BYTE	$02
		.BYTE	$F0,$C0,$62,$00
		.BYTE	$F0,$D0,$62,$F8
_sprA02_04:
		.BYTE	$82
		.WORD	_sprA02_03_A
		.WORD	_sprA02_04_B
_sprA02_04_B:
		.BYTE	$02
		.BYTE	$F1,$C0,$62,$00
		.BYTE	$F1,$D0,$62,$F8
_sprA02_05:
		.BYTE	$04
		.BYTE	$00,$E2,$22,$F8
		.BYTE	$00,$F2,$22,$00
		.BYTE	$F0,$E0,$22,$F8
		.BYTE	$F0,$F0,$22,$00
_sprA02_06:
		.BYTE	$04
		.BYTE	$00,$E6,$22,$F8
		.BYTE	$00,$F6,$22,$00
		.BYTE	$F0,$E4,$22,$F8
		.BYTE	$F0,$F4,$22,$00
_sprA02_07:
		.BYTE	$82
		.WORD	_sprA02_07_A
		.WORD	_sprA02_07_B
_sprA02_07_A:
		.BYTE	$03
		.BYTE	$08,$8A,$23,$F8
		.BYTE	$08,$9A,$23,$00
		.BYTE	$D9,$84,$21,$FA
_sprA02_07_B:
		.BYTE	$04
		.BYTE	$E8,$86,$23,$F8
		.BYTE	$E8,$96,$23,$00
		.BYTE	$F8,$88,$23,$F8
		.BYTE	$F8,$98,$23,$00
_sprA02_08:
		.BYTE	$07
		.BYTE	$07,$AA,$23,$F8
		.BYTE	$07,$BA,$23,$00
		.BYTE	$D7,$B4,$21,$FA
		.BYTE	$E7,$A6,$23,$F8
		.BYTE	$E7,$B6,$23,$00
		.BYTE	$F7,$A8,$23,$F8
		.BYTE	$F7,$B8,$23,$00
_sprA02_09:
		.BYTE	$82
		.WORD	_sprA02_09_A
		.WORD	_sprA02_07_B
_sprA02_09_A:
		.BYTE	$03
		.BYTE	$08,$CA,$23,$F8
		.BYTE	$08,$DA,$23,$00
		.BYTE	$D9,$84,$61,$FB
_sprA02_0A:
		.BYTE	$82
		.WORD	_sprA02_0A_A
		.WORD	_sprA02_0A_B
_sprA02_0A_A:
		.BYTE	$01
		.BYTE	$D8,$84,$01,$F7
_sprA02_0A_B:
		.BYTE	$06
		.BYTE	$08,$C8,$03,$F8
		.BYTE	$08,$D8,$03,$00
		.BYTE	$E8,$C4,$03,$F8
		.BYTE	$E8,$D4,$03,$00
		.BYTE	$F8,$C6,$03,$F8
		.BYTE	$F8,$D6,$03,$00
_sprA02_0B:
		.BYTE	$82
		.WORD	_sprA02_0B_A
		.WORD	_sprA02_0A_B
_sprA02_0B_A:
		.BYTE	$01
		.BYTE	$D8,$B4,$01,$F7
_sprA02_0C:
		.BYTE	$82
		.WORD	_sprA02_0C_A
		.WORD	_sprA02_0A_B
_sprA02_0C_A:
		.BYTE	$01
		.BYTE	$D8,$84,$41,$F8
_sprA02_0D:
		.BYTE	$82
		.WORD	_sprA02_0D_A
		.WORD	_sprA02_0A_B
_sprA02_0D_A:
		.BYTE	$01
		.BYTE	$D7,$B4,$41,$F8
_sprA02_0E:
		.BYTE	$06
		.BYTE	$00,$CC,$62,$00
		.BYTE	$00,$DC,$62,$F8
		.BYTE	$F0,$EA,$62,$00
		.BYTE	$F0,$FA,$62,$F8
		.BYTE	$F8,$D8,$60,$FA
		.BYTE	$F8,$E8,$60,$F2
_sprA02_0F:
		.BYTE	$06
		.BYTE	$00,$CC,$62,$00
		.BYTE	$00,$DC,$62,$F8
		.BYTE	$F0,$EA,$62,$00
		.BYTE	$F0,$FA,$62,$F8
		.BYTE	$F8,$D8,$60,$FA
		.BYTE	$F8,$E6,$60,$F2
_sprA02_10:
		.BYTE	$82
		.WORD	_sprA02_10_A
		.WORD	_sprA02_0F
_sprA02_10_A:
		.BYTE	$02
		.BYTE	$02,$58,$60,$EF
		.BYTE	$EF,$58,$60,$F3
_sprA02_11:
		.BYTE	$82
		.WORD	_sprA02_11_A
		.WORD	_sprA02_0E
_sprA02_11_A:
		.BYTE	$02
		.BYTE	$02,$48,$60,$EF
		.BYTE	$EF,$48,$60,$F3
_sprA02_12:
		.BYTE	$82
		.WORD	_sprA02_12_A
		.WORD	_sprA02_12_B
_sprA02_12_A:
		.BYTE	$02
		.BYTE	$EE,$D8,$60,$FB
		.BYTE	$EE,$E8,$60,$F3
_sprA02_12_B:
		.BYTE	$04
		.BYTE	$00,$CC,$62,$00
		.BYTE	$00,$DC,$62,$F8
		.BYTE	$F0,$CA,$62,$00
		.BYTE	$F0,$DA,$62,$F8
_sprA02_13:
		.BYTE	$82
		.WORD	_sprA02_13_A
		.WORD	_sprA02_12_B
_sprA02_13_A
		.BYTE	$02
		.BYTE	$EE,$D6,$60,$FB
		.BYTE	$EE,$E6,$60,$F3
_sprA02_14:
		.BYTE	$82
		.WORD	_sprA02_14_A
		.WORD	_sprA02_14_B
_sprA02_14_A:
		.BYTE	$02
		.BYTE	$00,$26,$20,$F8
		.BYTE	$00,$36,$20,$00
_sprA02_14_B:
		.BYTE	$02
		.BYTE	$F0,$18,$20,$F8
		.BYTE	$F0,$18,$60,$00
_sprA02_15:
		.BYTE	$82
		.WORD	_sprA02_15_A
		.WORD	_sprA02_15_B
_sprA02_15_A:
		.BYTE	$02
		.BYTE	$00,$24,$20,$F8
		.BYTE	$00,$34,$20,$00
_sprA02_15_B:
		.BYTE	$02
		.BYTE	$F1,$18,$20,$F8
		.BYTE	$F1,$18,$60,$00
_sprA02_16:
		.BYTE	$82
		.WORD	_sprA02_16_A
		.WORD	_sprA02_15_B
_sprA02_16_A:
		.BYTE	$02
		.BYTE	$00,$24,$60,$00
		.BYTE	$00,$34,$60,$F8
_sprA02_17:
		.BYTE	$82
		.WORD	_sprA02_17_A
		.WORD	_sprA02_17_B
_sprA02_17_A:
		.BYTE	$02
		.BYTE	$00,$28,$60,$00
		.BYTE	$00,$38,$60,$F8
_sprA02_17_B:
		.BYTE	$02
		.BYTE	$F0,$00,$60,$00
		.BYTE	$F0,$10,$60,$F8
_sprA02_18:
		.BYTE	$82
		.WORD	_sprA02_18_A
		.WORD	_sprA02_18_B
_sprA02_18_A:
		.BYTE	$02
		.BYTE	$00,$2A,$60,$00
		.BYTE	$00,$3A,$60,$F8
_sprA02_18_B:
		.BYTE	$02
		.BYTE	$F1,$00,$60,$00
		.BYTE	$F1,$10,$60,$F8
_sprA02_19:
		.BYTE	$82
		.WORD	_sprA02_1E_A
		.WORD	_sprA02_18_B
_sprA02_1A:
		.BYTE	$82
		.WORD	_sprA02_14_A
		.WORD	_sprA02_1A_B
_sprA02_1A_B:
		.BYTE	$02
		.BYTE	$F0,$08,$20,$F8
		.BYTE	$F0,$08,$60,$00
_sprA02_1B:
		.BYTE	$82
		.WORD	_sprA02_15_A
		.WORD	_sprA02_1B_B
_sprA02_1B_B:
		.BYTE	$02
		.BYTE	$F1,$08,$20,$F8
		.BYTE	$F1,$08,$60,$00
_sprA02_1C:
		.BYTE	$82
		.WORD	_sprA02_16_A
		.WORD	_sprA02_1B_B
_sprA02_1D:
		.BYTE	$82
		.WORD	_sprA02_1D_A
		.WORD	_sprA02_1D_B
_sprA02_1D_A:
		.BYTE	$02
		.BYTE	$00,$28,$20,$F8
		.BYTE	$00,$38,$20,$00
_sprA02_1D_B:
		.BYTE	$02
		.BYTE	$F0,$00,$20,$F8
		.BYTE	$F0,$10,$20,$00
_sprA02_1E:
		.BYTE	$82
		.WORD	_sprA02_1E_A
		.WORD	_sprA02_1E_B
_sprA02_1E_A:
		.BYTE	$02
		.BYTE	$00,$2A,$20,$F8
		.BYTE	$00,$3A,$20,$00
_sprA02_1E_B:
		.BYTE	$02
		.BYTE	$F1,$00,$20,$F8
		.BYTE	$F1,$10,$20,$00
_sprA02_1F:
		.BYTE	$82
		.WORD	_sprA02_18_A
		.WORD	_sprA02_1E_B
_sprA02_20:
		.BYTE	$82
		.WORD	_sprA02_14_A
		.WORD	_sprA02_20_B
_sprA02_20_B:
		.BYTE	$02
		.BYTE	$F0,$1A,$20,$F8
		.BYTE	$F0,$1A,$60,$00
_sprA02_21:
		.BYTE	$82
		.WORD	_sprA02_15_A
		.WORD	_sprA02_21_B
_sprA02_21_B:
		.BYTE	$02
		.BYTE	$F1,$1A,$20,$F8
		.BYTE	$F1,$1A,$60,$00
_sprA02_22:
		.BYTE	$82
		.WORD	_sprA02_16_A
		.WORD	_sprA02_21_B
_sprA02_23:
		.BYTE	$82
		.WORD	_sprA02_17_A
		.WORD	_sprA02_23_B
_sprA02_23_B:
		.BYTE	$02
		.BYTE	$F0,$02,$60,$00
		.BYTE	$F0,$12,$60,$F8
_sprA02_24:
		.BYTE	$82
		.WORD	_sprA02_18_A
		.WORD	_sprA02_24_B
_sprA02_24_B:
		.BYTE	$02
		.BYTE	$F1,$02,$60,$00
		.BYTE	$F1,$12,$60,$F8
_sprA02_25:
		.BYTE	$82
		.WORD	_sprA02_1E_A
		.WORD	_sprA02_24_B
_sprA02_26:
		.BYTE	$82
		.WORD	_sprA02_14_A
		.WORD	_sprA02_26_B
_sprA02_26_B:
		.BYTE	$02
		.BYTE	$F0,$0A,$20,$F8
		.BYTE	$F0,$0A,$60,$00
_sprA02_27:
		.BYTE	$82
		.WORD	_sprA02_15_A
		.WORD	_sprA02_27_B
_sprA02_27_B:
		.BYTE	$02
		.BYTE	$F1,$0A,$20,$F8
		.BYTE	$F1,$0A,$60,$00
_sprA02_28:
		.BYTE	$82
		.WORD	_sprA02_16_A
		.WORD	_sprA02_27_B
_sprA02_29:
		.BYTE	$82
		.WORD	_sprA02_1D_A
		.WORD	_sprA02_29_B
_sprA02_29_B:
		.BYTE	$02
		.BYTE	$F0,$02,$20,$F8
		.BYTE	$F0,$12,$20,$00
_sprA02_2A:
		.BYTE	$82
		.WORD	_sprA02_1E_A
		.WORD	_sprA02_2A_B
_sprA02_2A_B:
		.BYTE	$02
		.BYTE	$F1,$02,$20,$F8
		.BYTE	$F1,$12,$20,$00
_sprA02_2B:
		.BYTE	$82
		.WORD	_sprA02_18_A
		.WORD	_sprA02_2A_B
_sprA02_2C:
		.BYTE	$82
		.WORD	_sprA02_14_A
		.WORD	_sprA02_2C_B
_sprA02_2C_B:
		.BYTE	$02
		.BYTE	$F0,$1C,$20,$F8
		.BYTE	$F0,$1C,$60,$00
_sprA02_2D:
		.BYTE	$82
		.WORD	_sprA02_15_A
		.WORD	_sprA02_2D_B
_sprA02_2D_B:
		.BYTE	$02
		.BYTE	$F1,$1C,$20,$F8
		.BYTE	$F1,$1C,$60,$00
_sprA02_2E:
		.BYTE	$82
		.WORD	_sprA02_16_A
		.WORD	_sprA02_2D_B
_sprA02_2F:
		.BYTE	$82
		.WORD	_sprA02_17_A
		.WORD	_sprA02_2F_B
_sprA02_2F_B:
		.BYTE	$02
		.BYTE	$F0,$04,$60,$00
		.BYTE	$F0,$14,$60,$F8
_sprA02_30:
		.BYTE	$82
		.WORD	_sprA02_18_A
		.WORD	_sprA02_30_B
_sprA02_30_B:
		.BYTE	$02
		.BYTE	$F1,$04,$60,$00
		.BYTE	$F1,$14,$60,$F8
_sprA02_31:
		.BYTE	$82
		.WORD	_sprA02_1E_A
		.WORD	_sprA02_30_B
_sprA02_32:
		.BYTE	$82
		.WORD	_sprA02_14_A
		.WORD	_sprA02_32_B
_sprA02_32_B:
		.BYTE	$02
		.BYTE	$F0,$0C,$20,$F8
		.BYTE	$F0,$0C,$60,$00
_sprA02_33:
		.BYTE	$82
		.WORD	_sprA02_15_A
		.WORD	_sprA02_33_B
_sprA02_33_B:
		.BYTE	$02
		.BYTE	$F1,$0C,$20,$F8
		.BYTE	$F1,$0C,$60,$00
_sprA02_34:
		.BYTE	$82
		.WORD	_sprA02_16_A
		.WORD	_sprA02_33_B
_sprA02_35:
		.BYTE	$82
		.WORD	_sprA02_1D_A
		.WORD	_sprA02_35_B
_sprA02_35_B:
		.BYTE	$02
		.BYTE	$F0,$04,$20,$F8
		.BYTE	$F0,$14,$20,$00
_sprA02_36:
		.BYTE	$82
		.WORD	_sprA02_1E_A
		.WORD	_sprA02_36_B
_sprA02_36_B:
		.BYTE	$02
		.BYTE	$F1,$04,$20,$F8
		.BYTE	$F1,$14,$20,$00
_sprA02_37:
		.BYTE	$82
		.WORD	_sprA02_18_A
		.WORD	_sprA02_36_B
_sprA02_38:
		.BYTE	$82
		.WORD	_sprA02_14_A
		.WORD	_sprA02_38_B
_sprA02_38_B:
		.BYTE	$02
		.BYTE	$F0,$1E,$20,$F8
		.BYTE	$F0,$1E,$60,$00
_sprA02_39:
		.BYTE	$82
		.WORD	_sprA02_15_A
		.WORD	_sprA02_39_B
_sprA02_39_B:
		.BYTE	$02
		.BYTE	$F1,$1E,$20,$F8
		.BYTE	$F1,$1E,$60,$00
_sprA02_3A:
		.BYTE	$82
		.WORD	_sprA02_16_A
		.WORD	_sprA02_39_B
_sprA02_3B:
		.BYTE	$82
		.WORD	_sprA02_17_A
		.WORD	_sprA02_3B_B
_sprA02_3B_B:
		.BYTE	$02
		.BYTE	$F0,$06,$60,$00
		.BYTE	$F0,$16,$60,$F8
_sprA02_3C:
		.BYTE	$82
		.WORD	_sprA02_18_A
		.WORD	_sprA02_3C_B
_sprA02_3C_B:
		.BYTE	$02
		.BYTE	$F1,$06,$60,$00
		.BYTE	$F1,$16,$60,$F8
_sprA02_3D:
		.BYTE	$82
		.WORD	_sprA02_1E_A
		.WORD	_sprA02_3C_B
_sprA02_3E:
		.BYTE	$82
		.WORD	_sprA02_14_A
		.WORD	_sprA02_3E_B
_sprA02_3E_B:
		.BYTE	$02
		.BYTE	$F0,$0E,$20,$F8
		.BYTE	$F0,$0E,$60,$00
_sprA02_3F:
		.BYTE	$82
		.WORD	_sprA02_15_A
		.WORD	_sprA02_3F_B
_sprA02_3F_B:
		.BYTE	$02
		.BYTE	$F1,$0E,$20,$F8
		.BYTE	$F1,$0E,$60,$00
_sprA02_40:
		.BYTE	$82
		.WORD	_sprA02_16_A
		.WORD	_sprA02_3F_B
_sprA02_41:
		.BYTE	$82
		.WORD	_sprA02_1D_A
		.WORD	_sprA02_41_B
_sprA02_41_B:
		.BYTE	$02
		.BYTE	$F0,$06,$20,$F8
		.BYTE	$F0,$16,$20,$00
_sprA02_42:
		.BYTE	$82
		.WORD	_sprA02_1E_A
		.WORD	_sprA02_42_B
_sprA02_42_B:
		.BYTE	$02
		.BYTE	$F1,$06,$20,$F8
		.BYTE	$F1,$16,$20,$00
_sprA02_43:
		.BYTE	$82
		.WORD	_sprA02_18_A
		.WORD	_sprA02_42_B
_sprA02_44:
		.BYTE	$82
		.WORD	_sprA02_14_A
		.WORD	_sprA02_44_B
_sprA02_44_B:
		.BYTE	$02
		.BYTE	$F0,$32,$20,$F8
		.BYTE	$F0,$32,$60,$00
_sprA02_45:
		.BYTE	$82
		.WORD	_sprA02_15_A
		.WORD	_sprA02_45_B
_sprA02_45_B:
		.BYTE	$02
		.BYTE	$F1,$32,$20,$F8
		.BYTE	$F1,$32,$60,$00
_sprA02_46:
		.BYTE	$82
		.WORD	_sprA02_16_A
		.WORD	_sprA02_45_B
_sprA02_47:
		.BYTE	$82
		.WORD	_sprA02_17_A
		.WORD	_sprA02_47_B
_sprA02_47_B:
		.BYTE	$02
		.BYTE	$F0,$20,$60,$00
		.BYTE	$F0,$30,$60,$F8
_sprA02_48:
		.BYTE	$82
		.WORD	_sprA02_18_A
		.WORD	_sprA02_48_B
_sprA02_48_B:
		.BYTE	$02
		.BYTE	$F1,$20,$60,$00
		.BYTE	$F1,$30,$60,$F8
_sprA02_49:
		.BYTE	$82
		.WORD	_sprA02_1E_A
		.WORD	_sprA02_48_B
_sprA02_4A:
		.BYTE	$82
		.WORD	_sprA02_14_A
		.WORD	_sprA02_4A_B
_sprA02_4A_B:
		.BYTE	$02
		.BYTE	$F0,$22,$20,$F8
		.BYTE	$F0,$22,$60,$00
_sprA02_4B:
		.BYTE	$82
		.WORD	_sprA02_15_A
		.WORD	_sprA02_4B_B
_sprA02_4B_B:
		.BYTE	$02
		.BYTE	$F1,$22,$20,$F8
		.BYTE	$F1,$22,$60,$00
_sprA02_4C:
		.BYTE	$82
		.WORD	_sprA02_16_A
		.WORD	_sprA02_4B_B
_sprA02_4D:
		.BYTE	$82
		.WORD	_sprA02_1D_A
		.WORD	_sprA02_4D_B
_sprA02_4D_B:
		.BYTE	$02
		.BYTE	$F0,$20,$20,$F8
		.BYTE	$F0,$30,$20,$00
_sprA02_4E:
		.BYTE	$82
		.WORD	_sprA02_1E_A
		.WORD	_sprA02_4E_B
_sprA02_4E_B:
		.BYTE	$02
		.BYTE	$F1,$20,$20,$F8
		.BYTE	$F1,$30,$20,$00
_sprA02_4F:
		.BYTE	$82
		.WORD	_sprA02_18_A
		.WORD	_sprA02_4E_B
_sprA02_50:
		.BYTE	$82
		.WORD	_sprA02_50_A
		.WORD	_sprA02_50_B
_sprA02_50_A:
		.BYTE	$02
		.BYTE	$01,$4E,$20,$F8
		.BYTE	$01,$4E,$60,$00
_sprA02_50_B:
		.BYTE	$02
		.BYTE	$F4,$08,$20,$F8
		.BYTE	$F4,$08,$60,$00
_sprA02_51:
		.BYTE	$82
		.WORD	_sprA02_50_A
		.WORD	_sprA02_51_B
_sprA02_51_B:
		.BYTE	$02
		.BYTE	$F5,$08,$20,$F8
		.BYTE	$F5,$08,$60,$00
_sprA02_52:
		.BYTE	$82
		.WORD	_sprA02_50_A
		.WORD	_sprA02_52_B
_sprA02_52_B:
		.BYTE	$02
		.BYTE	$F4,$00,$60,$00
		.BYTE	$F4,$10,$60,$F8
_sprA02_53:
		.BYTE	$82
		.WORD	_sprA02_50_A
		.WORD	_sprA02_53_B
_sprA02_53_B:
		.BYTE	$02
		.BYTE	$F4,$0A,$20,$F8
		.BYTE	$F4,$0A,$60,$00
_sprA02_54:
		.BYTE	$82
		.WORD	_sprA02_50_A
		.WORD	_sprA02_54_B
_sprA02_54_B:
		.BYTE	$02
		.BYTE	$F5,$0A,$20,$F8
		.BYTE	$F5,$0A,$60,$00
_sprA02_55:
		.BYTE	$82
		.WORD	_sprA02_50_A
		.WORD	_sprA02_55_B
_sprA02_55_B:
		.BYTE	$02
		.BYTE	$F4,$02,$20,$F8
		.BYTE	$F4,$12,$20,$00
_sprA02_56:
		.BYTE	$82
		.WORD	_sprA02_56_A
		.WORD	_sprA02_56_B
_sprA02_56_A:
		.BYTE	$02
		.BYTE	$EF,$A8,$62,$00
		.BYTE	$EF,$B8,$62,$F8
_sprA02_56_B:
		.BYTE	$02
		.BYTE	$FF,$8C,$62,$00
		.BYTE	$FF,$9C,$62,$F8
_sprA02_57:
		.BYTE	$82
		.WORD	_sprA02_57_A
		.WORD	_sprA02_57_B
_sprA02_57_A:
		.BYTE	$03
		.BYTE	$00,$AC,$22,$F8
		.BYTE	$00,$AC,$62,$00
		.BYTE	$F0,$AA,$62,$00
_sprA02_57_B:
		.BYTE	$01
		.BYTE	$F0,$B8,$62,$F8
_sprA02_58:
		.BYTE	$82
		.WORD	_sprA02_58_A
		.WORD	_sprA02_58_B
_sprA02_58_A:
		.BYTE	$02
		.BYTE	$EF,$AA,$62,$00
		.BYTE	$EF,$BA,$62,$F8
_sprA02_58_B:
		.BYTE	$02
		.BYTE	$FF,$8C,$22,$F8
		.BYTE	$FF,$9C,$22,$00
_sprA02_59:
		.BYTE	$82
		.WORD	_sprA02_57_A
		.WORD	_sprA02_59_B
_sprA02_59_B:
		.BYTE	$01
		.BYTE	$F0,$BA,$62,$F8
_sprA02_5A:
		.BYTE	$82
		.WORD	_sprA02_5A_A
		.WORD	_sprA02_58_B
_sprA02_5A_A:
		.BYTE	$02
		.BYTE	$EF,$A8,$22,$F8
		.BYTE	$EF,$B8,$22,$00
_sprA02_5B:
		.BYTE	$82
		.WORD	_sprA02_5B_A
		.WORD	_sprA02_5B_B
_sprA02_5B_A:
		.BYTE	$03
		.BYTE	$00,$AC,$22,$F8
		.BYTE	$00,$AC,$62,$00
		.BYTE	$F0,$AA,$22,$F8
_sprA02_5B_B:
		.BYTE	$01
		.BYTE	$F0,$B8,$22,$00
_sprA02_5C:
		.BYTE	$82
		.WORD	_sprA02_5C_A
		.WORD	_sprA02_56_B
_sprA02_5C_A:
		.BYTE	$02
		.BYTE	$EF,$AA,$22,$F8
		.BYTE	$EF,$BA,$22,$00
_sprA02_5D:
		.BYTE	$82
		.WORD	_sprA02_5B_A
		.WORD	_sprA02_5D_B
_sprA02_5D_B:
		.BYTE	$01
		.BYTE	$F0,$BA,$22,$00
_sprA02_5E:
		.BYTE	$04
		.BYTE	$E8,$1C,$20,$F8
		.BYTE	$E8,$1C,$60,$00
		.BYTE	$F5,$5E,$23,$00
		.BYTE	$F5,$5E,$23,$FB
_sprA02_5F:
		.BYTE	$04
		.BYTE	$E8,$1E,$20,$F8
		.BYTE	$E8,$1E,$60,$00
		.BYTE	$F5,$5E,$23,$00
		.BYTE	$F5,$5E,$63,$F8
_sprA02_60:
		.BYTE	$82
		.WORD	_sprA02_60_A
		.WORD	_sprA02_60_B
_sprA02_60_A:
		.BYTE	$03
		.BYTE	$00,$A6,$23,$F8
		.BYTE	$00,$B6,$23,$00
		.BYTE	$00,$BA,$23,$F0
_sprA02_60_B:
		.BYTE	$02
		.BYTE	$F0,$A4,$23,$F8
		.BYTE	$F0,$B4,$23,$00
_sprA02_61:
		.BYTE	$82
		.WORD	_sprA02_61_A
		.WORD	_sprA02_61_B
_sprA02_61_A:
		.BYTE	$02
		.BYTE	$00,$86,$23,$F8
		.BYTE	$00,$96,$23,$00
_sprA02_61_B:
		.BYTE	$03
		.BYTE	$F0,$84,$23,$F8
		.BYTE	$F0,$94,$23,$00
		.BYTE	$F0,$BC,$23,$F0
_sprA02_62:
		.BYTE	$82
		.WORD	_sprA02_62_A
		.WORD	_sprA02_62_B
_sprA02_62_A:
		.BYTE	$03
		.BYTE	$00,$A6,$63,$00
		.BYTE	$00,$B6,$63,$F8
		.BYTE	$00,$BA,$63,$08
_sprA02_62_B:
		.BYTE	$02
		.BYTE	$F0,$A4,$63,$00
		.BYTE	$F0,$B4,$63,$F8
_sprA02_63:
		.BYTE	$82
		.WORD	_sprA02_63_A
		.WORD	_sprA02_63_B
_sprA02_63_A:
		.BYTE	$02
		.BYTE	$00,$86,$63,$00
		.BYTE	$00,$96,$63,$F8
_sprA02_63_B:
		.BYTE	$03
		.BYTE	$F0,$84,$63,$00
		.BYTE	$F0,$94,$63,$F8
		.BYTE	$F0,$BC,$63,$08
_sprA02_64:
		.BYTE	$82
		.WORD	_sprA02_61_A
		.WORD	_sprA02_64_B
_sprA02_64_B:
		.BYTE	$03
		.BYTE	$F0,$23,$23,$F8
		.BYTE	$F0,$25,$23,$00
		.BYTE	$F0,$9C,$23,$F0
_sprA02_65:
		.BYTE	$82
		.WORD	_sprA02_60_A
		.WORD	_sprA02_65_B
_sprA02_65_B:
		.BYTE	$02
		.BYTE	$F0,$27,$23,$F8
		.BYTE	$F0,$29,$23,$00
_sprA02_66:
		.BYTE	$82
		.WORD	_sprA02_63_A
		.WORD	_sprA02_66_B
_sprA02_66_B:
		.BYTE	$03
		.BYTE	$F0,$23,$63,$00
		.BYTE	$F0,$25,$63,$F8
		.BYTE	$F0,$9C,$63,$08
_sprA02_67:
		.BYTE	$82
		.WORD	_sprA02_62_A
		.WORD	_sprA02_67_B
_sprA02_67_B:
		.BYTE	$02
		.BYTE	$F0,$27,$63,$00
		.BYTE	$F0,$29,$63,$F8
_sprA02_68:
		.BYTE	$04
		.BYTE	$00,$A2,$23,$F8
		.BYTE	$00,$B2,$23,$00
		.BYTE	$F0,$3B,$23,$F8
		.BYTE	$F0,$3D,$23,$00
_sprA02_69:
		.BYTE	$02
		.BYTE	$F8,$AB,$23,$F8
		.BYTE	$F8,$BB,$23,$00
_sprA02_6A:
		.BYTE	$04
		.BYTE	$E0,$20,$20,$F8
		.BYTE	$E0,$30,$20,$00
		.BYTE	$F0,$4A,$20,$F8
		.BYTE	$F0,$5A,$20,$00
_sprA02_6B:
		.BYTE	$82
		.WORD	_sprA02_1D_A
		.WORD	_sprA02_6B_B
_sprA02_6B_B:
		.BYTE	$02
		.BYTE	$F2,$20,$20,$F8
		.BYTE	$F2,$30,$20,$00
_sprA02_6C:
		.BYTE	$83
		.WORD	_sprA02_14_A
		.WORD	_sprA02_4A_B
		.WORD	_sprA02_6C_C
_sprA02_6C_C:
		.BYTE	$02
		.BYTE	$F9,$AB,$23,$F8
		.BYTE	$F9,$BB,$23,$00
_sprA02_6D:
		.BYTE	$83
		.WORD	_sprA02_17_A
		.WORD	_sprA02_47_B
		.WORD	_sprA02_6D_C
_sprA02_6D_C:
		.BYTE	$02
		.BYTE	$F8,$AB,$23,$03
		.BYTE	$F8,$BB,$23,$0B
_sprA02_6E:
		.BYTE	$83
		.WORD	_sprA02_18_A
		.WORD	_sprA02_48_B
		.WORD	_sprA02_6E_C
_sprA02_6E_C:
		.BYTE	$02
		.BYTE	$F9,$AB,$23,$04
		.BYTE	$F9,$BB,$23,$0C
_sprA02_6F:
		.BYTE	$83
		.WORD	_sprA02_1E_A
		.WORD	_sprA02_48_B
		.WORD	_sprA02_6E_C
_sprA02_70:
		.BYTE	$83
		.WORD	_sprA02_1D_A
		.WORD	_sprA02_4D_B
		.WORD	_sprA02_70_C
_sprA02_70_C:
		.BYTE	$02
		.BYTE	$F8,$AB,$63,$F5
		.BYTE	$F8,$BB,$63,$ED
_sprA02_AD:
		.BYTE	$82
		.WORD	_sprA03_0E_A
		.WORD	_sprA02_AD_B
_sprA02_AD_B:
		.BYTE	$02
		.BYTE	$F0,$82,$00,$F8
		.BYTE	$F0,$92,$00,$00
_sprA02_AE:
		.BYTE	$82
		.WORD	_sprA02_AE_A
		.WORD	_sprA02_AE_B
_sprA02_AE_A:
		.BYTE	$02
		.BYTE	$00,$84,$00,$F8
		.BYTE	$00,$94,$00,$00
_sprA02_AE_B:
		.BYTE	$02
		.BYTE	$F1,$82,$00,$F8
		.BYTE	$F1,$92,$00,$00
_sprA02_AF:
		.BYTE	$82
		.WORD	_sprA02_AF_A
		.WORD	_sprA02_AE_B
_sprA02_AF_A:
		.BYTE	$02
		.BYTE	$00,$84,$40,$00
		.BYTE	$00,$94,$40,$F8
_sprA02_B0:
		.BYTE	$82
		.WORD	_sprA03_06_A
		.WORD	_sprA02_B0_B
_sprA02_B0_B:
		.BYTE	$02
		.BYTE	$F0,$82,$40,$00
		.BYTE	$F0,$92,$40,$F8
_sprA02_B1:
		.BYTE	$82
		.WORD	_sprA02_AF_A
		.WORD	_sprA02_B1_B
_sprA02_B1_B:
		.BYTE	$02
		.BYTE	$F1,$82,$40,$00
		.BYTE	$F1,$92,$40,$F8
_sprA02_B2:
		.BYTE	$82
		.WORD	_sprA02_AE_A
		.WORD	_sprA02_B1_B
_sprA02_B3:
		.BYTE	$01
		.BYTE	$FC,$6E,$41,$FD
_sprA02_B4:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.WORD	_sprA03_1A_B
_sprA02_B5:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.WORD	_sprA03_2A_B
_sprA02_B6:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.WORD	_sprA03_3A_B
_sprA02_B7:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.WORD	_sprA03_4A_B
_sprA02_B8:
		.BYTE	$04
		.BYTE	$E8,$4E,$80,$F8
		.BYTE	$E8,$4E,$C0,$00
		.BYTE	$F8,$4C,$80,$F8
		.BYTE	$F8,$4C,$C0,$00
_sprA02_B9:
		.BYTE	$82
		.WORD	_sprA02_B8
		.WORD	_sprA02_B9_B
_sprA02_B9_B:
		.BYTE	$02
		.BYTE	$F0,$48,$80,$06
		.BYTE	$F1,$48,$80,$F3
_sprA02_BA:
		.BYTE	$82
		.WORD	_sprA02_B8
		.WORD	_sprA02_BA_B
_sprA02_BA_B:
		.BYTE	$02
		.BYTE	$EC,$58,$80,$F1
		.BYTE	$ED,$58,$80,$08
_sprA02_BB:
		.BYTE	$82
		.WORD	_sprA02_B8
		.WORD	_sprA02_BB_B
_sprA02_BB_B:
		.BYTE	$02
		.BYTE	$EA,$48,$80,$09
		.BYTE	$EA,$48,$80,$F0
_sprA02_BC:
		.BYTE	$0C
		.BYTE	$00,$8A,$03,$10
		.BYTE	$00,$8E,$03,$E0
		.BYTE	$00,$9A,$03,$18
		.BYTE	$00,$9E,$03,$E8
		.BYTE	$00,$AE,$03,$F8
		.BYTE	$00,$BE,$03,$00
		.BYTE	$F0,$88,$03,$10
		.BYTE	$F0,$8C,$03,$E0
		.BYTE	$F0,$98,$03,$18
		.BYTE	$F0,$9C,$03,$E8
		.BYTE	$F0,$AC,$03,$F8
		.BYTE	$F0,$BC,$03,$00

_sprB02_C0:
		.BYTE	$83
		.WORD	_sprB02_C0_A
		.WORD	_sprB02_C0_B
		.WORD	_sprB02_C0_C
_sprB02_C1:
		.BYTE	$83
		.WORD	_sprB02_C1_A
		.WORD	_sprB02_C0_B
		.WORD	_sprB02_C0_C
_sprB02_C2:
		.BYTE	$82
		.WORD	_sprB02_C2_A
		.WORD	_sprB02_C2_B
_sprB02_C3:
		.BYTE	$82
		.WORD	_sprB02_C3_A
		.WORD	_sprB02_C2_B
_sprB02_C4:
		.BYTE	$83
		.WORD	_sprB02_C4_A
		.WORD	_sprB02_C0_B
		.WORD	_sprB02_C0_C
_sprB02_C5:
		.BYTE	$82
		.WORD	_sprB02_C5_A
		.WORD	_sprB02_C0_B
_sprB02_C6:
		.BYTE	$82
		.WORD	_sprB02_C6_A
		.WORD	_sprB02_C2_B
_sprB02_C7:
		.BYTE	$82
		.WORD	_sprB02_C7_A
		.WORD	_sprB02_C2_B
_sprB02_C8:
		.BYTE	$83
		.WORD	_sprB02_C8_A
		.WORD	_sprB02_C8_B
		.WORD	_sprB02_C8_C
_sprB02_C9:
		.BYTE	$83
		.WORD	_sprB02_C9_A
		.WORD	_sprB02_C8_B
		.WORD	_sprB02_C8_C
_sprB02_CA:
		.BYTE	$83
		.WORD	_sprB02_CA_A
		.WORD	_sprB02_C8_B
		.WORD	_sprB02_C8_C
_sprB02_CB:
		.BYTE	$83
		.WORD	_sprB02_CB_A
		.WORD	_sprB02_C8_B
		.WORD	_sprB02_C8_C
_sprB02_CC:
		.BYTE	$83
		.WORD	_sprB02_CC_A
		.WORD	_sprB02_C8_B
		.WORD	_sprB02_C8_C
_sprB02_CD:
		.BYTE	$83
		.WORD	_sprB02_CD_A
		.WORD	_sprB02_C8_B
		.WORD	_sprB02_C8_C
_sprB02_CE:
		.BYTE	$84
		.WORD	_sprB02_CE_A
		.WORD	_sprB02_C8_B
		.WORD	_sprB02_C8_C
		.WORD	_sprB02_CE_D
_sprB02_CF:
		.BYTE	$84
		.WORD	_sprB02_CE_A
		.WORD	_sprB02_C8_B
		.WORD	_sprB02_C8_C
		.WORD	_sprB02_CF_D
_sprB02_D0:
		.BYTE	$82
		.WORD	_sprB02_D0_A
		.WORD	_sprB02_D0_B
_sprB02_D1:
		.BYTE	$82
		.WORD	_sprB02_D0_A
		.WORD	_sprB02_D1_B
_sprB02_D2:
		.BYTE	$83
		.WORD	_sprB02_D2_A
		.WORD	_sprB02_C8_A
		.WORD	_sprB02_C8_C
_sprB02_C0_A:
		.BYTE	$03
		.BYTE	$CE,$EC,$23,$F0
		.BYTE	$CE,$FC,$23,$F8
		.BYTE	$DC,$C8,$23,$F4
_sprB02_C0_B:
		.BYTE	$05
		.BYTE	$E8,$D0,$23,$F4
		.BYTE	$E8,$E0,$23,$FC
		.BYTE	$E8,$F0,$23,$04
		.BYTE	$F8,$D2,$23,$F4
		.BYTE	$F8,$E2,$23,$FC
_sprB02_C0_C:
		.BYTE	$01
		.BYTE	$F8,$C2,$23,$04
_sprB02_C1_A:
		.BYTE	$04
		.BYTE	$D4,$EC,$23,$01
		.BYTE	$D4,$FC,$23,$09
		.BYTE	$DD,$CC,$23,$F8
		.BYTE	$DD,$DC,$23,$00
_sprB02_C2_A:
		.BYTE	$04
		.BYTE	$E4,$EC,$23,$02
		.BYTE	$E4,$FC,$23,$0A
		.BYTE	$E8,$CA,$23,$F7
		.BYTE	$E8,$CA,$23,$FF
_sprB02_C2_B:
		.BYTE	$06
		.BYTE	$E8,$D4,$23,$F4
		.BYTE	$E8,$E4,$23,$FC
		.BYTE	$E8,$F4,$23,$04
		.BYTE	$F8,$C4,$23,$F4
		.BYTE	$F8,$E6,$23,$FC
		.BYTE	$F8,$F6,$23,$04
_sprB02_C3_A:
		.BYTE	$04
		.BYTE	$E4,$CC,$63,$F8
		.BYTE	$F4,$EC,$23,$01
		.BYTE	$F4,$FC,$23,$09
		.BYTE	$F5,$DC,$63,$FF
_sprB02_C4_A:
		.BYTE	$03
		.BYTE	$EF,$C8,$23,$F5
		.BYTE	$FB,$EC,$23,$F1
		.BYTE	$FB,$FC,$23,$F9
_sprB02_C5_A:
		.BYTE	$05
		.BYTE	$EE,$CC,$23,$E9
		.BYTE	$EE,$DC,$23,$F1
		.BYTE	$F6,$EC,$23,$E0
		.BYTE	$F6,$FC,$23,$E8
		.BYTE	$F8,$C6,$23,$04
_sprB02_C6_A:
		.BYTE	$04
		.BYTE	$E6,$EC,$23,$DF
		.BYTE	$E6,$FC,$23,$E7
		.BYTE	$EA,$CA,$23,$EE
		.BYTE	$EA,$CA,$63,$E8
_sprB02_C7_A:
		.BYTE	$04
		.BYTE	$D7,$EC,$23,$E0
		.BYTE	$D7,$FC,$23,$E8
		.BYTE	$DD,$CC,$63,$EF
		.BYTE	$DD,$DC,$63,$E7
_sprB02_C8_A:
		.BYTE	$02
		.BYTE	$09,$EC,$23,$EF
		.BYTE	$09,$FC,$23,$F7
_sprB02_C8_B:
		.BYTE	$02
		.BYTE	$E8,$D8,$23,$F4
		.BYTE	$E8,$E8,$23,$FC
_sprB02_C8_C:
		.BYTE	$05
		.BYTE	$E8,$F8,$23,$04
		.BYTE	$F8,$DA,$23,$F4
		.BYTE	$F8,$EA,$23,$FC
		.BYTE	$F8,$FA,$23,$04
		.BYTE	$FE,$C8,$23,$F3
_sprB02_C9_A:
		.BYTE	$03
		.BYTE	$0E,$C8,$23,$F3
		.BYTE	$1B,$EC,$23,$EF
		.BYTE	$1B,$FC,$23,$F7
_sprB02_CA_A:
		.BYTE	$04
		.BYTE	$0E,$C8,$23,$F3
		.BYTE	$1E,$C8,$23,$F3
		.BYTE	$2C,$EC,$23,$F0
		.BYTE	$2C,$FC,$23,$F8
_sprB02_CB_A:
		.BYTE	$05
		.BYTE	$0E,$C8,$23,$F3
		.BYTE	$1E,$C8,$23,$F3
		.BYTE	$2E,$C8,$23,$F3
		.BYTE	$3C,$EC,$23,$F0
		.BYTE	$3C,$FC,$23,$F8
_sprB02_CC_A:
		.BYTE	$06
		.BYTE	$0E,$C8,$23,$F3
		.BYTE	$1E,$C8,$23,$F3
		.BYTE	$2E,$C8,$23,$F3
		.BYTE	$3E,$C8,$23,$F3
		.BYTE	$4D,$EC,$23,$F0
		.BYTE	$4D,$FC,$23,$F8
_sprB02_CD_A:
		.BYTE	$07
		.BYTE	$0E,$C8,$23,$F3
		.BYTE	$1E,$C8,$23,$F3
		.BYTE	$2E,$C8,$23,$F3
		.BYTE	$3E,$C8,$23,$F3
		.BYTE	$4E,$C8,$23,$F3
		.BYTE	$5C,$EC,$23,$F0
		.BYTE	$5C,$FC,$23,$F8
_sprB02_CE_A:
		.BYTE	$07
		.BYTE	$0E,$C8,$23,$F3
		.BYTE	$1E,$C8,$23,$F3
		.BYTE	$2E,$C8,$23,$F3
		.BYTE	$3E,$C8,$23,$F3
		.BYTE	$4E,$C8,$23,$F3
		.BYTE	$5E,$C8,$23,$F3
		.BYTE	$C8,$C8,$23,$F3
_sprB02_CE_D:
		.BYTE	$02
		.BYTE	$D7,$EC,$23,$F0
		.BYTE	$D7,$EC,$63,$F8
_sprB02_CF_D:
		.BYTE	$05
		.BYTE	$D8,$C8,$23,$F3
		.BYTE	$E3,$48,$23,$FC
		.BYTE	$E4,$EC,$23,$EF
		.BYTE	$E4,$EC,$63,$F7
		.BYTE	$EF,$48,$23,$EB
_sprB02_D0_A:
		.BYTE	$10
		.BYTE	$03,$C8,$23,$F3
		.BYTE	$13,$C8,$23,$F3
		.BYTE	$23,$C8,$23,$F3
		.BYTE	$33,$C8,$23,$F3
		.BYTE	$43,$C8,$23,$F3
		.BYTE	$53,$C8,$23,$F3
		.BYTE	$63,$C8,$23,$F3
		.BYTE	$CD,$C8,$23,$F3
		.BYTE	$DD,$C8,$23,$F3
		.BYTE	$E9,$EC,$23,$EF
		.BYTE	$E9,$EC,$63,$F7
		.BYTE	$ED,$D8,$23,$F4
		.BYTE	$ED,$F8,$23,$04
		.BYTE	$FD,$DA,$23,$F4
		.BYTE	$FD,$EA,$23,$FC
		.BYTE	$FD,$FA,$23,$04
_sprB02_D0_B:
		.BYTE	$03
		.BYTE	$ED,$E4,$23,$FC
		.BYTE	$E5,$58,$23,$FE
		.BYTE	$F8,$58,$23,$EC
_sprB02_D1_B:
		.BYTE	$01
		.BYTE	$ED,$E8,$23,$FC
_sprB02_D2_A:
		.BYTE	$02
		.BYTE	$E8,$D8,$23,$F4
		.BYTE	$E8,$E4,$23,$FC
