
_sprA00_00:
		.BYTE	$6C,$02
		.BYTE	$00,$86,$E8
		.BYTE	$00,$96,$F0
		.BYTE	$00,$A6,$F8
		.BYTE	$00,$B6,$00
		.BYTE	$00,$C6,$08
		.BYTE	$00,$D6,$10
		.BYTE	$F0,$84,$E8
		.BYTE	$F0,$94,$F0
		.BYTE	$F0,$A4,$F8
		.BYTE	$F0,$B4,$00
		.BYTE	$F0,$C4,$08
		.BYTE	$F0,$D4,$10
_sprA00_01:
		.BYTE	$6C,$02
		.BYTE	$00,$82,$E8
		.BYTE	$00,$92,$F0
		.BYTE	$00,$A2,$F8
		.BYTE	$00,$B2,$00
		.BYTE	$00,$C2,$08
		.BYTE	$00,$D2,$10
		.BYTE	$F0,$80,$E8
		.BYTE	$F0,$90,$F0
		.BYTE	$F0,$A0,$F8
		.BYTE	$F0,$B0,$00
		.BYTE	$F0,$C0,$08
		.BYTE	$F0,$D0,$10
_sprA00_02:
		.BYTE	$24
		.BYTE	$00,$8A,$03,$F8
		.BYTE	$00,$8A,$43,$00
		.BYTE	$F0,$88,$03,$F8
		.BYTE	$F0,$88,$43,$00
_sprA00_03:
		.BYTE	$24
		.BYTE	$00,$8E,$03,$F8
		.BYTE	$00,$8E,$43,$00
		.BYTE	$F0,$8C,$03,$F8
		.BYTE	$F0,$8C,$43,$00
_sprA00_04:
		.BYTE	$02
_sprA00_04_A:
		.BYTE	$00,$5E,$00,$00
		.BYTE	$00,$5E,$40,$F8
		.BYTE	$A2
		.WORD	_sprA03_0A_B
_sprA00_0B:
		.BYTE	$24
_sprA00_0B_A:
		.BYTE	$00,$6E,$00,$FE
		.BYTE	$00,$7E,$00,$06
		.BYTE	$F0,$C8,$00,$FE
		.BYTE	$F0,$D8,$00,$06
_sprA00_0C:
		.BYTE	$24
_sprA00_0C_A:
		.BYTE	$00,$EC,$00,$F8
		.BYTE	$00,$EC,$40,$00
		.BYTE	$F0,$E0,$00,$F8
		.BYTE	$F0,$F0,$00,$00
_sprA00_0D:
		.BYTE	$24
_sprA00_0D_A:
		.BYTE	$00,$6E,$40,$FA
		.BYTE	$00,$7E,$40,$F2
_sprA00_0D_B:
		.BYTE	$F0,$C8,$40,$FA
		.BYTE	$F0,$D8,$40,$F2
_sprA00_0E:
		.BYTE	$02
_sprA00_0E_A:
		.BYTE	$00,$EE,$00,$F8
		.BYTE	$00,$EE,$40,$00
		.BYTE	$A2
		.WORD	_sprA03_02_B
_sprA00_0F:
		.BYTE	$A2
		.WORD	_sprA00_0D_B
_sprA00_10:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.BYTE	$A2
		.WORD	_sprA03_2A_B
_sprA00_17:
		.BYTE	$82
		.WORD	_sprA00_0B_A
		.BYTE	$22
		.BYTE	$F0,$CC,$00,$FE
		.BYTE	$F0,$DC,$00,$06
_sprA00_18:
		.BYTE	$82
		.WORD	_sprA00_0C_A
		.BYTE	$22
		.BYTE	$F0,$E4,$00,$F8
		.BYTE	$F0,$F4,$00,$00
_sprA00_19:
		.BYTE	$82
		.WORD	_sprA00_0D_A
		.BYTE	$22
_sprA00_19_B:
		.BYTE	$F0,$CC,$40,$FA
		.BYTE	$F0,$DC,$40,$F2
_sprA00_1A:
		.BYTE	$82
		.WORD	_sprA00_0E_A
		.BYTE	$A2
		.WORD	_sprA03_22_B
_sprA00_1B:
		.BYTE	$A2
		.WORD	_sprA00_19_B
_sprA00_1C:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.BYTE	$A2
		.WORD	_sprA03_3A_B
_sprA00_23:
		.BYTE	$82
		.WORD	_sprA00_0B_A
		.BYTE	$22
		.BYTE	$F0,$CE,$00,$FE
		.BYTE	$F0,$DE,$00,$06
_sprA00_24:
		.BYTE	$82
		.WORD	_sprA00_0C_A
		.BYTE	$22
		.BYTE	$F0,$E6,$00,$F8
		.BYTE	$F0,$F6,$00,$00
_sprA00_25:
		.BYTE	$82
		.WORD	_sprA00_0D_A
		.BYTE	$22
_sprA00_25_B:
		.BYTE	$F0,$CE,$40,$FA
		.BYTE	$F0,$DE,$40,$F2
_sprA00_26:
		.BYTE	$82
		.WORD	_sprA00_0E_A
		.BYTE	$A2
		.WORD	_sprA03_32_B
_sprA00_27:
		.BYTE	$A2
		.WORD	_sprA00_25_B
_sprA00_28:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.BYTE	$A2
		.WORD	_sprA03_1A_B
_sprA00_2F:
		.BYTE	$82
		.WORD	_sprA00_0B_A
		.BYTE	$22
		.BYTE	$F0,$CA,$00,$FE
		.BYTE	$F0,$DA,$00,$06
_sprA00_30:
		.BYTE	$82
		.WORD	_sprA00_0C_A
		.BYTE	$22
		.BYTE	$F0,$E2,$00,$F8
		.BYTE	$F0,$F2,$00,$00
_sprA00_31:
		.BYTE	$82
		.WORD	_sprA00_0D_A
		.BYTE	$22
_sprA00_31_B:
		.BYTE	$F0,$CA,$40,$FA
		.BYTE	$F0,$DA,$40,$F2
_sprA00_32:
		.BYTE	$82
		.WORD	_sprA00_0E_A
		.BYTE	$A2
		.WORD	_sprA03_12_B
_sprA00_33:
		.BYTE	$A2
		.WORD	_sprA00_31_B
_sprA00_3B:
		.BYTE	$82
		.WORD	_sprA00_0B_A
		.BYTE	$22
		.BYTE	$F0,$EA,$00,$FE
		.BYTE	$F0,$FA,$00,$06
_sprA00_3C:
		.BYTE	$82
		.WORD	_sprA00_0C_A
		.BYTE	$22
		.BYTE	$F0,$E8,$00,$F8
		.BYTE	$F0,$F8,$00,$00
_sprA00_3D:
		.BYTE	$82
		.WORD	_sprA00_0D_A
		.BYTE	$22
_sprA00_3D_B:
		.BYTE	$F0,$EA,$40,$FA
		.BYTE	$F0,$FA,$40,$F2
_sprA00_3E:
		.BYTE	$82
		.WORD	_sprA00_0E_A
		.BYTE	$A2
		.WORD	_sprA03_42_B
_sprA00_3F:
		.BYTE	$A2
		.WORD	_sprA00_3D_B
_sprA00_40:
		.BYTE	$65,$02
		.BYTE	$F4,$D3,$04
		.BYTE	$F4,$D3,$F4
		.BYTE	$F4,$E9,$EC
		.BYTE	$F4,$ED,$0C
		.BYTE	$F4,$F1,$FC
_sprA00_41:
		.BYTE	$63,$02
		.BYTE	$F4,$CB,$FC
		.BYTE	$F4,$ED,$F4
		.BYTE	$F4,$FB,$04
_sprA00_42:
		.BYTE	$64,$02
		.BYTE	$F4,$D3,$F0
		.BYTE	$F4,$D7,$F8
		.BYTE	$F4,$E5,$08
		.BYTE	$F4,$E7,$00
_sprA00_43:
		.BYTE	$67,$02
		.BYTE	$F4,$DB,$EC
		.BYTE	$F4,$E5,$14
		.BYTE	$F4,$E5,$F4
		.BYTE	$F4,$E7,$0C
		.BYTE	$F4,$EF,$FC
		.BYTE	$F4,$F1,$04
		.BYTE	$F4,$F7,$E4
_sprA00_44:
		.BYTE	$65,$02
		.BYTE	$F4,$DB,$04
		.BYTE	$F4,$E1,$EC
		.BYTE	$F4,$E7,$F4
		.BYTE	$F4,$EF,$0C
		.BYTE	$F4,$F3,$FC
_sprA00_45:
		.BYTE	$A2
		.WORD	_sprA00_0E_A
_sprA00_46:
		.BYTE	$66,$02
		.BYTE	$F0,$DB,$F4
		.BYTE	$F0,$FB,$04
		.BYTE	$00,$FD,$04
		.BYTE	$00,$DD,$F4
		.BYTE	$00,$ED,$FC
		.BYTE	$F0,$EB,$FC
_sprA00_47:
		.BYTE	$64,$02
		.BYTE	$00,$E9,$F8
		.BYTE	$00,$F9,$00
		.BYTE	$F0,$F7,$00
		.BYTE	$F0,$E7,$F8
_sprA00_48:
		.BYTE	$64,$02
		.BYTE	$00,$D9,$00
		.BYTE	$00,$C9,$F8
		.BYTE	$F0,$C7,$F8
		.BYTE	$F0,$D7,$00
_sprA00_49:
		.BYTE	$64,$02
		.BYTE	$00,$B9,$00
		.BYTE	$00,$A9,$F8
		.BYTE	$F0,$A7,$F8
		.BYTE	$F0,$B7,$00
_sprA00_4A:
		.BYTE	$67,$02
		.BYTE	$F0,$97,$0C
		.BYTE	$F0,$87,$04
		.BYTE	$00,$89,$04
		.BYTE	$00,$79,$FC
		.BYTE	$F0,$77,$FC
		.BYTE	$00,$69,$F4
		.BYTE	$F0,$67,$F4
_sprA00_4B:
		.BYTE	$44,$00
		.BYTE	$F0,$9B,$04
		.BYTE	$00,$8B,$04
		.BYTE	$00,$7B,$FC
		.BYTE	$00,$6B,$F4
		.BYTE	$67,$02
		.BYTE	$F0,$99,$F4
		.BYTE	$F0,$17,$0C
		.BYTE	$F0,$07,$04
		.BYTE	$F0,$19,$FC
		.BYTE	$00,$2B,$04
		.BYTE	$00,$1B,$FC
		.BYTE	$00,$CB,$F4
_sprA00_4C:
		.BYTE	$6E,$01
		.BYTE	$00,$CF,$10
		.BYTE	$F0,$CD,$10
		.BYTE	$F0,$BD,$08
		.BYTE	$00,$BF,$08
		.BYTE	$00,$AF,$00
		.BYTE	$F0,$AD,$00
		.BYTE	$F0,$9D,$F8
		.BYTE	$00,$9F,$F8
		.BYTE	$00,$8F,$F0
		.BYTE	$F0,$8D,$F0
		.BYTE	$F0,$7D,$E8
		.BYTE	$00,$7F,$E8
		.BYTE	$00,$6F,$E0
		.BYTE	$F0,$6D,$E0
_sprA02_00:
		.BYTE	$64,$22
		.BYTE	$00,$A2,$F8
		.BYTE	$00,$B2,$00
		.BYTE	$F0,$A0,$F8
		.BYTE	$F0,$B0,$00
_sprA02_01:
		.BYTE	$25
_sprA02_01_A:
		.BYTE	$00,$82,$22,$F8
		.BYTE	$00,$92,$22,$00
		.BYTE	$F0,$80,$22,$F8
		.BYTE	$F0,$90,$22,$00
		.BYTE	$EF,$94,$20,$F8
_sprA02_02:
		.BYTE	$84
		.WORD	_sprA02_01_A
		.BYTE	$21
		.BYTE	$F1,$94,$20,$F4
_sprA02_03:
		.BYTE	$24
_sprA02_03_A:
		.BYTE	$00,$C2,$62,$00
		.BYTE	$00,$D2,$62,$F8
		.BYTE	$F0,$C0,$62,$00
		.BYTE	$F0,$D0,$62,$F8
_sprA02_04:
		.BYTE	$82
		.WORD	_sprA02_03_A
		.BYTE	$22
		.BYTE	$F1,$C0,$62,$00
		.BYTE	$F1,$D0,$62,$F8
_sprA02_05:
		.BYTE	$64,$22
		.BYTE	$00,$E2,$F8
		.BYTE	$00,$F2,$00
		.BYTE	$F0,$E0,$F8
		.BYTE	$F0,$F0,$00
_sprA02_06:
		.BYTE	$64,$22
		.BYTE	$00,$E6,$F8
		.BYTE	$00,$F6,$00
		.BYTE	$F0,$E4,$F8
		.BYTE	$F0,$F4,$00
_sprA02_07:
		.BYTE	$27
		.BYTE	$08,$8A,$23,$F8
		.BYTE	$08,$9A,$23,$00
		.BYTE	$D9,$84,$21,$FA
_sprA02_07_A:
		.BYTE	$E8,$86,$23,$F8
		.BYTE	$E8,$96,$23,$00
		.BYTE	$F8,$88,$23,$F8
		.BYTE	$F8,$98,$23,$00
_sprA02_08:
		.BYTE	$46,$23
		.BYTE	$07,$AA,$F8
		.BYTE	$07,$BA,$00
		.BYTE	$E7,$A6,$F8
		.BYTE	$E7,$B6,$00
		.BYTE	$F7,$A8,$F8
		.BYTE	$F7,$B8,$00
		.BYTE	$21
		.BYTE	$D7,$B4,$21,$FA
_sprA02_09:
		.BYTE	$03
		.BYTE	$08,$CA,$23,$F8
		.BYTE	$08,$DA,$23,$00
		.BYTE	$D9,$84,$61,$FB
		.BYTE	$A4
		.WORD	_sprA02_07_A
_sprA02_0A:
		.BYTE	$27
		.BYTE	$D8,$84,$01,$F7
_sprA02_0A_A:
		.BYTE	$08,$C8,$03,$F8
		.BYTE	$08,$D8,$03,$00
		.BYTE	$E8,$C4,$03,$F8
		.BYTE	$E8,$D4,$03,$00
		.BYTE	$F8,$C6,$03,$F8
		.BYTE	$F8,$D6,$03,$00
_sprA02_0B:
		.BYTE	$01
		.BYTE	$D8,$B4,$01,$F7
		.BYTE	$A6
		.WORD	_sprA02_0A_A
_sprA02_0C:
		.BYTE	$01
		.BYTE	$D8,$84,$41,$F8
		.BYTE	$A6
		.WORD	_sprA02_0A_A
_sprA02_0D:
		.BYTE	$01
		.BYTE	$D7,$B4,$41,$F8
		.BYTE	$A6
		.WORD	_sprA02_0A_A
_sprA02_0E:
		.BYTE	$26
_sprA02_0E_A:
		.BYTE	$00,$CC,$62,$00
		.BYTE	$00,$DC,$62,$F8
		.BYTE	$F0,$EA,$62,$00
		.BYTE	$F0,$FA,$62,$F8
		.BYTE	$F8,$D8,$60,$FA
		.BYTE	$F8,$E8,$60,$F2
_sprA02_0F:
		.BYTE	$85
		.WORD	_sprA02_0E_A
		.BYTE	$21
		.BYTE	$F8,$E6,$60,$F2
_sprA02_10:
		.BYTE	$02
		.BYTE	$02,$58,$60,$EF
		.BYTE	$EF,$58,$60,$F3
		.BYTE	$85
		.WORD	_sprA02_0E_A
		.BYTE	$21
		.BYTE	$F8,$E6,$60,$F2
_sprA02_11:
		.BYTE	$02
		.BYTE	$02,$48,$60,$EF
		.BYTE	$EF,$48,$60,$F3
		.BYTE	$A6
		.WORD	_sprA02_0E_A
_sprA02_12:
		.BYTE	$02
		.BYTE	$EE,$D8,$60,$FB
		.BYTE	$EE,$E8,$60,$F3
		.BYTE	$82
		.WORD	_sprA02_0E_A
		.BYTE	$22
_sprA02_12_A:
		.BYTE	$F0,$CA,$62,$00
		.BYTE	$F0,$DA,$62,$F8
_sprA02_13:
		.BYTE	$02
		.BYTE	$EE,$D6,$60,$FB
		.BYTE	$EE,$E6,$60,$F3
		.BYTE	$82
		.WORD	_sprA02_0E_A
		.BYTE	$A2
		.WORD	_sprA02_12_A
_sprA02_14:
		.BYTE	$E4,$20
		.WORD	_sprA03_02_A
_sprA02_15:
		.BYTE	$E4,$20
		.WORD	_sprA03_01_A
_sprA02_16:
		.BYTE	$C2,$20
		.WORD	_sprA03_03_A
		.BYTE	$E2,$20
		.WORD	_sprA03_01_B
_sprA02_17:
		.BYTE	$E4,$20
		.WORD	_sprA03_06_A
_sprA02_18:
		.BYTE	$C2,$20
		.WORD	_sprA03_05_A
		.BYTE	$E2,$20
		.WORD	_sprA03_05_B
_sprA02_19:
		.BYTE	$C2,$20
		.WORD	_sprA03_07_A
		.BYTE	$E2,$20
		.WORD	_sprA03_05_B
_sprA02_1A:
		.BYTE	$C2,$20
		.WORD	_sprA03_02_A
		.BYTE	$E2,$20
		.WORD	_sprA03_0A_B
_sprA02_1B:
		.BYTE	$C2,$20
		.WORD	_sprA03_01_A
		.BYTE	$E2,$20
		.WORD	_sprA03_09_B
_sprA02_1C:
		.BYTE	$C2,$20
		.WORD	_sprA03_03_A
		.BYTE	$E2,$20
		.WORD	_sprA03_09_B
_sprA02_1D:
		.BYTE	$E4,$20
		.WORD	_sprA03_0E_A
_sprA02_1E:
		.BYTE	$C2,$20
		.WORD	_sprA03_07_A
		.BYTE	$E2,$20
		.WORD	_sprA03_0D_B
_sprA02_1F:
		.BYTE	$C2,$20
		.WORD	_sprA03_05_A
		.BYTE	$E2,$20
		.WORD	_sprA03_0D_B
_sprA02_20:
		.BYTE	$C2,$20
		.WORD	_sprA03_02_A
		.BYTE	$E2,$20
		.WORD	_sprA03_12_B
_sprA02_21:
		.BYTE	$C2,$20
		.WORD	_sprA03_01_A
		.BYTE	$E2,$20
		.WORD	_sprA03_11_B
_sprA02_22:
		.BYTE	$C2,$20
		.WORD	_sprA03_03_A
		.BYTE	$E2,$20
		.WORD	_sprA03_11_B
_sprA02_23:
		.BYTE	$C2,$20
		.WORD	_sprA03_06_A
		.BYTE	$E2,$20
		.WORD	_sprA03_16_B
_sprA02_24:
		.BYTE	$C2,$20
		.WORD	_sprA03_05_A
		.BYTE	$E2,$20
		.WORD	_sprA03_15_B
_sprA02_25:
		.BYTE	$C2,$20
		.WORD	_sprA03_07_A
		.BYTE	$E2,$20
		.WORD	_sprA03_15_B
_sprA02_26:
		.BYTE	$C2,$20
		.WORD	_sprA03_02_A
		.BYTE	$E2,$20
		.WORD	_sprA03_1A_B
_sprA02_27:
		.BYTE	$C2,$20
		.WORD	_sprA03_01_A
		.BYTE	$E2,$20
		.WORD	_sprA03_19_B
_sprA02_28:
		.BYTE	$C2,$20
		.WORD	_sprA03_03_A
		.BYTE	$E2,$20
		.WORD	_sprA03_19_B
_sprA02_29:
		.BYTE	$C2,$20
		.WORD	_sprA03_0E_A
		.BYTE	$E2,$20
		.WORD	_sprA03_1E_B
_sprA02_2A:
		.BYTE	$C2,$20
		.WORD	_sprA03_07_A
		.BYTE	$E2,$20
		.WORD	_sprA03_1D_B
_sprA02_2B:
		.BYTE	$C2,$20
		.WORD	_sprA03_05_A
		.BYTE	$E2,$20
		.WORD	_sprA03_1D_B
_sprA02_2C:
		.BYTE	$C2,$20
		.WORD	_sprA03_02_A
		.BYTE	$E2,$20
		.WORD	_sprA03_22_B
_sprA02_2D:
		.BYTE	$C2,$20
		.WORD	_sprA03_01_A
		.BYTE	$E2,$20
		.WORD	_sprA03_21_B
_sprA02_2E:
		.BYTE	$C2,$20
		.WORD	_sprA03_03_A
		.BYTE	$E2,$20
		.WORD	_sprA03_21_B
_sprA02_2F:
		.BYTE	$C2,$20
		.WORD	_sprA03_06_A
		.BYTE	$E2,$20
		.WORD	_sprA03_26_B
_sprA02_30:
		.BYTE	$C2,$20
		.WORD	_sprA03_05_A
		.BYTE	$E2,$20
		.WORD	_sprA03_25_A
_sprA02_31:
		.BYTE	$C2,$20
		.WORD	_sprA03_07_A
		.BYTE	$E2,$20
		.WORD	_sprA03_25_A
_sprA02_32:
		.BYTE	$C2,$20
		.WORD	_sprA03_02_A
		.BYTE	$E2,$20
		.WORD	_sprA03_2A_B
_sprA02_33:
		.BYTE	$C2,$20
		.WORD	_sprA03_01_A
		.BYTE	$E2,$20
		.WORD	_sprA03_29_A
_sprA02_34:
		.BYTE	$C2,$20
		.WORD	_sprA03_03_A
		.BYTE	$E2,$20
		.WORD	_sprA03_29_A
_sprA02_35:
		.BYTE	$C2,$20
		.WORD	_sprA03_0E_A
		.BYTE	$E2,$20
		.WORD	_sprA03_2E_B
_sprA02_36:
		.BYTE	$C2,$20
		.WORD	_sprA03_07_A
		.BYTE	$E2,$20
		.WORD	_sprA03_2D_B
_sprA02_37:
		.BYTE	$C2,$20
		.WORD	_sprA03_05_A
		.BYTE	$E2,$20
		.WORD	_sprA03_2D_B
_sprA02_38:
		.BYTE	$C2,$20
		.WORD	_sprA03_02_A
		.BYTE	$E2,$20
		.WORD	_sprA03_32_B
_sprA02_39:
		.BYTE	$C2,$20
		.WORD	_sprA03_01_A
		.BYTE	$E2,$20
		.WORD	_sprA03_31_B
_sprA02_3A:
		.BYTE	$C2,$20
		.WORD	_sprA03_03_A
		.BYTE	$E2,$20
		.WORD	_sprA03_31_B
_sprA02_3B:
		.BYTE	$C2,$20
		.WORD	_sprA03_06_A
		.BYTE	$E2,$20
		.WORD	_sprA03_36_B
_sprA02_3C:
		.BYTE	$C2,$20
		.WORD	_sprA03_05_A
		.BYTE	$E2,$20
		.WORD	_sprA03_35_B
_sprA02_3D:
		.BYTE	$C2,$20
		.WORD	_sprA03_07_A
		.BYTE	$E2,$20
		.WORD	_sprA03_35_B
_sprA02_3E:
		.BYTE	$C2,$20
		.WORD	_sprA03_02_A
		.BYTE	$E2,$20
		.WORD	_sprA03_3A_B
_sprA02_3F:
		.BYTE	$C2,$20
		.WORD	_sprA03_01_A
		.BYTE	$E2,$20
		.WORD	_sprA03_39_A
_sprA02_40:
		.BYTE	$C2,$20
		.WORD	_sprA03_03_A
		.BYTE	$E2,$20
		.WORD	_sprA03_39_A
_sprA02_41:
		.BYTE	$C2,$20
		.WORD	_sprA03_0E_A
		.BYTE	$E2,$20
		.WORD	_sprA03_3E_B
_sprA02_42:
		.BYTE	$C2,$20
		.WORD	_sprA03_07_A
		.BYTE	$E2,$20
		.WORD	_sprA03_3D_B
_sprA02_43:
		.BYTE	$C2,$20
		.WORD	_sprA03_05_A
		.BYTE	$E2,$20
		.WORD	_sprA03_3D_B
_sprA02_44:
		.BYTE	$C2,$20
		.WORD	_sprA03_02_A
		.BYTE	$E2,$20
		.WORD	_sprA03_42_B
_sprA02_45:
		.BYTE	$C2,$20
		.WORD	_sprA03_01_A
		.BYTE	$E2,$20
		.WORD	_sprA03_41_B
_sprA02_46:
		.BYTE	$C2,$20
		.WORD	_sprA03_03_A
		.BYTE	$E2,$20
		.WORD	_sprA03_41_B
_sprA02_47:
		.BYTE	$C2,$20
		.WORD	_sprA03_06_A
		.BYTE	$E2,$20
		.WORD	_sprA03_46_B
_sprA02_48:
		.BYTE	$C2,$20
		.WORD	_sprA03_05_A
		.BYTE	$E2,$20
		.WORD	_sprA03_45_B
_sprA02_49:
		.BYTE	$C2,$20
		.WORD	_sprA03_07_A
		.BYTE	$E2,$20
		.WORD	_sprA03_45_B
_sprA02_4A:
		.BYTE	$C2,$20
		.WORD	_sprA03_02_A
		.BYTE	$E2,$20
		.WORD	_sprA03_4A_B
_sprA02_4B:
		.BYTE	$C2,$20
		.WORD	_sprA03_01_A
		.BYTE	$E2,$20
		.WORD	_sprA03_49_B
_sprA02_4C:
		.BYTE	$C2,$20
		.WORD	_sprA03_03_A
		.BYTE	$E2,$20
		.WORD	_sprA03_49_B
_sprA02_4D:
		.BYTE	$C2,$20
		.WORD	_sprA03_0E_A
		.BYTE	$E2,$20
		.WORD	_sprA03_4E_B
_sprA02_4E:
		.BYTE	$C2,$20
		.WORD	_sprA03_07_A
		.BYTE	$E2,$20
		.WORD	_sprA03_4D_B
_sprA02_4F:
		.BYTE	$C2,$20
		.WORD	_sprA03_05_A
		.BYTE	$E2,$20
		.WORD	_sprA03_4D_B
_sprA02_50:
		.BYTE	$02
_sprA02_50_A:
		.BYTE	$01,$4E,$20,$F8
		.BYTE	$01,$4E,$60,$00
		.BYTE	$E2,$20
		.WORD	_sprA03_5A_A
_sprA02_51:
		.BYTE	$C2,$20
		.WORD	_sprA02_50_A
		.BYTE	$E2,$20
		.WORD	_sprA03_5B_A
_sprA02_52:
		.BYTE	$C2,$20
		.WORD	_sprA02_50_A
		.BYTE	$E2,$20
		.WORD	_sprA03_56_A
_sprA02_53:
		.BYTE	$C2,$20
		.WORD	_sprA02_50_A
		.BYTE	$E2,$20
		.WORD	_sprA03_6A_A
_sprA02_54:
		.BYTE	$C2,$20
		.WORD	_sprA02_50_A
		.BYTE	$E2,$20
		.WORD	_sprA03_6B_A
_sprA02_55:
		.BYTE	$C2,$20
		.WORD	_sprA02_50_A
		.BYTE	$E2,$20
		.WORD	_sprA03_6E_A
_sprA02_56:
		.BYTE	$24
		.BYTE	$EF,$A8,$62,$00
		.BYTE	$EF,$B8,$62,$F8
_sprA02_56_A:
		.BYTE	$FF,$8C,$62,$00
		.BYTE	$FF,$9C,$62,$F8
_sprA02_57:
		.BYTE	$24
_sprA02_57_A:
		.BYTE	$00,$AC,$22,$F8
		.BYTE	$00,$AC,$62,$00
		.BYTE	$F0,$AA,$62,$00
		.BYTE	$F0,$B8,$62,$F8
_sprA02_58:
		.BYTE	$24
		.BYTE	$EF,$AA,$62,$00
		.BYTE	$EF,$BA,$62,$F8
_sprA02_58_A:
		.BYTE	$FF,$8C,$22,$F8
		.BYTE	$FF,$9C,$22,$00
_sprA02_59:
		.BYTE	$83
		.WORD	_sprA02_57_A
		.BYTE	$21
		.BYTE	$F0,$BA,$62,$F8
_sprA02_5A:
		.BYTE	$02
		.BYTE	$EF,$A8,$22,$F8
		.BYTE	$EF,$B8,$22,$00
		.BYTE	$A2
		.WORD	_sprA02_58_A
_sprA02_5B:
		.BYTE	$24
_sprA02_5B_A:
		.BYTE	$00,$AC,$22,$F8
		.BYTE	$00,$AC,$62,$00
		.BYTE	$F0,$AA,$22,$F8
		.BYTE	$F0,$B8,$22,$00
_sprA02_5C:
		.BYTE	$02
		.BYTE	$EF,$AA,$22,$F8
		.BYTE	$EF,$BA,$22,$00
		.BYTE	$A2
		.WORD	_sprA02_56_A
_sprA02_5D:
		.BYTE	$83
		.WORD	_sprA02_5B_A
		.BYTE	$21
		.BYTE	$F0,$BA,$22,$00
_sprA02_5E:
		.BYTE	$24
		.BYTE	$E8,$1C,$20,$F8
		.BYTE	$E8,$1C,$60,$00
		.BYTE	$F5,$5E,$23,$00
		.BYTE	$F5,$5E,$23,$FB
_sprA02_5F:
		.BYTE	$24
		.BYTE	$E8,$1E,$20,$F8
		.BYTE	$E8,$1E,$60,$00
		.BYTE	$F5,$5E,$23,$00
		.BYTE	$F5,$5E,$63,$F8
_sprA02_60:
		.BYTE	$25
_sprA02_60_A:
		.BYTE	$00,$A6,$23,$F8
		.BYTE	$00,$B6,$23,$00
		.BYTE	$00,$BA,$23,$F0
		.BYTE	$F0,$A4,$23,$F8
		.BYTE	$F0,$B4,$23,$00
_sprA02_61:
		.BYTE	$25
_sprA02_61_A:
		.BYTE	$00,$86,$23,$F8
		.BYTE	$00,$96,$23,$00
		.BYTE	$F0,$84,$23,$F8
		.BYTE	$F0,$94,$23,$00
		.BYTE	$F0,$BC,$23,$F0
_sprA02_62:
		.BYTE	$25
_sprA02_62_A:
		.BYTE	$00,$A6,$63,$00
		.BYTE	$00,$B6,$63,$F8
		.BYTE	$00,$BA,$63,$08
		.BYTE	$F0,$A4,$63,$00
		.BYTE	$F0,$B4,$63,$F8
_sprA02_63:
		.BYTE	$25
_sprA02_63_A:
		.BYTE	$00,$86,$63,$00
		.BYTE	$00,$96,$63,$F8
		.BYTE	$F0,$84,$63,$00
		.BYTE	$F0,$94,$63,$F8
		.BYTE	$F0,$BC,$63,$08
_sprA02_64:
		.BYTE	$82
		.WORD	_sprA02_61_A
		.BYTE	$23
		.BYTE	$F0,$23,$23,$F8
		.BYTE	$F0,$25,$23,$00
		.BYTE	$F0,$9C,$23,$F0
_sprA02_65:
		.BYTE	$83
		.WORD	_sprA02_60_A
		.BYTE	$22
		.BYTE	$F0,$27,$23,$F8
		.BYTE	$F0,$29,$23,$00
_sprA02_66:
		.BYTE	$82
		.WORD	_sprA02_63_A
		.BYTE	$23
		.BYTE	$F0,$23,$63,$00
		.BYTE	$F0,$25,$63,$F8
		.BYTE	$F0,$9C,$63,$08
_sprA02_67:
		.BYTE	$83
		.WORD	_sprA02_62_A
		.BYTE	$22
		.BYTE	$F0,$27,$63,$00
		.BYTE	$F0,$29,$63,$F8
_sprA02_68:
		.BYTE	$64,$23
		.BYTE	$00,$A2,$F8
		.BYTE	$00,$B2,$00
		.BYTE	$F0,$3B,$F8
		.BYTE	$F0,$3D,$00
_sprA02_69:
		.BYTE	$22
		.BYTE	$F8,$AB,$23,$F8
		.BYTE	$F8,$BB,$23,$00
_sprA02_6A:
		.BYTE	$64,$20
		.BYTE	$E0,$20,$F8
		.BYTE	$E0,$30,$00
		.BYTE	$F0,$4A,$F8
		.BYTE	$F0,$5A,$00
_sprA02_6B:
		.BYTE	$C2,$20
		.WORD	_sprA03_0E_A
		.BYTE	$22
		.BYTE	$F2,$20,$20,$F8
		.BYTE	$F2,$30,$20,$00
_sprA02_6C:
		.BYTE	$C2,$20
		.WORD	_sprA03_02_A
		.BYTE	$C2,$20
		.WORD	_sprA03_4A_B
		.BYTE	$22
		.BYTE	$F9,$AB,$23,$F8
		.BYTE	$F9,$BB,$23,$00
_sprA02_6D:
		.BYTE	$C2,$20
		.WORD	_sprA03_06_A
		.BYTE	$C2,$20
		.WORD	_sprA03_46_B
		.BYTE	$22
		.BYTE	$F8,$AB,$23,$03
		.BYTE	$F8,$BB,$23,$0B
_sprA02_6E:
		.BYTE	$C2,$20
		.WORD	_sprA03_05_A
		.BYTE	$C2,$20
		.WORD	_sprA03_45_B
		.BYTE	$22
_sprA02_6E_C:
		.BYTE	$F9,$AB,$23,$04
		.BYTE	$F9,$BB,$23,$0C
_sprA02_6F:
		.BYTE	$C2,$20
		.WORD	_sprA03_07_A
		.BYTE	$C2,$20
		.WORD	_sprA03_45_B
		.BYTE	$A2
		.WORD	_sprA02_6E_C
_sprA02_70:
		.BYTE	$C2,$20
		.WORD	_sprA03_0E_A
		.BYTE	$C2,$20
		.WORD	_sprA03_4E_B
		.BYTE	$22
		.BYTE	$F8,$AB,$63,$F5
		.BYTE	$F8,$BB,$63,$ED
_sprA02_AD:
		.BYTE	$82
		.WORD	_sprA03_0E_A
		.BYTE	$22
		.BYTE	$F0,$82,$00,$F8
		.BYTE	$F0,$92,$00,$00
_sprA02_AE:
		.BYTE	$24
_sprA02_AE_A:
		.BYTE	$00,$84,$00,$F8
		.BYTE	$00,$94,$00,$00
_sprA02_AE_B:
		.BYTE	$F1,$82,$00,$F8
		.BYTE	$F1,$92,$00,$00
_sprA02_AF:
		.BYTE	$02
_sprA02_AF_A:
		.BYTE	$00,$84,$40,$00
		.BYTE	$00,$94,$40,$F8
		.BYTE	$A2
		.WORD	_sprA02_AE_B
_sprA02_B0:
		.BYTE	$82
		.WORD	_sprA03_06_A
		.BYTE	$22
		.BYTE	$F0,$82,$40,$00
		.BYTE	$F0,$92,$40,$F8
_sprA02_B1:
		.BYTE	$82
		.WORD	_sprA02_AF_A
		.BYTE	$22
_sprA02_B1_B:
		.BYTE	$F1,$82,$40,$00
		.BYTE	$F1,$92,$40,$F8
_sprA02_B2:
		.BYTE	$82
		.WORD	_sprA02_AE_A
		.BYTE	$A2
		.WORD	_sprA02_B1_B
_sprA02_B3:
		.BYTE	$21
		.BYTE	$FC,$6E,$41,$FD
_sprA02_B4:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.BYTE	$A2
		.WORD	_sprA03_1A_B
_sprA02_B5:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.BYTE	$A2
		.WORD	_sprA03_2A_B
_sprA02_B6:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.BYTE	$A2
		.WORD	_sprA03_3A_B
_sprA02_B7:
		.BYTE	$82
		.WORD	_sprA00_04_A
		.BYTE	$A2
		.WORD	_sprA03_4A_B
_sprA02_B8:
		.BYTE	$24
_sprA02_B8_A:
		.BYTE	$E8,$4E,$80,$F8
		.BYTE	$E8,$4E,$C0,$00
		.BYTE	$F8,$4C,$80,$F8
		.BYTE	$F8,$4C,$C0,$00
_sprA02_B9:
		.BYTE	$84
		.WORD	_sprA02_B8_A
		.BYTE	$22
		.BYTE	$F0,$48,$80,$06
		.BYTE	$F1,$48,$80,$F3
_sprA02_BA:
		.BYTE	$84
		.WORD	_sprA02_B8_A
		.BYTE	$22
		.BYTE	$EC,$58,$80,$F1
		.BYTE	$ED,$58,$80,$08
_sprA02_BB:
		.BYTE	$84
		.WORD	_sprA02_B8_A
		.BYTE	$22
		.BYTE	$EA,$48,$80,$09
		.BYTE	$EA,$48,$80,$F0
_sprA02_BC:
		.BYTE	$6C,$03
		.BYTE	$00,$8A,$10
		.BYTE	$00,$8E,$E0
		.BYTE	$00,$9A,$18
		.BYTE	$00,$9E,$E8
		.BYTE	$00,$AE,$F8
		.BYTE	$00,$BE,$00
		.BYTE	$F0,$88,$10
		.BYTE	$F0,$8C,$E0
		.BYTE	$F0,$98,$18
		.BYTE	$F0,$9C,$E8
		.BYTE	$F0,$AC,$F8
		.BYTE	$F0,$BC,$00
_sprB02_C0:
		.BYTE	$03
		.BYTE	$CE,$EC,$23,$F0
		.BYTE	$CE,$FC,$23,$F8
		.BYTE	$DC,$C8,$23,$F4
		.BYTE	$26
_sprB02_C0_A:
		.BYTE	$E8,$D0,$23,$F4
		.BYTE	$E8,$E0,$23,$FC
		.BYTE	$E8,$F0,$23,$04
		.BYTE	$F8,$D2,$23,$F4
		.BYTE	$F8,$E2,$23,$FC
		.BYTE	$F8,$C2,$23,$04
_sprB02_C1:
		.BYTE	$44,$23
		.BYTE	$D4,$EC,$01
		.BYTE	$D4,$FC,$09
		.BYTE	$DD,$CC,$F8
		.BYTE	$DD,$DC,$00
		.BYTE	$A6
		.WORD	_sprB02_C0_A
_sprB02_C2:
		.BYTE	$44,$23
		.BYTE	$E4,$EC,$02
		.BYTE	$E4,$FC,$0A
		.BYTE	$E8,$CA,$F7
		.BYTE	$E8,$CA,$FF
		.BYTE	$26
_sprB02_C2_A:
		.BYTE	$E8,$D4,$23,$F4
		.BYTE	$E8,$E4,$23,$FC
		.BYTE	$E8,$F4,$23,$04
		.BYTE	$F8,$C4,$23,$F4
		.BYTE	$F8,$E6,$23,$FC
		.BYTE	$F8,$F6,$23,$04
_sprB02_C3:
		.BYTE	$04
		.BYTE	$E4,$CC,$63,$F8
		.BYTE	$F4,$EC,$23,$01
		.BYTE	$F4,$FC,$23,$09
		.BYTE	$F5,$DC,$63,$FF
		.BYTE	$A6
		.WORD	_sprB02_C2_A
_sprB02_C4:
		.BYTE	$03
		.BYTE	$EF,$C8,$23,$F5
		.BYTE	$FB,$EC,$23,$F1
		.BYTE	$FB,$FC,$23,$F9
		.BYTE	$A6
		.WORD	_sprB02_C0_A
_sprB02_C5:
		.BYTE	$45,$23
		.BYTE	$EE,$CC,$E9
		.BYTE	$EE,$DC,$F1
		.BYTE	$F6,$EC,$E0
		.BYTE	$F6,$FC,$E8
		.BYTE	$F8,$C6,$04
		.BYTE	$A5
		.WORD	_sprB02_C0_A
_sprB02_C6:
		.BYTE	$04
		.BYTE	$E6,$EC,$23,$DF
		.BYTE	$E6,$FC,$23,$E7
		.BYTE	$EA,$CA,$23,$EE
		.BYTE	$EA,$CA,$63,$E8
		.BYTE	$A6
		.WORD	_sprB02_C2_A
_sprB02_C7:
		.BYTE	$04
		.BYTE	$D7,$EC,$23,$E0
		.BYTE	$D7,$FC,$23,$E8
		.BYTE	$DD,$CC,$63,$EF
		.BYTE	$DD,$DC,$63,$E7
		.BYTE	$A6
		.WORD	_sprB02_C2_A
_sprB02_C8:
		.BYTE	$03
_sprB02_C8_A:
		.BYTE	$09,$EC,$23,$EF
		.BYTE	$09,$FC,$23,$F7
		.BYTE	$E8,$D8,$23,$F4
		.BYTE	$A6
		.WORD	_sprB02_CF_B
_sprB02_C9:
		.BYTE	$02
		.BYTE	$1B,$EC,$23,$EF
		.BYTE	$1B,$FC,$23,$F7
		.BYTE	$A8
		.WORD	_sprB02_CF_A
_sprB02_CA:
		.BYTE	$02
		.BYTE	$2C,$EC,$23,$F0
		.BYTE	$2C,$FC,$23,$F8
		.BYTE	$A9
		.WORD	_sprB02_CF_A
_sprB02_CB:
		.BYTE	$02
		.BYTE	$3C,$EC,$23,$F0
		.BYTE	$3C,$FC,$23,$F8
		.BYTE	$AA
		.WORD	_sprB02_CF_A
_sprB02_CC:
		.BYTE	$02
		.BYTE	$4D,$EC,$23,$F0
		.BYTE	$4D,$FC,$23,$F8
		.BYTE	$AB
		.WORD	_sprB02_CF_A
_sprB02_CD:
		.BYTE	$02
		.BYTE	$5C,$EC,$23,$F0
		.BYTE	$5C,$FC,$23,$F8
		.BYTE	$AC
		.WORD	_sprB02_CF_A
_sprB02_CE:
		.BYTE	$02
		.BYTE	$D7,$EC,$23,$F0
		.BYTE	$D7,$EC,$63,$F8
		.BYTE	$AE
		.WORD	_sprB02_CF_A
_sprB02_CF:
		.BYTE	$05
		.BYTE	$D8,$C8,$23,$F3
		.BYTE	$E3,$48,$23,$FC
		.BYTE	$E4,$EC,$23,$EF
		.BYTE	$E4,$EC,$63,$F7
		.BYTE	$EF,$48,$23,$EB
		.BYTE	$2E
_sprB02_CF_A:
		.BYTE	$E8,$D8,$23,$F4
_sprB02_CF_B:
		.BYTE	$E8,$E8,$23,$FC
_sprB02_CF_C:
		.BYTE	$E8,$F8,$23,$04
		.BYTE	$F8,$DA,$23,$F4
		.BYTE	$F8,$EA,$23,$FC
		.BYTE	$F8,$FA,$23,$04
		.BYTE	$FE,$C8,$23,$F3
		.BYTE	$0E,$C8,$23,$F3
		.BYTE	$1E,$C8,$23,$F3
		.BYTE	$2E,$C8,$23,$F3
		.BYTE	$3E,$C8,$23,$F3
		.BYTE	$4E,$C8,$23,$F3
		.BYTE	$5E,$C8,$23,$F3
		.BYTE	$C8,$C8,$23,$F3
_sprB02_D0:
		.BYTE	$33
_sprB02_D0_A:
		.BYTE	$03,$C8,$23,$F3
		.BYTE	$13,$C8,$23,$F3
		.BYTE	$23,$C8,$23,$F3
		.BYTE	$33,$C8,$23,$F3
		.BYTE	$43,$C8,$23,$F3
		.BYTE	$53,$C8,$23,$F3
		.BYTE	$63,$C8,$23,$F3
		.BYTE	$CD,$C8,$23,$F3
		.BYTE	$DD,$C8,$23,$F3
		.BYTE	$E9,$EC,$23,$EF
		.BYTE	$E9,$EC,$63,$F7
		.BYTE	$ED,$D8,$23,$F4
		.BYTE	$ED,$F8,$23,$04
		.BYTE	$FD,$DA,$23,$F4
		.BYTE	$FD,$EA,$23,$FC
		.BYTE	$FD,$FA,$23,$04
		.BYTE	$ED,$E4,$23,$FC
		.BYTE	$E5,$58,$23,$FE
		.BYTE	$F8,$58,$23,$EC
_sprB02_D1:
		.BYTE	$90
		.WORD	_sprB02_D0_A
		.BYTE	$21
		.BYTE	$ED,$E8,$23,$FC
_sprB02_D2:
		.BYTE	$01
		.BYTE	$E8,$E4,$23,$FC
		.BYTE	$83
		.WORD	_sprB02_C8_A
		.BYTE	$A5
		.WORD	_sprB02_CF_C
